// Copyright © 2026 Richard M. Hamilton.
// SPDX-License-Identifier: GPL-3.0-only
// Additional permission: Copperfin Application, Runtime, and Toolchain Exception 1.0; see LICENSE.

#pragma once

#include "copperfin/studio/designer_context.h"
#include "copperfin/runtime/prg_engine.h"
#include "copperfin/vfp/asset_inspector.h"
#include "copperfin/vfp/dbf_table.h"

#include <cstdint>
#include <string>
#include <vector>

namespace copperfin::localization {
struct LocalizedCatalog;
}

namespace copperfin::studio {

enum class StudioAssetKind {
    unknown,
    project,
    form,
    class_library,
    report,
    label,
    menu,
    index,
    table,
    database_container,
    program,
    header
};

enum class StudioUndoMode {
    unspecified,
    edit,
    command
};

inline constexpr std::size_t StudioObjectMissingFieldIndex = static_cast<std::size_t>(-1);
inline constexpr std::size_t StudioObjectMissingLineIndex = static_cast<std::size_t>(-1);
inline constexpr std::size_t StudioObjectMissingRecordIndex = static_cast<std::size_t>(-1);

struct StudioObjectSelector {
    std::size_t record_index = 0;
    std::string object_name{};
    std::string unique_id{};
};

struct StudioDeletedStateSelector {
    std::size_t record_index = 0;
    std::string object_name{};
    std::string unique_id{};
    bool deleted = false;
    bool deleted_available = false;
};

struct StudioFieldValueAssignment {
    std::string property_name{};
    std::string property_value{};
};

struct StudioOpenRequest {
    std::string path{};
    std::string symbol{};
    std::string property_name{};
    std::string property_value{};
    std::string new_property_name{};
    std::string object_name{};
    std::string unique_id{};
    std::string new_object_name{};
    std::string new_name{};
    std::string new_unique_id{};
    std::string parent_name{};
    std::string parent_unique_id{};
    std::string placement{};
    std::string target_object_name{};
    std::string target_unique_id{};
    std::string alignment_mode{};
    std::string resize_mode{};
    std::string distribution_mode{};
    std::string snap_mode{};
    std::string nudge_mode{};
    std::string caption{};
    std::string picture{};
    std::string down_picture{};
    std::string disabled_picture{};
    std::string ole_drag_picture{};
    std::string mouse_icon{};
    std::string drag_icon{};
    std::string tooltip_text{};
    std::string status_bar_text{};
    std::string link_master{};
    std::string control_source{};
    std::string current_control{};
    std::string input_mask{};
    std::string format{};
    std::string row_source{};
    std::string column_widths{};
    bool column_lines = false;
    bool integral_height = false;
    bool incremental_search = false;
    bool multi_select = false;
    std::string record_source{};
    std::string form_set_class{};
    std::string default_file_path{};
    std::string initial_selected_alias{};
    std::string display_value{};
    std::string font_name{};
    std::string dynamic_back_color{};
    std::string dynamic_fore_color{};
    std::string dynamic_input_mask{};
    std::string dynamic_line_height{};
    std::string dynamic_alignment{};
    std::string dynamic_current_control{};
    std::string dynamic_font_name{};
    std::string dynamic_font_size{};
    std::string dynamic_font_bold{};
    std::string dynamic_font_italic{};
    std::string dynamic_font_underline{};
    std::string dynamic_font_strikethru{};
    std::string dynamic_font_outline{};
    std::string dynamic_font_shadow{};
    std::string anchor_object_name{};
    std::string anchor_unique_id{};
    double grid_width = 0.0;
    double grid_height = 0.0;
    double delta_hpos = 0.0;
    double delta_vpos = 0.0;
    double font_size = 0.0;
    int starting_tab_index = 0;
    int row_source_type = 0;
    int bound_column = 0;
    int column_count = 0;
    int style = 0;
    int list_index = 0;
    int left_column = 0;
    int tab_orientation = 0;
    int display_orientation = 0;
    int help_context_id = 0;
    int whats_this_help_id = 0;
    int drag_mode = 0;
    int ole_drag_mode = 0;
    int ole_drop_mode = 0;
    int ole_drop_effects = 0;
    int ole_drop_text_insertion = 0;
    int button_count = 0;
    int curvature = 0;
    int draw_mode = 0;
    int draw_style = 0;
    int draw_width = 0;
    int fill_style = 0;
    int scale_mode = 0;
    int buffer_mode = 0;
    int buffer_mode_override = 0;
    int data_session = 0;
    int grid_line_color = 0;
    int header_height = 0;
    int row_height = 0;
    int max_height = 0;
    int min_height = 0;
    int back_style = 0;
    int border_style = 0;
    int border_width = 0;
    int border_color = 0;
    int special_effect = 0;
    int scroll_bars = 0;
    int window_state = 0;
    int show_window = 0;
    int title_bar = 0;
    int mouse_pointer = 0;
    int picture_margin = 0;
    int picture_position = 0;
    int picture_spacing = 0;
    int picture_selection_display = 0;
    int max_width = 0;
    int min_width = 0;
    int max_left = 0;
    int max_top = 0;
    int lock_columns = 0;
    int lock_columns_left = 0;
    int grid_line_width = 0;
    int grid_lines = 0;
    int highlight_row_line_width = 0;
    int partition = 0;
    int record_source_type = 0;
    int column_order = 0;
    int highlight_style = 0;
    int child_order = 0;
    int fill_color = 0;
    int list_item_id = 0;
    int selected_back_color = 0;
    int selected_fore_color = 0;
    int selected_item_back_color = 0;
    int selected_item_fore_color = 0;
    int disabled_item_back_color = 0;
    int disabled_item_fore_color = 0;
    int item_back_color = 0;
    int item_fore_color = 0;
    int highlight_back_color = 0;
    int highlight_fore_color = 0;
    int back_color = 0;
    int fore_color = 0;
    int disabled_back_color = 0;
    int disabled_fore_color = 0;
    std::size_t line = 0;
    std::size_t column = 0;
    std::size_t record_index = 0;
    bool launched_from_visual_studio = false;
    bool read_only = false;
    bool load_full_table = false;
    bool apply_property_update = false;
    bool clear_property = false;
    bool rename_property = false;
    bool delete_object = false;
    bool restore_object = false;
    bool deleted_states = false;
    bool subtree_deleted_state = false;
    bool duplicate_object = false;
    bool rename_object = false;
    bool reparent_object = false;
    bool reorder_object = false;
    bool group_object = false;
    bool align_object = false;
    bool resize_object = false;
    bool distribute_object = false;
    bool snap_object = false;
    bool nudge_object = false;
    bool tab_order_object = false;
    bool tab_stop_object = false;
    bool visibility_object = false;
    bool enabled_object = false;
    bool read_only_object = false;
    bool locked_object = false;
    bool caption_object = false;
    bool tooltip_text_object = false;
    bool status_bar_text_object = false;
    bool link_master_object = false;
    bool control_source_object = false;
    bool current_control_object = false;
    bool input_mask_object = false;
    bool format_object = false;
    bool row_source_object = false;
    bool column_widths_object = false;
    bool column_lines_object = false;
    bool integral_height_object = false;
    bool incremental_search_object = false;
    bool multi_select_object = false;
    bool row_source_type_object = false;
    bool bound_column_object = false;
    bool column_count_object = false;
    bool style_object = false;
    bool list_index_object = false;
    bool left_column_object = false;
    bool display_value_object = false;
    bool selected_back_color_object = false;
    bool selected_fore_color_object = false;
    bool selected_item_back_color_object = false;
    bool selected_item_fore_color_object = false;
    bool disabled_item_back_color_object = false;
    bool disabled_item_fore_color_object = false;
    bool item_back_color_object = false;
    bool item_fore_color_object = false;
    bool highlight_back_color_object = false;
    bool highlight_fore_color_object = false;
    bool back_color_object = false;
    bool fore_color_object = false;
    bool disabled_back_color_object = false;
    bool disabled_fore_color_object = false;
    bool dynamic_back_color_object = false;
    bool dynamic_fore_color_object = false;
    bool closable_object = false;
    bool control_box_object = false;
    bool allow_output_object = false;
    bool bind_controls_object = false;
    bool auto_verb_menu_object = false;
    bool desktop_object = false;
    bool key_preview_object = false;
    bool mac_desktop_object = false;
    bool max_button_object = false;
    bool min_button_object = false;
    bool min_height_object = false;
    bool min_width_object = false;
    bool max_height_object = false;
    bool movable_object = false;
    bool half_height_caption_object = false;
    bool mdi_form_object = false;
    bool back_style_object = false;
    bool border_style_object = false;
    bool border_width_object = false;
    bool border_color_object = false;
    bool special_effect_object = false;
    bool scroll_bars_object = false;
    bool window_state_object = false;
    bool show_window_object = false;
    bool title_bar_object = false;
    bool mouse_pointer_object = false;
    bool picture_margin_object = false;
    bool picture_position_object = false;
    bool picture_spacing_object = false;
    bool picture_selection_display_object = false;
    bool dynamic_input_mask_object = false;
    bool dynamic_line_height_object = false;
    bool dynamic_alignment_object = false;
    bool dynamic_current_control_object = false;
    bool dynamic_font_name_object = false;
    bool dynamic_font_size_object = false;
    bool dynamic_font_bold_object = false;
    bool dynamic_font_italic_object = false;
    bool dynamic_font_underline_object = false;
    bool dynamic_font_strikethru_object = false;
    bool dynamic_font_outline_object = false;
    bool dynamic_font_shadow_object = false;
    bool font_name_object = false;
    bool font_size_object = false;
    bool font_bold_object = false;
    bool font_italic_object = false;
    bool font_underline_object = false;
    bool font_strikethru_object = false;
    bool font_outline_object = false;
    bool font_shadow_object = false;
    bool max_width_object = false;
    bool max_left_object = false;
    bool max_top_object = false;
    bool auto_center_object = false;
    bool auto_size_object = false;
    bool auto_release_object = false;
    bool continuous_scroll_object = false;
    bool dockable_object = false;
    bool clip_controls_object = false;
    bool sparse_object = false;
    bool lock_screen_object = false;
    bool hide_selection_object = false;
    bool allow_cell_selection_object = false;
    bool delete_mark_object = false;
    bool record_mark_object = false;
    bool split_bar_object = false;
    bool highlight_row_object = false;
    bool panel_link_object = false;
    bool allow_header_sizing_object = false;
    bool allow_row_sizing_object = false;
    bool resizable_object = false;
    bool add_line_feeds_object = false;
    bool always_on_top_object = false;
    bool always_on_bottom_object = false;
    bool picture_object = false;
    bool down_picture_object = false;
    bool disabled_picture_object = false;
    bool ole_drag_picture_object = false;
    bool mouse_icon_object = false;
    bool drag_icon_object = false;
    bool drag_mode_object = false;
    bool ole_drag_mode_object = false;
    bool ole_drop_mode_object = false;
    bool ole_drop_effects_object = false;
    bool ole_drop_text_insertion_object = false;
    bool button_count_object = false;
    bool curvature_object = false;
    bool draw_mode_object = false;
    bool draw_style_object = false;
    bool draw_width_object = false;
    bool fill_style_object = false;
    bool scale_mode_object = false;
    bool buffer_mode_object = false;
    bool buffer_mode_override_object = false;
    bool data_session_object = false;
    bool grid_line_color_object = false;
    bool header_height_object = false;
    bool row_height_object = false;
    bool lock_columns_object = false;
    bool lock_columns_left_object = false;
    bool grid_line_width_object = false;
    bool grid_lines_object = false;
    bool highlight_row_line_width_object = false;
    bool partition_object = false;
    bool record_source_type_object = false;
    bool column_order_object = false;
    bool highlight_style_object = false;
    bool child_order_object = false;
    bool fill_color_object = false;
    bool list_item_id_object = false;
    bool tab_orientation_object = false;
    bool display_orientation_object = false;
    bool help_context_id_object = false;
    bool whats_this_help_id_object = false;
    bool whats_this_help_object = false;
    bool whats_this_button_object = false;
    bool record_source_object = false;
    bool form_set_class_object = false;
    bool default_file_path_object = false;
    bool initial_selected_alias_object = false;
    bool ungroup_object = false;
    bool tab_stop = false;
    bool visible = false;
    bool enabled = false;
    bool subtree_deleted = false;
    bool object_read_only = false;
    bool locked = false;
    bool whats_this_help = false;
    bool whats_this_button = false;
    bool clear_parent = false;
    bool selection_record_available = false;
    bool starting_tab_index_available = false;
    bool tab_stop_available = false;
    bool visible_available = false;
    bool enabled_available = false;
    bool subtree_deleted_available = false;
    bool object_read_only_available = false;
    bool locked_available = false;
    bool caption_available = false;
    bool picture_available = false;
    bool down_picture_available = false;
    bool disabled_picture_available = false;
    bool ole_drag_picture_available = false;
    bool mouse_icon_available = false;
    bool drag_icon_available = false;
    bool drag_mode_available = false;
    bool ole_drag_mode_available = false;
    bool ole_drop_mode_available = false;
    bool ole_drop_effects_available = false;
    bool ole_drop_text_insertion_available = false;
    bool button_count_available = false;
    bool curvature_available = false;
    bool draw_mode_available = false;
    bool draw_style_available = false;
    bool draw_width_available = false;
    bool fill_style_available = false;
    bool scale_mode_available = false;
    bool buffer_mode_available = false;
    bool buffer_mode_override_available = false;
    bool data_session_available = false;
    bool grid_line_color_available = false;
    bool header_height_available = false;
    bool row_height_available = false;
    bool lock_columns_available = false;
    bool lock_columns_left_available = false;
    bool grid_line_width_available = false;
    bool grid_lines_available = false;
    bool highlight_row_line_width_available = false;
    bool partition_available = false;
    bool record_source_type_available = false;
    bool column_order_available = false;
    bool highlight_style_available = false;
    bool child_order_available = false;
    bool fill_color_available = false;
    bool list_item_id_available = false;
    bool tab_orientation_available = false;
    bool display_orientation_available = false;
    bool help_context_id_available = false;
    bool whats_this_help_id_available = false;
    bool whats_this_help_available = false;
    bool whats_this_button_available = false;
    bool record_source_available = false;
    bool form_set_class_available = false;
    bool default_file_path_available = false;
    bool initial_selected_alias_available = false;
    bool tooltip_text_available = false;
    bool status_bar_text_available = false;
    bool link_master_available = false;
    bool control_source_available = false;
    bool current_control_available = false;
    bool input_mask_available = false;
    bool format_available = false;
    bool row_source_available = false;
    bool column_widths_available = false;
    bool column_lines_available = false;
    bool integral_height_available = false;
    bool incremental_search_available = false;
    bool multi_select_available = false;
    bool row_source_type_available = false;
    bool bound_column_available = false;
    bool column_count_available = false;
    bool style_available = false;
    bool list_index_available = false;
    bool left_column_available = false;
    bool display_value_available = false;
    bool selected_back_color_available = false;
    bool selected_fore_color_available = false;
    bool selected_item_back_color_available = false;
    bool selected_item_fore_color_available = false;
    bool disabled_item_back_color_available = false;
    bool disabled_item_fore_color_available = false;
    bool item_back_color_available = false;
    bool item_fore_color_available = false;
    bool highlight_back_color_available = false;
    bool highlight_fore_color_available = false;
    bool back_color_available = false;
    bool fore_color_available = false;
    bool disabled_back_color_available = false;
    bool disabled_fore_color_available = false;
    bool dynamic_back_color_available = false;
    bool dynamic_fore_color_available = false;
    bool closable_available = false;
    bool control_box_available = false;
    bool allow_output_available = false;
    bool bind_controls_available = false;
    bool auto_verb_menu_available = false;
    bool desktop_available = false;
    bool key_preview_available = false;
    bool mac_desktop_available = false;
    bool max_button_available = false;
    bool min_button_available = false;
    bool min_height_available = false;
    bool min_width_available = false;
    bool max_height_available = false;
    bool movable_available = false;
    bool half_height_caption_available = false;
    bool mdi_form_available = false;
    bool back_style_available = false;
    bool border_style_available = false;
    bool border_width_available = false;
    bool border_color_available = false;
    bool special_effect_available = false;
    bool scroll_bars_available = false;
    bool window_state_available = false;
    bool show_window_available = false;
    bool title_bar_available = false;
    bool mouse_pointer_available = false;
    bool picture_margin_available = false;
    bool picture_position_available = false;
    bool picture_spacing_available = false;
    bool picture_selection_display_available = false;
    bool dynamic_input_mask_available = false;
    bool dynamic_line_height_available = false;
    bool dynamic_alignment_available = false;
    bool dynamic_current_control_available = false;
    bool dynamic_font_name_available = false;
    bool dynamic_font_size_available = false;
    bool dynamic_font_bold_available = false;
    bool dynamic_font_italic_available = false;
    bool dynamic_font_underline_available = false;
    bool dynamic_font_strikethru_available = false;
    bool dynamic_font_outline_available = false;
    bool dynamic_font_shadow_available = false;
    bool font_name_available = false;
    bool font_size_available = false;
    bool font_bold_available = false;
    bool font_italic_available = false;
    bool font_underline_available = false;
    bool font_strikethru_available = false;
    bool font_outline_available = false;
    bool font_shadow_available = false;
    bool max_width_available = false;
    bool max_left_available = false;
    bool max_top_available = false;
    bool auto_center_available = false;
    bool auto_size_available = false;
    bool auto_release_available = false;
    bool continuous_scroll_available = false;
    bool dockable_available = false;
    bool clip_controls_available = false;
    bool sparse_available = false;
    bool lock_screen_available = false;
    bool hide_selection_available = false;
    bool allow_cell_selection_available = false;
    bool delete_mark_available = false;
    bool record_mark_available = false;
    bool split_bar_available = false;
    bool highlight_row_available = false;
    bool panel_link_available = false;
    bool allow_header_sizing_available = false;
    bool allow_row_sizing_available = false;
    bool resizable_available = false;
    bool add_line_feeds_available = false;
    bool always_on_top_available = false;
    bool always_on_bottom_available = false;
    bool closable = false;
    bool control_box = false;
    bool allow_output = false;
    bool font_bold = false;
    bool font_italic = false;
    bool font_underline = false;
    bool font_strikethru = false;
    bool font_outline = false;
    bool font_shadow = false;
    bool bind_controls = false;
    bool auto_verb_menu = false;
    bool desktop = false;
    bool key_preview = false;
    bool mac_desktop = false;
    bool max_button = false;
    bool min_button = false;
    bool movable = false;
    bool half_height_caption = false;
    bool mdi_form = false;
    bool auto_center = false;
    bool auto_size = false;
    bool auto_release = false;
    bool continuous_scroll = false;
    bool dockable = false;
    bool clip_controls = false;
    bool sparse = false;
    bool lock_screen = false;
    bool hide_selection = false;
    bool allow_cell_selection = false;
    bool delete_mark = false;
    bool record_mark = false;
    bool split_bar = false;
    bool highlight_row = false;
    bool panel_link = false;
    bool allow_header_sizing = false;
    bool allow_row_sizing = false;
    bool resizable = false;
    bool add_line_feeds = false;
    bool always_on_top = false;
    bool always_on_bottom = false;
    StudioUndoMode undo_mode = StudioUndoMode::unspecified;
    std::string undo_label{};
    std::vector<StudioFieldValueAssignment> field_values{};
    std::vector<StudioObjectSelector> group_objects{};
    std::vector<StudioObjectSelector> align_objects{};
    std::vector<StudioObjectSelector> resize_objects{};
    std::vector<StudioObjectSelector> distribute_objects{};
    std::vector<StudioObjectSelector> snap_objects{};
    std::vector<StudioObjectSelector> nudge_objects{};
    std::vector<StudioObjectSelector> tab_order_objects{};
    std::vector<StudioObjectSelector> tab_stop_objects{};
    std::vector<StudioObjectSelector> visibility_objects{};
    std::vector<StudioDeletedStateSelector> deleted_state_objects{};
    std::vector<StudioObjectSelector> enabled_objects{};
    std::vector<StudioObjectSelector> read_only_objects{};
    std::vector<StudioObjectSelector> locked_objects{};
    std::vector<StudioObjectSelector> caption_objects{};
    std::vector<StudioObjectSelector> tooltip_text_objects{};
    std::vector<StudioObjectSelector> status_bar_text_objects{};
    std::vector<StudioObjectSelector> link_master_objects{};
    std::vector<StudioObjectSelector> control_source_objects{};
    std::vector<StudioObjectSelector> current_control_objects{};
    std::vector<StudioObjectSelector> input_mask_objects{};
    std::vector<StudioObjectSelector> format_objects{};
    std::vector<StudioObjectSelector> row_source_objects{};
    std::vector<StudioObjectSelector> column_widths_objects{};
    std::vector<StudioObjectSelector> column_lines_objects{};
    std::vector<StudioObjectSelector> integral_height_objects{};
    std::vector<StudioObjectSelector> incremental_search_objects{};
    std::vector<StudioObjectSelector> multi_select_objects{};
    std::vector<StudioObjectSelector> row_source_type_objects{};
    std::vector<StudioObjectSelector> bound_column_objects{};
    std::vector<StudioObjectSelector> column_count_objects{};
    std::vector<StudioObjectSelector> style_objects{};
    std::vector<StudioObjectSelector> list_index_objects{};
    std::vector<StudioObjectSelector> left_column_objects{};
    std::vector<StudioObjectSelector> display_value_objects{};
    std::vector<StudioObjectSelector> selected_back_color_objects{};
    std::vector<StudioObjectSelector> selected_fore_color_objects{};
    std::vector<StudioObjectSelector> selected_item_back_color_objects{};
    std::vector<StudioObjectSelector> selected_item_fore_color_objects{};
    std::vector<StudioObjectSelector> disabled_item_back_color_objects{};
    std::vector<StudioObjectSelector> disabled_item_fore_color_objects{};
    std::vector<StudioObjectSelector> item_back_color_objects{};
    std::vector<StudioObjectSelector> item_fore_color_objects{};
    std::vector<StudioObjectSelector> highlight_back_color_objects{};
    std::vector<StudioObjectSelector> highlight_fore_color_objects{};
    std::vector<StudioObjectSelector> back_color_objects{};
    std::vector<StudioObjectSelector> fore_color_objects{};
    std::vector<StudioObjectSelector> disabled_back_color_objects{};
    std::vector<StudioObjectSelector> disabled_fore_color_objects{};
    std::vector<StudioObjectSelector> dynamic_back_color_objects{};
    std::vector<StudioObjectSelector> dynamic_fore_color_objects{};
    std::vector<StudioObjectSelector> closable_objects{};
    std::vector<StudioObjectSelector> control_box_objects{};
    std::vector<StudioObjectSelector> allow_output_objects{};
    std::vector<StudioObjectSelector> bind_controls_objects{};
    std::vector<StudioObjectSelector> auto_verb_menu_objects{};
    std::vector<StudioObjectSelector> desktop_objects{};
    std::vector<StudioObjectSelector> key_preview_objects{};
    std::vector<StudioObjectSelector> mac_desktop_objects{};
    std::vector<StudioObjectSelector> max_button_objects{};
    std::vector<StudioObjectSelector> min_button_objects{};
    std::vector<StudioObjectSelector> min_height_objects{};
    std::vector<StudioObjectSelector> min_width_objects{};
    std::vector<StudioObjectSelector> max_height_objects{};
    std::vector<StudioObjectSelector> movable_objects{};
    std::vector<StudioObjectSelector> half_height_caption_objects{};
    std::vector<StudioObjectSelector> mdi_form_objects{};
    std::vector<StudioObjectSelector> back_style_objects{};
    std::vector<StudioObjectSelector> border_style_objects{};
    std::vector<StudioObjectSelector> border_width_objects{};
    std::vector<StudioObjectSelector> border_color_objects{};
    std::vector<StudioObjectSelector> special_effect_objects{};
    std::vector<StudioObjectSelector> scroll_bars_objects{};
    std::vector<StudioObjectSelector> window_state_objects{};
    std::vector<StudioObjectSelector> show_window_objects{};
    std::vector<StudioObjectSelector> title_bar_objects{};
    std::vector<StudioObjectSelector> mouse_pointer_objects{};
    std::vector<StudioObjectSelector> picture_margin_objects{};
    std::vector<StudioObjectSelector> picture_position_objects{};
    std::vector<StudioObjectSelector> picture_spacing_objects{};
    std::vector<StudioObjectSelector> picture_selection_display_objects{};
    std::vector<StudioObjectSelector> dynamic_input_mask_objects{};
    std::vector<StudioObjectSelector> dynamic_line_height_objects{};
    std::vector<StudioObjectSelector> dynamic_alignment_objects{};
    std::vector<StudioObjectSelector> dynamic_current_control_objects{};
    std::vector<StudioObjectSelector> dynamic_font_name_objects{};
    std::vector<StudioObjectSelector> dynamic_font_size_objects{};
    std::vector<StudioObjectSelector> dynamic_font_bold_objects{};
    std::vector<StudioObjectSelector> dynamic_font_italic_objects{};
    std::vector<StudioObjectSelector> dynamic_font_underline_objects{};
    std::vector<StudioObjectSelector> dynamic_font_strikethru_objects{};
    std::vector<StudioObjectSelector> dynamic_font_outline_objects{};
    std::vector<StudioObjectSelector> dynamic_font_shadow_objects{};
    std::vector<StudioObjectSelector> font_name_objects{};
    std::vector<StudioObjectSelector> font_size_objects{};
    std::vector<StudioObjectSelector> font_bold_objects{};
    std::vector<StudioObjectSelector> font_italic_objects{};
    std::vector<StudioObjectSelector> font_underline_objects{};
    std::vector<StudioObjectSelector> font_strikethru_objects{};
    std::vector<StudioObjectSelector> font_outline_objects{};
    std::vector<StudioObjectSelector> font_shadow_objects{};
    std::vector<StudioObjectSelector> max_width_objects{};
    std::vector<StudioObjectSelector> max_left_objects{};
    std::vector<StudioObjectSelector> max_top_objects{};
    std::vector<StudioObjectSelector> auto_center_objects{};
    std::vector<StudioObjectSelector> auto_size_objects{};
    std::vector<StudioObjectSelector> auto_release_objects{};
    std::vector<StudioObjectSelector> continuous_scroll_objects{};
    std::vector<StudioObjectSelector> dockable_objects{};
    std::vector<StudioObjectSelector> clip_controls_objects{};
    std::vector<StudioObjectSelector> sparse_objects{};
    std::vector<StudioObjectSelector> lock_screen_objects{};
    std::vector<StudioObjectSelector> hide_selection_objects{};
    std::vector<StudioObjectSelector> allow_cell_selection_objects{};
    std::vector<StudioObjectSelector> delete_mark_objects{};
    std::vector<StudioObjectSelector> record_mark_objects{};
    std::vector<StudioObjectSelector> split_bar_objects{};
    std::vector<StudioObjectSelector> highlight_row_objects{};
    std::vector<StudioObjectSelector> panel_link_objects{};
    std::vector<StudioObjectSelector> allow_header_sizing_objects{};
    std::vector<StudioObjectSelector> allow_row_sizing_objects{};
    std::vector<StudioObjectSelector> resizable_objects{};
    std::vector<StudioObjectSelector> add_line_feeds_objects{};
    std::vector<StudioObjectSelector> always_on_top_objects{};
    std::vector<StudioObjectSelector> always_on_bottom_objects{};
    std::vector<StudioObjectSelector> picture_objects{};
    std::vector<StudioObjectSelector> down_picture_objects{};
    std::vector<StudioObjectSelector> disabled_picture_objects{};
    std::vector<StudioObjectSelector> ole_drag_picture_objects{};
    std::vector<StudioObjectSelector> mouse_icon_objects{};
    std::vector<StudioObjectSelector> drag_icon_objects{};
    std::vector<StudioObjectSelector> drag_mode_objects{};
    std::vector<StudioObjectSelector> ole_drag_mode_objects{};
    std::vector<StudioObjectSelector> ole_drop_mode_objects{};
    std::vector<StudioObjectSelector> ole_drop_effects_objects{};
    std::vector<StudioObjectSelector> ole_drop_text_insertion_objects{};
    std::vector<StudioObjectSelector> button_count_objects{};
    std::vector<StudioObjectSelector> curvature_objects{};
    std::vector<StudioObjectSelector> draw_mode_objects{};
    std::vector<StudioObjectSelector> draw_style_objects{};
    std::vector<StudioObjectSelector> draw_width_objects{};
    std::vector<StudioObjectSelector> fill_style_objects{};
    std::vector<StudioObjectSelector> scale_mode_objects{};
    std::vector<StudioObjectSelector> buffer_mode_objects{};
    std::vector<StudioObjectSelector> buffer_mode_override_objects{};
    std::vector<StudioObjectSelector> data_session_objects{};
    std::vector<StudioObjectSelector> grid_line_color_objects{};
    std::vector<StudioObjectSelector> header_height_objects{};
    std::vector<StudioObjectSelector> row_height_objects{};
    std::vector<StudioObjectSelector> lock_columns_objects{};
    std::vector<StudioObjectSelector> lock_columns_left_objects{};
    std::vector<StudioObjectSelector> grid_line_width_objects{};
    std::vector<StudioObjectSelector> grid_lines_objects{};
    std::vector<StudioObjectSelector> highlight_row_line_width_objects{};
    std::vector<StudioObjectSelector> partition_objects{};
    std::vector<StudioObjectSelector> record_source_type_objects{};
    std::vector<StudioObjectSelector> column_order_objects{};
    std::vector<StudioObjectSelector> highlight_style_objects{};
    std::vector<StudioObjectSelector> child_order_objects{};
    std::vector<StudioObjectSelector> fill_color_objects{};
    std::vector<StudioObjectSelector> list_item_id_objects{};
    std::vector<StudioObjectSelector> tab_orientation_objects{};
    std::vector<StudioObjectSelector> display_orientation_objects{};
    std::vector<StudioObjectSelector> help_context_id_objects{};
    std::vector<StudioObjectSelector> whats_this_help_id_objects{};
    std::vector<StudioObjectSelector> whats_this_help_objects{};
    std::vector<StudioObjectSelector> whats_this_button_objects{};
    std::vector<StudioObjectSelector> record_source_objects{};
    std::vector<StudioObjectSelector> form_set_class_objects{};
    std::vector<StudioObjectSelector> default_file_path_objects{};
    std::vector<StudioObjectSelector> initial_selected_alias_objects{};
    std::vector<StudioEditorSelectionContext> designer_selection_contexts{};
};

struct StudioDocumentModel {
    std::string path;
    std::string display_name;
    std::string sidecar_path;
    std::string selection_symbol;
    StudioAssetKind kind = StudioAssetKind::unknown;
    bool has_sidecar = false;
    bool read_only = false;
    bool launched_from_visual_studio = false;
    bool selection_record_available = false;
    std::size_t selection_line = 0;
    std::size_t selection_column = 0;
    std::size_t selection_record_index = 0;
    vfp::AssetInspectionResult inspection{};
    std::vector<runtime::PrgStaticDiagnostic> static_diagnostics;
    bool table_preview_available = false;
    vfp::DbfTable table_preview{};
    std::vector<StudioDesignerContextResult> designer_contexts{};
};

struct StudioPropertySnapshot {
    std::string name{};
    std::size_t field_index = 0;
    char type = '\0';
    bool is_null = false;
    bool derived_from_property_blob = false;
    std::size_t source_line_index = StudioObjectMissingLineIndex;
    std::uint32_t memo_block_number = 0;
    std::string value{};
};

struct StudioObjectSnapshot {
    std::size_t record_index = 0;
    bool deleted = false;
    int objtype_code = 0;
    std::size_t objtype_field_index = StudioObjectMissingFieldIndex;
    std::uint32_t objtype_memo_block_number = 0;
    int objcode_code = 0;
    std::size_t objcode_field_index = StudioObjectMissingFieldIndex;
    std::uint32_t objcode_memo_block_number = 0;
    std::string platform{};
    std::size_t platform_field_index = StudioObjectMissingFieldIndex;
    std::uint32_t platform_memo_block_number = 0;
    std::string object_name{};
    std::size_t object_name_field_index = StudioObjectMissingFieldIndex;
    std::uint32_t object_name_memo_block_number = 0;
    std::string object_path{};
    std::size_t object_depth = 0;
    std::size_t sibling_index = 0;
    std::size_t sibling_count = 0;
    std::string unique_id{};
    std::size_t unique_id_field_index = StudioObjectMissingFieldIndex;
    std::uint32_t unique_id_memo_block_number = 0;
    std::string parent_name{};
    std::size_t parent_name_field_index = StudioObjectMissingFieldIndex;
    std::uint32_t parent_name_memo_block_number = 0;
    std::size_t parent_record_index = StudioObjectMissingRecordIndex;
    std::vector<std::size_t> ancestor_record_indexes{};
    std::string class_name{};
    std::size_t class_name_field_index = StudioObjectMissingFieldIndex;
    std::uint32_t class_name_memo_block_number = 0;
    std::string baseclass_name{};
    std::size_t baseclass_name_field_index = StudioObjectMissingFieldIndex;
    std::uint32_t baseclass_name_memo_block_number = 0;
    std::size_t child_count = 0;
    std::vector<std::size_t> child_record_indexes{};
    std::string menu_prompt{};
    std::size_t menu_prompt_field_index = StudioObjectMissingFieldIndex;
    std::uint32_t menu_prompt_memo_block_number = 0;
    std::string menu_level_name{};
    std::size_t menu_level_name_field_index = StudioObjectMissingFieldIndex;
    std::uint32_t menu_level_name_memo_block_number = 0;
    std::string menu_command{};
    std::size_t menu_command_field_index = StudioObjectMissingFieldIndex;
    std::uint32_t menu_command_memo_block_number = 0;
    std::string menu_message{};
    std::size_t menu_message_field_index = StudioObjectMissingFieldIndex;
    std::uint32_t menu_message_memo_block_number = 0;
    std::string title{};
    std::size_t title_field_index = StudioObjectMissingFieldIndex;
    std::uint32_t title_memo_block_number = 0;
    std::string subtitle{};
    std::size_t subtitle_field_index = StudioObjectMissingFieldIndex;
    std::uint32_t subtitle_memo_block_number = 0;
    std::vector<StudioPropertySnapshot> properties{};
};

struct StudioOpenResult {
    bool ok = false;
    StudioDocumentModel document{};
    std::string error{};
};

[[nodiscard]] StudioAssetKind studio_asset_kind_from_vfp_family(vfp::AssetFamily family);
[[nodiscard]] const char* studio_asset_kind_name(StudioAssetKind kind);
// Compatibility helper: use vfp::resolve_vfp_sidecar_path when ambiguity details are required.
[[nodiscard]] std::string infer_sidecar_path(const std::string& path, StudioAssetKind kind);
[[nodiscard]] std::vector<StudioObjectSnapshot> build_object_snapshot(const StudioDocumentModel& document);
[[nodiscard]] std::vector<StudioObjectSnapshot> build_object_snapshot(
    const StudioDocumentModel& document,
    const localization::LocalizedCatalog& catalog);
StudioOpenResult open_document(const StudioOpenRequest& request);
StudioOpenResult open_document(
    const StudioOpenRequest& request,
    const localization::LocalizedCatalog& catalog);

}  // namespace copperfin::studio
