// Copyright © 2026 Richard M. Hamilton.
// SPDX-License-Identifier: GPL-3.0-only
// Additional permission: Copperfin Application, Runtime, and Toolchain Exception 1.0; see LICENSE.

#include "runtime_pipeline_support.h"

#include <locale>

namespace copperfin::runtime {

namespace runtime_pipeline_detail {

void append_native_wrapper_response_handling_source(std::ostringstream& stream) {
    stream << "static CopperfinRuntimeBridgeHostFailureEvaluation copperfin_runtime_bridge_evaluate_host_failure(\n";
    stream << "    const CopperfinRuntimeBridgeProcessLaunch& process_launch,\n";
    stream << "    const CopperfinRuntimeBridgeFailurePolicyPlan& failure_policy_plan) {\n";
    stream << "    const bool launch_failed = !process_launch.launch_succeeded;\n";
    stream << "    const bool should_use_fallback_return =\n";
    stream << "        launch_failed && failure_policy_plan.fail_on_nonzero_exit;\n";
    stream << "    return CopperfinRuntimeBridgeHostFailureEvaluation{\n";
    stream << "        launch_failed,\n";
    stream << "        should_use_fallback_return,\n";
    stream << "        should_use_fallback_return ? failure_policy_plan.diagnostics_fallback : std::string{},\n";
    stream << "        failure_policy_plan.fallback_return_value};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeMissingResponseEvaluation copperfin_runtime_bridge_evaluate_missing_response(\n";
    stream << "    const CopperfinRuntimeBridgeHostFailureEvaluation& host_failure,\n";
    stream << "    const CopperfinRuntimeBridgeResponseReadPlan& response_read_plan,\n";
    stream << "    const std::string& response_document) {\n";
    stream << "    const auto& failure_policy_plan =\n";
    stream << "        response_read_plan.request_write_plan.request_artifact.response_validation_plan.failure_policy_plan;\n";
    stream << "    const bool response_missing = response_read_plan.require_existing_response && response_document.empty();\n";
    stream << "    const bool should_use_fallback_return =\n";
    stream << "        host_failure.should_use_fallback_return || response_missing;\n";
    stream << "    return CopperfinRuntimeBridgeMissingResponseEvaluation{\n";
    stream << "        response_missing,\n";
    stream << "        should_use_fallback_return,\n";
    stream << "        should_use_fallback_return ? failure_policy_plan.diagnostics_fallback : host_failure.diagnostics_value,\n";
    stream << "        failure_policy_plan.fallback_return_value};\n";
    stream << "}\n\n";
    stream << "static bool copperfin_runtime_bridge_find_json_field_value_start(\n";
    stream << "    const std::string& response_document,\n";
    stream << "    const std::string& field_name,\n";
    stream << "    std::size_t& value_start) {\n";
    stream << "    const auto field_token = std::string(\"\\\"\") + field_name + \"\\\"\";\n";
    stream << "    value_start = std::string::npos;\n";
    stream << "    std::size_t object_depth = 0U;\n";
    stream << "    std::size_t array_depth = 0U;\n";
    stream << "    for (std::size_t index = 0U; index < response_document.size(); ++index) {\n";
    stream << "        const char ch = response_document[index];\n";
    stream << "        if (ch == '\"') {\n";
    stream << "            std::size_t string_end = index + 1U;\n";
    stream << "            bool escaping = false;\n";
    stream << "            for (; string_end < response_document.size(); ++string_end) {\n";
    stream << "                const char string_ch = response_document[string_end];\n";
    stream << "                if (escaping) {\n";
    stream << "                    escaping = false;\n";
    stream << "                    continue;\n";
    stream << "                }\n";
    stream << "                if (string_ch == '\\\\') {\n";
    stream << "                    escaping = true;\n";
    stream << "                    continue;\n";
    stream << "                }\n";
    stream << "                if (string_ch == '\"') {\n";
    stream << "                    break;\n";
    stream << "                }\n";
    stream << "            }\n";
    stream << "            if (string_end >= response_document.size()) {\n";
    stream << "                return false;\n";
    stream << "            }\n";
    stream << "            if (object_depth == 1U && array_depth == 0U &&\n";
    stream << "                string_end + 1U == index + field_token.size() &&\n";
    stream << "                response_document.compare(index, field_token.size(), field_token) == 0) {\n";
    stream << "                const auto colon_offset = response_document.find_first_not_of(\" \\t\\r\\n\", string_end + 1U);\n";
    stream << "                if (colon_offset != std::string::npos && response_document[colon_offset] == ':') {\n";
    stream << "                    value_start = response_document.find_first_not_of(\" \\t\\r\\n\", colon_offset + 1U);\n";
    stream << "                    if (value_start == std::string::npos) {\n";
    stream << "                        return false;\n";
    stream << "                    }\n";
    stream << "                    return true;\n";
    stream << "                }\n";
    stream << "            }\n";
    stream << "            index = string_end;\n";
    stream << "            continue;\n";
    stream << "        }\n";
    stream << "        if (ch == '{') {\n";
    stream << "            ++object_depth;\n";
    stream << "            continue;\n";
    stream << "        }\n";
    stream << "        if (ch == '}' && object_depth > 0U) {\n";
    stream << "            --object_depth;\n";
    stream << "            continue;\n";
    stream << "        }\n";
    stream << "        if (ch == '[') {\n";
    stream << "            ++array_depth;\n";
    stream << "            continue;\n";
    stream << "        }\n";
    stream << "        if (ch == ']' && array_depth > 0U) {\n";
    stream << "            --array_depth;\n";
    stream << "        }\n";
    stream << "    }\n";
    stream << "    return false;\n";
    stream << "}\n\n";
    stream << "static bool copperfin_runtime_bridge_response_document_has_field(\n";
    stream << "    const std::string& response_document,\n";
    stream << "    const std::string& field_name) {\n";
    stream << "    std::size_t value_start = std::string::npos;\n";
    stream << "    return copperfin_runtime_bridge_find_json_field_value_start(response_document, field_name, value_start);\n";
    stream << "}\n\n";
    stream << "static bool copperfin_runtime_bridge_response_document_has_required_fields(\n";
    stream << "    const std::string& response_document,\n";
    stream << "    const std::vector<std::string>& required_response_fields) {\n";
    stream << "    for (const auto& required_response_field : required_response_fields) {\n";
    stream << "        if (!copperfin_runtime_bridge_response_document_has_field(\n";
    stream << "                response_document,\n";
    stream << "                required_response_field)) {\n";
    stream << "            return false;\n";
    stream << "        }\n";
    stream << "    }\n";
    stream << "    return true;\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_schema_version_field_name();\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_response_media_type_field_name();\n\n";
    stream << "static std::string copperfin_runtime_bridge_extract_json_field(\n";
    stream << "    const std::string& response_document,\n";
    stream << "    const std::string& field_name);\n\n";
    stream << "static CopperfinRuntimeBridgeResponseValidationEvaluation copperfin_runtime_bridge_evaluate_response_validation(\n";
    stream << "    const CopperfinRuntimeBridgeMissingResponseEvaluation& missing_response,\n";
    stream << "    const CopperfinRuntimeBridgeResponseValidationPlan& response_validation_plan,\n";
    stream << "    const std::string& response_document) {\n";
    stream << "    const bool response_document_available = !response_document.empty();\n";
    stream << "    const bool required_response_fields_present =\n";
    stream << "        copperfin_runtime_bridge_response_document_has_required_fields(\n";
    stream << "            response_document,\n";
    stream << "            response_validation_plan.required_response_fields);\n";
    stream << "    const auto response_media_type = copperfin_runtime_bridge_extract_json_field(\n";
    stream << "        response_document,\n";
    stream << "        copperfin_build_runtime_bridge_response_media_type_field_name());\n";
    stream << "    const bool response_media_type_matches =\n";
    stream << "        response_media_type == response_validation_plan.expected_response_media_type;\n";
    stream << "    const auto response_schema_version = copperfin_runtime_bridge_extract_json_field(\n";
    stream << "        response_document,\n";
    stream << "        copperfin_build_runtime_bridge_schema_version_field_name());\n";
    stream << "    const bool response_schema_version_matches =\n";
    stream << "        response_schema_version == response_validation_plan.expected_schema_version;\n";
    stream << "    const bool validation_failed =\n";
    stream << "        missing_response.should_use_fallback_return || !response_document_available || !required_response_fields_present || !response_media_type_matches || !response_schema_version_matches;\n";
    stream << "    const bool should_use_fallback_return = validation_failed;\n";
    stream << "    return CopperfinRuntimeBridgeResponseValidationEvaluation{\n";
    stream << "        validation_failed,\n";
    stream << "        response_document_available,\n";
    stream << "        should_use_fallback_return,\n";
    stream << "        should_use_fallback_return ? response_validation_plan.failure_policy_plan.diagnostics_fallback : std::string{},\n";
    stream << "        response_validation_plan.failure_policy_plan.fallback_return_value};\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_status_field_name() {\n";
    stream << "    return \"status\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_return_value_field_name() {\n";
    stream << "    return \"return_value\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_diagnostics_field_name() {\n";
    stream << "    return \"diagnostics\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_request_payload_shape_name() {\n";
    stream << "    return \"bridge_request_v1\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_response_payload_shape_name() {\n";
    stream << "    return \"bridge_response_v1\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_response_media_type_field_name() {\n";
    stream << "    return \"response_media_type\";\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgePayloadPlan copperfin_build_runtime_bridge_payload_plan(\n";
    stream << "    CopperfinRuntimeBridgeDispatchPlan dispatch_plan) {\n";
    stream << "    return CopperfinRuntimeBridgePayloadPlan{\n";
    stream << "        std::move(dispatch_plan),\n";
    stream << "        copperfin_build_runtime_bridge_request_payload_shape_name(),\n";
    stream << "        copperfin_build_runtime_bridge_response_payload_shape_name(),\n";
    stream << "        {copperfin_build_runtime_bridge_export_name_field_name(),\n";
    stream << "         copperfin_build_runtime_bridge_routine_kind_field_name(),\n";
    stream << "         copperfin_build_runtime_bridge_source_path_field_name(),\n";
    stream << "         copperfin_build_runtime_bridge_source_line_field_name(),\n";
    stream << "         copperfin_build_runtime_bridge_parameter_declaration_field_name(),\n";
    stream << "         copperfin_build_runtime_bridge_parameter_names_field_name(),\n";
    stream << "         copperfin_build_runtime_bridge_parameter_count_field_name(),\n";
    stream << "         copperfin_build_runtime_bridge_schema_version_field_name(),\n";
    stream << "         copperfin_build_runtime_bridge_parameters_field_name(),\n";
    stream << "         copperfin_build_runtime_bridge_request_media_type_field_name()},\n";
    stream << "        {copperfin_build_runtime_bridge_status_field_name(),\n";
    stream << "         copperfin_build_runtime_bridge_return_value_field_name(),\n";
    stream << "         copperfin_build_runtime_bridge_response_media_type_field_name(),\n";
    stream << "         copperfin_build_runtime_bridge_schema_version_field_name(),\n";
    stream << "         copperfin_build_runtime_bridge_diagnostics_field_name()}};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeInterpretationPlan copperfin_build_runtime_bridge_interpretation_plan(\n";
    stream << "    CopperfinRuntimeBridgePayloadPlan payload_plan,\n";
    stream << "    std::string wrapper_return_surface) {\n";
    stream << "    return CopperfinRuntimeBridgeInterpretationPlan{\n";
    stream << "        std::move(payload_plan),\n";
    stream << "        copperfin_build_runtime_bridge_status_field_name(),\n";
    stream << "        copperfin_build_runtime_bridge_return_value_field_name(),\n";
    stream << "        copperfin_build_runtime_bridge_diagnostics_field_name(),\n";
    stream << "        std::move(wrapper_return_surface)};\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_failure_diagnostics_value() {\n";
    stream << "    return \"runtime_host_failure\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_success_status_value() {\n";
    stream << "    return \"ok\";\n";
    stream << "}\n\n";
    stream << "static bool copperfin_runtime_bridge_fail_on_nonzero_exit_policy() {\n";
    stream << "    return true;\n";
    stream << "}\n\n";
    stream << "static bool copperfin_runtime_bridge_fail_on_missing_response_policy() {\n";
    stream << "    return true;\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeFailurePolicyPlan copperfin_build_runtime_bridge_failure_policy_plan(\n";
    stream << "    CopperfinRuntimeBridgeInterpretationPlan interpretation_plan,\n";
    stream << "    std::string fallback_return_value) {\n";
    stream << "    return CopperfinRuntimeBridgeFailurePolicyPlan{\n";
    stream << "        std::move(interpretation_plan),\n";
    stream << "        copperfin_runtime_bridge_fail_on_nonzero_exit_policy(),\n";
    stream << "        copperfin_runtime_bridge_fail_on_missing_response_policy(),\n";
    stream << "        copperfin_build_runtime_bridge_failure_diagnostics_value(),\n";
    stream << "        std::move(fallback_return_value)};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeResponseValidationPlan copperfin_build_runtime_bridge_response_validation_plan(\n";
    stream << "    CopperfinRuntimeBridgeFailurePolicyPlan failure_policy_plan) {\n";
    stream << "    const auto expected_response_media_type =\n";
    stream << "        failure_policy_plan.interpretation_plan.payload_plan.dispatch_plan.serialization_plan.response_media_type;\n";
    stream << "    const auto expected_schema_version =\n";
    stream << "        failure_policy_plan.interpretation_plan.payload_plan.dispatch_plan.serialization_plan.schema_version;\n";
    stream << "    const auto required_response_fields =\n";
    stream << "        failure_policy_plan.interpretation_plan.payload_plan.response_fields;\n";
    stream << "    return CopperfinRuntimeBridgeResponseValidationPlan{\n";
    stream << "        std::move(failure_policy_plan),\n";
    stream << "        expected_response_media_type,\n";
    stream << "        expected_schema_version,\n";
    stream << "        required_response_fields,\n";
    stream << "        copperfin_build_runtime_bridge_success_status_value()};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeRequestArtifact copperfin_build_runtime_bridge_request_artifact(\n";
    stream << "    CopperfinRuntimeBridgeResponseValidationPlan response_validation_plan) {\n";
    stream << "    const auto request_document = copperfin_build_runtime_bridge_request_document(\n";
    stream << "        response_validation_plan.failure_policy_plan.interpretation_plan.payload_plan.dispatch_plan.serialization_plan.transport_plan.execution_plan.observation_plan.launch_plan.result.call,\n";
    stream << "        response_validation_plan.failure_policy_plan.interpretation_plan.payload_plan,\n";
    stream << "        response_validation_plan.failure_policy_plan.interpretation_plan.payload_plan.dispatch_plan.serialization_plan.request_media_type);\n";
    stream << "    return CopperfinRuntimeBridgeRequestArtifact{\n";
    stream << "        std::move(response_validation_plan),\n";
    stream << "        std::move(request_document)};\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_request_write_mode() {\n";
    stream << "    return \"overwrite\";\n";
    stream << "}\n\n";
    stream << "static bool copperfin_runtime_bridge_ensure_parent_directory_policy() {\n";
    stream << "    return true;\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeRequestWritePlan copperfin_build_runtime_bridge_request_write_plan(\n";
    stream << "    CopperfinRuntimeBridgeRequestArtifact request_artifact) {\n";
    stream << "    const auto target_path =\n";
    stream << "        request_artifact.response_validation_plan.failure_policy_plan.interpretation_plan.payload_plan.dispatch_plan.serialization_plan.transport_plan.request_path;\n";
    stream << "    const auto write_mode = copperfin_build_runtime_bridge_request_write_mode();\n";
    stream << "    return CopperfinRuntimeBridgeRequestWritePlan{\n";
    stream << "        std::move(request_artifact),\n";
    stream << "        target_path,\n";
    stream << "        write_mode,\n";
    stream << "        copperfin_runtime_bridge_ensure_parent_directory_policy()};\n";
    stream << "}\n\n";
    stream << "static bool copperfin_runtime_bridge_execute_write_request(\n";
    stream << "    const CopperfinRuntimeBridgeRequestWritePlan& plan) {\n";
    stream << "    if (plan.ensure_parent_directory) {\n";
    stream << "        std::error_code parent_directory_error;\n";
    stream << "        std::filesystem::create_directories(plan.target_path.parent_path(), parent_directory_error);\n";
    stream << "        if (parent_directory_error) {\n";
    stream << "            return false;\n";
    stream << "        }\n";
    stream << "    }\n";
    stream << "    const auto remove_artifact = [](const std::filesystem::path& path) {\n";
    stream << "        if (path.empty()) {\n";
    stream << "            return true;\n";
    stream << "        }\n";
    stream << "        std::error_code error;\n";
    stream << "        std::filesystem::remove(path, error);\n";
    stream << "        return !error;\n";
    stream << "    };\n";
    stream << "    const auto& transport_plan =\n";
    stream << "        plan.request_artifact.response_validation_plan.failure_policy_plan.interpretation_plan.payload_plan.dispatch_plan.serialization_plan.transport_plan;\n";
    stream << "    const auto& observation_plan =\n";
    stream << "        transport_plan.execution_plan.observation_plan;\n";
    stream << "    if (!remove_artifact(plan.target_path) ||\n";
    stream << "        !remove_artifact(transport_plan.response_path) ||\n";
    stream << "        !remove_artifact(observation_plan.stdout_log_path) ||\n";
    stream << "        !remove_artifact(observation_plan.stderr_log_path)) {\n";
    stream << "        return false;\n";
    stream << "    }\n";
    stream << "    std::ofstream out(plan.target_path);\n";
    stream << "    if (!out) {\n";
    stream << "        return false;\n";
    stream << "    }\n";
    stream << "    out << plan.request_artifact.request_document;\n";
    stream << "    return out.good();\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeProcessLaunch copperfin_runtime_bridge_failed_process_launch(\n";
    stream << "    const CopperfinRuntimeBridgeDispatchExecution& dispatch_execution) {\n";
    stream << "    return CopperfinRuntimeBridgeProcessLaunch{\n";
    stream << "        dispatch_execution.executable_path,\n";
    stream << "        dispatch_execution.arguments,\n";
    stream << "        dispatch_execution.working_directory,\n";
    stream << "        dispatch_execution.environment,\n";
    stream << "        dispatch_execution.stdout_log_path,\n";
    stream << "        dispatch_execution.stderr_log_path,\n";
    stream << "        dispatch_execution.capture_stdout,\n";
    stream << "        dispatch_execution.capture_stderr,\n";
    stream << "        false,\n";
    stream << "        false,\n";
    stream << "        -1,\n";
    stream << "        dispatch_execution.expected_exit_code};\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_response_read_mode() {\n";
    stream << "    return \"read_text\";\n";
    stream << "}\n\n";
    stream << "static bool copperfin_runtime_bridge_require_existing_response_policy() {\n";
    stream << "    return true;\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeResponseReadPlan copperfin_build_runtime_bridge_response_read_plan(\n";
    stream << "    CopperfinRuntimeBridgeRequestWritePlan request_write_plan,\n";
    stream << "    bool request_write_succeeded) {\n";
    stream << "    const auto source_path =\n";
    stream << "        request_write_plan.request_artifact.response_validation_plan.failure_policy_plan.interpretation_plan.payload_plan.dispatch_plan.serialization_plan.transport_plan.response_path;\n";
    stream << "    const auto read_mode = copperfin_build_runtime_bridge_response_read_mode();\n";
    stream << "    return CopperfinRuntimeBridgeResponseReadPlan{\n";
    stream << "        std::move(request_write_plan),\n";
    stream << "        request_write_succeeded,\n";
    stream << "        source_path,\n";
    stream << "        read_mode,\n";
    stream << "        copperfin_runtime_bridge_require_existing_response_policy()};\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_empty_response_document() {\n";
    stream << "    return \"\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_runtime_bridge_execute_read_response(\n";
    stream << "    const CopperfinRuntimeBridgeResponseReadPlan& plan) {\n";
    stream << "    if (!plan.request_write_succeeded) {\n";
    stream << "        return copperfin_build_runtime_bridge_empty_response_document();\n";
    stream << "    }\n";
    stream << "    std::error_code response_exists_error;\n";
    stream << "    if (plan.require_existing_response &&\n";
    stream << "        (!std::filesystem::exists(plan.source_path, response_exists_error) || response_exists_error)) {\n";
    stream << "        return copperfin_build_runtime_bridge_empty_response_document();\n";
    stream << "    }\n";
    stream << "    std::ifstream input(plan.source_path, std::ios::binary);\n";
    stream << "    if (!input) {\n";
    stream << "        return copperfin_build_runtime_bridge_empty_response_document();\n";
    stream << "    }\n";
    stream << "    std::ostringstream response_document;\n";
    stream << "    response_document << input.rdbuf();\n";
    stream << "    return response_document.str();\n";
    stream << "}\n\n";
    stream << "static void copperfin_runtime_bridge_cleanup_artifacts(\n";
    stream << "    const CopperfinRuntimeBridgeResponseReadPlan& plan) {\n";
    stream << "    const auto remove_artifact = [](const std::filesystem::path& path) {\n";
    stream << "        if (path.empty()) {\n";
    stream << "            return;\n";
    stream << "        }\n";
    stream << "        std::error_code ignored;\n";
    stream << "        std::filesystem::remove(path, ignored);\n";
    stream << "    };\n";
    stream << "    const auto& transport_plan =\n";
    stream << "        plan.request_write_plan.request_artifact.response_validation_plan.failure_policy_plan.interpretation_plan.payload_plan.dispatch_plan.serialization_plan.transport_plan;\n";
    stream << "    const auto& observation_plan =\n";
    stream << "        transport_plan.execution_plan.observation_plan;\n";
    stream << "    remove_artifact(transport_plan.request_path);\n";
    stream << "    remove_artifact(transport_plan.response_path);\n";
    stream << "    remove_artifact(observation_plan.stdout_log_path);\n";
    stream << "    remove_artifact(observation_plan.stderr_log_path);\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeResponseArtifact copperfin_build_runtime_bridge_response_artifact(\n";
    stream << "    CopperfinRuntimeBridgeResponseReadPlan response_read_plan,\n";
    stream << "    std::string response_document) {\n";
    stream << "    return CopperfinRuntimeBridgeResponseArtifact{\n";
    stream << "        std::move(response_read_plan),\n";
    stream << "        std::move(response_document)};\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_response_parse_kind() {\n";
    stream << "    return \"json_field_map\";\n";
    stream << "}\n\n";
    stream << "static bool copperfin_runtime_bridge_parse_json_string_at(\n";
    stream << "    const std::string& document,\n";
    stream << "    std::size_t value_start,\n";
    stream << "    std::size_t& value_end,\n";
    stream << "    std::string& decoded_value) {\n";
    stream << "    if (value_start >= document.size() || document[value_start] != '\"') {\n";
    stream << "        return false;\n";
    stream << "    }\n";
    stream << "    decoded_value.clear();\n";
    stream << "    for (std::size_t index = value_start + 1; index < document.size(); ++index) {\n";
    stream << "        const char ch = document[index];\n";
    stream << "        if (ch == '\\\\' && index + 1 < document.size()) {\n";
    stream << "            const char escaped = document[++index];\n";
    stream << "            switch (escaped) {\n";
    stream << "            case 'n': decoded_value.push_back('\\n'); break;\n";
    stream << "            case 'r': decoded_value.push_back('\\r'); break;\n";
    stream << "            case 't': decoded_value.push_back('\\t'); break;\n";
    stream << "            default: decoded_value.push_back(escaped); break;\n";
    stream << "            }\n";
    stream << "            continue;\n";
    stream << "        }\n";
    stream << "        if (ch == '\"') {\n";
    stream << "            value_end = index + 1;\n";
    stream << "            return true;\n";
    stream << "        }\n";
    stream << "        decoded_value.push_back(ch);\n";
    stream << "    }\n";
    stream << "    return false;\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_runtime_bridge_extract_json_field(\n";
    stream << "    const std::string& response_document,\n";
    stream << "    const std::string& field_name) {\n";
    stream << "    std::size_t value_start = std::string::npos;\n";
    stream << "    if (!copperfin_runtime_bridge_find_json_field_value_start(response_document, field_name, value_start)) {\n";
    stream << "        return \"\";\n";
    stream << "    }\n";
    stream << "    if (response_document[value_start] == '\"') {\n";
    stream << "        std::size_t string_end = value_start;\n";
    stream << "        std::string decoded_value;\n";
    stream << "        return copperfin_runtime_bridge_parse_json_string_at(response_document, value_start, string_end, decoded_value)\n";
    stream << "            ? decoded_value\n";
    stream << "            : std::string{};\n";
    stream << "    }\n";
    stream << "    const auto value_end = response_document.find_first_of(\",}\", value_start);\n";
    stream << "    return response_document.substr(\n";
    stream << "        value_start,\n";
    stream << "        value_end == std::string::npos ? std::string::npos : value_end - value_start);\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeParsedResponse copperfin_runtime_bridge_execute_parse_response(\n";
    stream << "    const CopperfinRuntimeBridgeResponseParsePlan& plan) {\n";
    stream << "    const auto& response_document = plan.response_artifact.response_document;\n";
    stream << "    return CopperfinRuntimeBridgeParsedResponse{\n";
    stream << "        copperfin_runtime_bridge_extract_json_field(response_document, plan.status_field),\n";
    stream << "        copperfin_runtime_bridge_extract_json_field(response_document, plan.value_field),\n";
    stream << "        copperfin_runtime_bridge_extract_json_field(response_document, plan.diagnostics_field)};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeResponseParsePlan copperfin_build_runtime_bridge_response_parse_plan(\n";
    stream << "    CopperfinRuntimeBridgeResponseArtifact response_artifact) {\n";
    stream << "    const auto& interpretation_plan =\n";
    stream << "        response_artifact.response_read_plan.request_write_plan.request_artifact.response_validation_plan.failure_policy_plan.interpretation_plan;\n";
    stream << "    const auto parser_kind = copperfin_build_runtime_bridge_response_parse_kind();\n";
    stream << "    return CopperfinRuntimeBridgeResponseParsePlan{\n";
    stream << "        std::move(response_artifact),\n";
    stream << "        parser_kind,\n";
    stream << "        interpretation_plan.status_field,\n";
    stream << "        interpretation_plan.value_field,\n";
    stream << "        interpretation_plan.diagnostics_field};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeResponseParseAdmission copperfin_runtime_bridge_admit_response_parse(\n";
    stream << "    const CopperfinRuntimeBridgeResponseValidationEvaluation& response_validation_evaluation,\n";
    stream << "    const CopperfinRuntimeBridgeResponseParsePlan& response_parse_plan) {\n";
    stream << "    const auto& failure_policy_plan =\n";
    stream << "        response_parse_plan.response_artifact.response_read_plan.request_write_plan.request_artifact.response_validation_plan.failure_policy_plan;\n";
    stream << "    const bool should_parse_response = !response_validation_evaluation.should_use_fallback_return;\n";
    stream << "    const bool should_use_fallback_return = !should_parse_response;\n";
    stream << "    return CopperfinRuntimeBridgeResponseParseAdmission{\n";
    stream << "        should_parse_response,\n";
    stream << "        should_use_fallback_return,\n";
    stream << "        should_use_fallback_return ? failure_policy_plan.diagnostics_fallback : response_validation_evaluation.diagnostics_value,\n";
    stream << "        failure_policy_plan.fallback_return_value};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeInterpretedResultPlan copperfin_build_runtime_bridge_interpreted_result_plan(\n";
    stream << "    CopperfinRuntimeBridgeResponseParsePlan response_parse_plan,\n";
    stream << "    CopperfinRuntimeBridgeParsedResponse parsed_response) {\n";
    stream << "    const auto& response_validation_plan =\n";
    stream << "        response_parse_plan.response_artifact.response_read_plan.request_write_plan.request_artifact.response_validation_plan;\n";
    stream << "    const auto& failure_policy_plan = response_validation_plan.failure_policy_plan;\n";
    stream << "    return CopperfinRuntimeBridgeInterpretedResultPlan{\n";
    stream << "        std::move(response_parse_plan),\n";
    stream << "        std::move(parsed_response),\n";
    stream << "        response_validation_plan.success_status_value,\n";
    stream << "        failure_policy_plan.interpretation_plan.wrapper_return_surface,\n";
    stream << "        failure_policy_plan.fallback_return_value};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeInterpretedResultAdmission copperfin_runtime_bridge_admit_interpreted_result(\n";
    stream << "    const CopperfinRuntimeBridgeResponseParseAdmission& response_parse_admission,\n";
    stream << "    const CopperfinRuntimeBridgeInterpretedResultPlan& interpreted_result_plan) {\n";
    stream << "    const auto& failure_policy_plan = interpreted_result_plan.response_parse_plan.response_artifact.response_read_plan.request_write_plan.request_artifact.response_validation_plan.failure_policy_plan;\n";
    stream << "    const bool should_interpret_result = !response_parse_admission.should_use_fallback_return;\n";
    stream << "    const bool should_use_fallback_return = !should_interpret_result;\n";
    stream << "    return CopperfinRuntimeBridgeInterpretedResultAdmission{\n";
    stream << "        should_interpret_result,\n";
    stream << "        should_use_fallback_return,\n";
    stream << "        should_use_fallback_return ? failure_policy_plan.diagnostics_fallback : response_parse_admission.diagnostics_value,\n";
    stream << "        failure_policy_plan.fallback_return_value};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeInterpretedResult copperfin_runtime_bridge_execute_interpreted_result(\n";
    stream << "    const CopperfinRuntimeBridgeInterpretedResultPlan& plan) {\n";
    stream << "    const auto& parsed_response = plan.parsed_response;\n";
    stream << "    const bool matched_success_status = parsed_response.status_value == plan.success_status_value;\n";
    stream << "    const auto selected_return_value_representation = matched_success_status\n";
    stream << "        ? parsed_response.return_value_representation\n";
    stream << "        : plan.fallback_return_value;\n";
    stream << "    return CopperfinRuntimeBridgeInterpretedResult{\n";
    stream << "        matched_success_status,\n";
    stream << "        std::move(selected_return_value_representation),\n";
    stream << "        parsed_response.diagnostics_value,\n";
    stream << "        plan.wrapper_return_surface};\n";
    stream << "}\n\n";
    stream << "static int copperfin_runtime_bridge_default_int_value() {\n";
    stream << "    return -1;\n";
    stream << "}\n\n";
    stream << "static int copperfin_parse_runtime_bridge_int_value_representation(\n";
    stream << "    const std::string& value_representation) {\n";
    stream << "    std::istringstream value_stream(value_representation);\n";
    stream << "    int parsed_value = copperfin_runtime_bridge_default_int_value();\n";
    stream << "    value_stream >> parsed_value;\n";
    stream << "    return parsed_value;\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeNativeReturnPlan copperfin_build_runtime_bridge_native_return_plan(\n";
    stream << "    const CopperfinRuntimeBridgeResult& result,\n";
    stream << "    CopperfinRuntimeBridgeInterpretedResultPlan interpreted_result_plan,\n";
    stream << "    CopperfinRuntimeBridgeInterpretedResult interpreted_result) {\n";
    stream << "    const auto success_value_representation = interpreted_result.selected_return_value_representation;\n";
    stream << "    const int success_int_value = copperfin_parse_runtime_bridge_int_value_representation(\n";
    stream << "        success_value_representation);\n";
    stream << "    const auto fallback_value_representation = interpreted_result_plan.fallback_return_value;\n";
    stream << "    const int fallback_int_value = copperfin_parse_runtime_bridge_int_value_representation(\n";
    stream << "        fallback_value_representation);\n";
    stream << "    return CopperfinRuntimeBridgeNativeReturnPlan{\n";
    stream << "        std::move(interpreted_result_plan),\n";
    stream << "        std::move(interpreted_result),\n";
    stream << "        success_value_representation,\n";
    stream << "        success_int_value,\n";
    stream << "        fallback_value_representation,\n";
    stream << "        fallback_int_value,\n";
    stream << "        result.return_binding.return_surface};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeNativeReturnAdmission copperfin_runtime_bridge_admit_native_return(\n";
    stream << "    const CopperfinRuntimeBridgeInterpretedResultAdmission& interpreted_result_admission,\n";
    stream << "    const CopperfinRuntimeBridgeNativeReturnPlan& native_return_plan) {\n";
    stream << "    const auto& failure_policy_plan = native_return_plan.interpreted_result_plan.response_parse_plan.response_artifact.response_read_plan.request_write_plan.request_artifact.response_validation_plan.failure_policy_plan;\n";
    stream << "    const bool should_materialize_native_return = !interpreted_result_admission.should_use_fallback_return;\n";
    stream << "    const bool should_use_fallback_return = !should_materialize_native_return;\n";
    stream << "    return CopperfinRuntimeBridgeNativeReturnAdmission{\n";
    stream << "        should_materialize_native_return,\n";
    stream << "        should_use_fallback_return,\n";
    stream << "        should_use_fallback_return ? failure_policy_plan.diagnostics_fallback : interpreted_result_admission.diagnostics_value,\n";
    stream << "        failure_policy_plan.fallback_return_value};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeNativeReturn copperfin_runtime_bridge_execute_native_return(\n";
    stream << "    const CopperfinRuntimeBridgeNativeReturnPlan& plan) {\n";
    stream << "    const auto& interpreted_result = plan.interpreted_result;\n";
    stream << "    const auto selected_value_representation = interpreted_result.matched_success_status\n";
    stream << "        ? plan.success_value_representation\n";
    stream << "        : plan.fallback_value_representation;\n";
    stream << "    const int selected_int_value = interpreted_result.matched_success_status\n";
    stream << "        ? plan.success_int_value\n";
    stream << "        : plan.fallback_int_value;\n";
    stream << "    return CopperfinRuntimeBridgeNativeReturn{\n";
    stream << "        interpreted_result.matched_success_status,\n";
    stream << "        std::move(selected_value_representation),\n";
    stream << "        selected_int_value,\n";
    stream << "        interpreted_result.diagnostics_value,\n";
    stream << "        interpreted_result.wrapper_return_surface};\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_success_comparator_token() {\n";
    stream << "    return \" == \";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_fallback_comparator_token() {\n";
    stream << "    return \" != \";\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeOutcomeSelectionPlan copperfin_build_runtime_bridge_outcome_selection_plan(\n";
    stream << "    CopperfinRuntimeBridgeNativeReturnPlan native_return_plan,\n";
    stream << "    CopperfinRuntimeBridgeNativeReturn native_return) {\n";
    stream << "    const auto& interpreted_result_plan = native_return_plan.interpreted_result_plan;\n";
    stream << "    const auto& response_parse_plan = interpreted_result_plan.response_parse_plan;\n";
    stream << "    const auto success_comparator = copperfin_build_runtime_bridge_success_comparator_token();\n";
    stream << "    const auto fallback_comparator = copperfin_build_runtime_bridge_fallback_comparator_token();\n";
    stream << "    const auto success_condition =\n";
    stream << "        response_parse_plan.status_field + success_comparator + interpreted_result_plan.success_status_value;\n";
    stream << "    const auto fallback_condition =\n";
    stream << "        response_parse_plan.status_field + fallback_comparator + interpreted_result_plan.success_status_value;\n";
    stream << "    return CopperfinRuntimeBridgeOutcomeSelectionPlan{\n";
    stream << "        std::move(native_return_plan),\n";
    stream << "        std::move(native_return),\n";
    stream << "        std::move(success_condition),\n";
    stream << "        std::move(fallback_condition),\n";
    stream << "        response_parse_plan.diagnostics_field};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeOutcomeSelectionAdmission copperfin_runtime_bridge_admit_outcome_selection(\n";
    stream << "    const CopperfinRuntimeBridgeNativeReturnAdmission& native_return_admission,\n";
    stream << "    const CopperfinRuntimeBridgeOutcomeSelectionPlan& outcome_selection_plan) {\n";
    stream << "    const auto& failure_policy_plan = outcome_selection_plan.native_return_plan.interpreted_result_plan.response_parse_plan.response_artifact.response_read_plan.request_write_plan.request_artifact.response_validation_plan.failure_policy_plan;\n";
    stream << "    const bool should_select_outcome = !native_return_admission.should_use_fallback_return;\n";
    stream << "    const bool should_use_fallback_return = !should_select_outcome;\n";
    stream << "    return CopperfinRuntimeBridgeOutcomeSelectionAdmission{\n";
    stream << "        should_select_outcome,\n";
    stream << "        should_use_fallback_return,\n";
    stream << "        should_use_fallback_return ? failure_policy_plan.diagnostics_fallback : native_return_admission.diagnostics_value,\n";
    stream << "        failure_policy_plan.fallback_return_value};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeOutcomeSelection copperfin_runtime_bridge_execute_outcome_selection(\n";
    stream << "    const CopperfinRuntimeBridgeOutcomeSelectionPlan& plan) {\n";
    stream << "    const auto& native_return = plan.native_return;\n";
    stream << "    const auto selected_condition = native_return.matched_success_status\n";
    stream << "        ? plan.success_condition\n";
    stream << "        : plan.fallback_condition;\n";
    stream << "    return CopperfinRuntimeBridgeOutcomeSelection{\n";
    stream << "        native_return.matched_success_status,\n";
    stream << "        std::move(selected_condition),\n";
    stream << "        native_return.diagnostics_value,\n";
    stream << "        native_return.selected_value_representation,\n";
    stream << "        native_return.selected_int_value,\n";
    stream << "        native_return.native_return_surface};\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_native_int_return_surface() {\n";
    stream << "    return \"int\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_native_int_placeholder_signature_token() {\n";
    stream << "    return \"(int)\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_return_statement_from_expression(\n";
    stream << "    const std::string& value_expression) {\n";
    stream << "    return \"return \" + value_expression + \";\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_typed_native_return_expression(\n";
    stream << "    const std::string& native_return_surface,\n";
    stream << "    const std::string& int_value_representation) {\n";
    stream << "    const auto prefix = native_return_surface.substr(\n";
    stream << "        0U, native_return_surface.find(copperfin_build_runtime_bridge_native_int_placeholder_signature_token()));\n";
    stream << "    return prefix + \"(\" + int_value_representation + \")\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_return_statement(\n";
    stream << "    const std::string& native_return_surface,\n";
    stream << "    int int_value,\n";
    stream << "    const std::string& value_representation) {\n";
    stream << "    const auto int_value_representation = std::to_string(int_value);\n";
    stream << "    if (native_return_surface == copperfin_build_runtime_bridge_native_int_return_surface()) {\n";
    stream << "        return copperfin_build_runtime_bridge_return_statement_from_expression(int_value_representation);\n";
    stream << "    }\n";
    stream << "    const auto placeholder_index = native_return_surface.find(copperfin_build_runtime_bridge_native_int_placeholder_signature_token());\n";
    stream << "    if (placeholder_index != std::string::npos) {\n";
    stream << "        return copperfin_build_runtime_bridge_return_statement_from_expression(\n";
    stream << "            copperfin_build_runtime_bridge_typed_native_return_expression(native_return_surface, int_value_representation));\n";
    stream << "    }\n";
    stream << "    return copperfin_build_runtime_bridge_return_statement_from_expression(value_representation);\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_placeholder_return_statement(\n";
    stream << "    const CopperfinRuntimeBridgeReturn& return_binding) {\n";
    stream << "    return copperfin_build_runtime_bridge_return_statement(\n";
    stream << "        return_binding.return_surface,\n";
    stream << "        copperfin_parse_runtime_bridge_int_value_representation(return_binding.value_representation),\n";
    stream << "        return_binding.value_representation);\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeReturnMaterializationPlan copperfin_build_runtime_bridge_return_materialization_plan(\n";
    stream << "    CopperfinRuntimeBridgeOutcomeSelectionPlan outcome_selection_plan,\n";
    stream << "    CopperfinRuntimeBridgeOutcomeSelection outcome_selection) {\n";
    stream << "    const auto& native_return_plan = outcome_selection_plan.native_return_plan;\n";
    stream << "    const auto success_return_statement = copperfin_build_runtime_bridge_return_statement(\n";
    stream << "        native_return_plan.native_return_surface,\n";
    stream << "        native_return_plan.success_int_value,\n";
    stream << "        native_return_plan.success_value_representation);\n";
    stream << "    const auto fallback_return_statement = copperfin_build_runtime_bridge_return_statement(\n";
    stream << "        native_return_plan.native_return_surface,\n";
    stream << "        native_return_plan.fallback_int_value,\n";
    stream << "        native_return_plan.fallback_value_representation);\n";
    stream << "    return CopperfinRuntimeBridgeReturnMaterializationPlan{\n";
    stream << "        std::move(outcome_selection_plan),\n";
    stream << "        std::move(outcome_selection),\n";
    stream << "        std::move(success_return_statement),\n";
    stream << "        std::move(fallback_return_statement),\n";
    stream << "        native_return_plan.native_return_surface};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeReturnMaterializationAdmission copperfin_runtime_bridge_admit_return_materialization(\n";
    stream << "    const CopperfinRuntimeBridgeOutcomeSelectionAdmission& outcome_selection_admission,\n";
    stream << "    const CopperfinRuntimeBridgeReturnMaterializationPlan& return_materialization_plan) {\n";
    stream << "    const auto& failure_policy_plan = return_materialization_plan.outcome_selection_plan.native_return_plan.interpreted_result_plan.response_parse_plan.response_artifact.response_read_plan.request_write_plan.request_artifact.response_validation_plan.failure_policy_plan;\n";
    stream << "    const bool should_materialize_return = !outcome_selection_admission.should_use_fallback_return;\n";
    stream << "    const bool should_use_fallback_return = !should_materialize_return;\n";
    stream << "    return CopperfinRuntimeBridgeReturnMaterializationAdmission{\n";
    stream << "        should_materialize_return,\n";
    stream << "        should_use_fallback_return,\n";
    stream << "        should_use_fallback_return ? failure_policy_plan.diagnostics_fallback : outcome_selection_admission.diagnostics_value,\n";
    stream << "        failure_policy_plan.fallback_return_value};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeReturnMaterialization copperfin_runtime_bridge_execute_return_materialization(\n";
    stream << "    const CopperfinRuntimeBridgeReturnMaterializationPlan& plan) {\n";
    stream << "    const auto& outcome_selection = plan.outcome_selection;\n";
    stream << "    return CopperfinRuntimeBridgeReturnMaterialization{\n";
    stream << "        outcome_selection.matched_success_status,\n";
    stream << "        plan.outcome_selection_plan.success_condition,\n";
    stream << "        outcome_selection.selected_condition,\n";
    stream << "        outcome_selection.diagnostics_value,\n";
    stream << "        plan.success_return_statement,\n";
    stream << "        plan.fallback_return_statement,\n";
    stream << "        outcome_selection.native_return_surface};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeReturnEmissionPlan copperfin_build_runtime_bridge_return_emission_plan(\n";
    stream << "    CopperfinRuntimeBridgeReturnMaterializationPlan return_materialization_plan,\n";
    stream << "    CopperfinRuntimeBridgeReturnMaterialization return_materialization) {\n";
    stream << "    const auto success_branch_statement =\n";
    stream << "        \"if (\" + return_materialization.success_condition + \") { \"\n";
    stream << "        + return_materialization.success_return_statement + \" }\";\n";
    stream << "    const auto fallback_branch_statement =\n";
    stream << "        \"else { \" + return_materialization.fallback_return_statement + \" }\";\n";
    stream << "    const auto emitted_return_block =\n";
    stream << "        success_branch_statement + \" \" + fallback_branch_statement;\n";
    stream << "    return CopperfinRuntimeBridgeReturnEmissionPlan{\n";
    stream << "        std::move(return_materialization_plan),\n";
    stream << "        std::move(return_materialization),\n";
    stream << "        std::move(success_branch_statement),\n";
    stream << "        std::move(fallback_branch_statement),\n";
    stream << "        std::move(emitted_return_block)};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeReturnEmissionAdmission copperfin_runtime_bridge_admit_return_emission(\n";
    stream << "    const CopperfinRuntimeBridgeReturnMaterializationAdmission& return_materialization_admission,\n";
    stream << "    const CopperfinRuntimeBridgeReturnEmissionPlan& return_emission_plan) {\n";
    stream << "    const bool should_emit_return = !return_materialization_admission.should_use_fallback_return;\n";
    stream << "    const bool should_use_fallback_return = !should_emit_return;\n";
    stream << "    return CopperfinRuntimeBridgeReturnEmissionAdmission{\n";
    stream << "        should_emit_return,\n";
    stream << "        should_use_fallback_return,\n";
    stream << "        return_materialization_admission.diagnostics_value,\n";
    stream << "        return_emission_plan.emitted_return_block};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeReturnEmission copperfin_runtime_bridge_execute_return_emission(\n";
    stream << "    const CopperfinRuntimeBridgeReturnEmissionPlan& plan) {\n";
    stream << "    const auto& return_materialization = plan.return_materialization;\n";
    stream << "    return CopperfinRuntimeBridgeReturnEmission{\n";
    stream << "        return_materialization.matched_success_status,\n";
    stream << "        return_materialization.selected_condition,\n";
    stream << "        return_materialization.diagnostics_value,\n";
    stream << "        plan.success_branch_statement,\n";
    stream << "        plan.fallback_branch_statement,\n";
    stream << "        plan.emitted_return_block,\n";
    stream << "        return_materialization.native_return_surface};\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_replace_placeholder_return_mode() {\n";
    stream << "    return \"replace_placeholder_return\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_planned_activation_pending_mode() {\n";
    stream << "    return \"planned_activation_pending\";\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeFinalReturnAdoptionPlan copperfin_build_runtime_bridge_final_return_adoption_plan(\n";
    stream << "    CopperfinRuntimeBridgeReturnEmissionPlan return_emission_plan,\n";
    stream << "    CopperfinRuntimeBridgeReturnEmission return_emission,\n";
    stream << "    std::string placeholder_return_statement) {\n";
    stream << "    const auto adopted_return_block = return_emission.emitted_return_block;\n";
    stream << "    return CopperfinRuntimeBridgeFinalReturnAdoptionPlan{\n";
    stream << "        std::move(return_emission_plan),\n";
    stream << "        std::move(return_emission),\n";
    stream << "        std::move(placeholder_return_statement),\n";
    stream << "        adopted_return_block,\n";
    stream << "        copperfin_build_runtime_bridge_replace_placeholder_return_mode()};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeFinalReturnAdoptionAdmission copperfin_runtime_bridge_admit_final_return_adoption(\n";
    stream << "    const CopperfinRuntimeBridgeReturnEmissionAdmission& return_emission_admission,\n";
    stream << "    const CopperfinRuntimeBridgeFinalReturnAdoptionPlan& final_return_adoption_plan) {\n";
    stream << "    const bool should_adopt_return = !return_emission_admission.should_use_fallback_return;\n";
    stream << "    const bool should_use_placeholder_return = !should_adopt_return;\n";
    stream << "    return CopperfinRuntimeBridgeFinalReturnAdoptionAdmission{\n";
    stream << "        should_adopt_return,\n";
    stream << "        should_use_placeholder_return,\n";
    stream << "        return_emission_admission.diagnostics_value,\n";
    stream << "        should_use_placeholder_return\n";
    stream << "            ? final_return_adoption_plan.placeholder_return_statement\n";
    stream << "            : final_return_adoption_plan.adopted_return_block};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeFinalReturnAdoption copperfin_runtime_bridge_execute_final_return_adoption(\n";
    stream << "    const CopperfinRuntimeBridgeFinalReturnAdoptionPlan& plan) {\n";
    stream << "    const auto& return_emission = plan.return_emission;\n";
    stream << "    return CopperfinRuntimeBridgeFinalReturnAdoption{\n";
    stream << "        return_emission.matched_success_status,\n";
    stream << "        return_emission.selected_condition,\n";
    stream << "        return_emission.diagnostics_value,\n";
    stream << "        plan.placeholder_return_statement,\n";
    stream << "        plan.adopted_return_block,\n";
    stream << "        plan.adoption_mode,\n";
    stream << "        return_emission.native_return_surface};\n";
    stream << "}\n\n";
    stream << "static bool copperfin_runtime_bridge_activates_adopted_return_policy() {\n";
    stream << "    return false;\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeReturnActivationPlan copperfin_build_runtime_bridge_return_activation_plan(\n";
    stream << "    CopperfinRuntimeBridgeFinalReturnAdoptionPlan final_return_adoption_plan,\n";
    stream << "    CopperfinRuntimeBridgeFinalReturnAdoption final_return_adoption) {\n";
    stream << "    const auto active_return_block = final_return_adoption.adopted_return_block;\n";
    stream << "    return CopperfinRuntimeBridgeReturnActivationPlan{\n";
    stream << "        std::move(final_return_adoption_plan),\n";
    stream << "        std::move(final_return_adoption),\n";
    stream << "        copperfin_runtime_bridge_activates_adopted_return_policy(),\n";
    stream << "        copperfin_build_runtime_bridge_planned_activation_pending_mode(),\n";
    stream << "        active_return_block};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeReturnActivationAdmission copperfin_runtime_bridge_admit_return_activation(\n";
    stream << "    const CopperfinRuntimeBridgeFinalReturnAdoptionAdmission& final_return_adoption_admission,\n";
    stream << "    const CopperfinRuntimeBridgeReturnActivationPlan& return_activation_plan) {\n";
    stream << "    const bool should_activate_return =\n";
    stream << "        return_activation_plan.activates_adopted_return && !final_return_adoption_admission.should_use_placeholder_return;\n";
    stream << "    const bool should_emit_placeholder_return = !should_activate_return;\n";
    stream << "    return CopperfinRuntimeBridgeReturnActivationAdmission{\n";
    stream << "        should_activate_return,\n";
    stream << "        should_emit_placeholder_return,\n";
    stream << "        final_return_adoption_admission.diagnostics_value,\n";
    stream << "        should_emit_placeholder_return\n";
    stream << "            ? return_activation_plan.final_return_adoption_plan.placeholder_return_statement\n";
    stream << "            : return_activation_plan.active_return_block};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeReturnActivation copperfin_runtime_bridge_execute_return_activation(\n";
    stream << "    const CopperfinRuntimeBridgeReturnActivationPlan& plan) {\n";
    stream << "    const auto& final_return_adoption = plan.final_return_adoption;\n";
    stream << "    return CopperfinRuntimeBridgeReturnActivation{\n";
    stream << "        final_return_adoption.matched_success_status,\n";
    stream << "        final_return_adoption.selected_condition,\n";
    stream << "        final_return_adoption.diagnostics_value,\n";
    stream << "        plan.activates_adopted_return,\n";
    stream << "        plan.activation_mode,\n";
    stream << "        plan.active_return_block,\n";
    stream << "        final_return_adoption.native_return_surface};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeStubReturnPlan copperfin_build_runtime_bridge_stub_return_plan(\n";
    stream << "    CopperfinRuntimeBridgeReturnActivationPlan return_activation_plan,\n";
    stream << "    CopperfinRuntimeBridgeReturnActivation return_activation) {\n";
    stream << "    const auto& final_return_adoption_plan = return_activation_plan.final_return_adoption_plan;\n";
    stream << "    const auto& native_return_plan = final_return_adoption_plan.return_emission_plan.return_materialization_plan\n";
    stream << "        .outcome_selection_plan.native_return_plan;\n";
    stream << "    const auto emitted_return_statement = return_activation.activates_adopted_return\n";
    stream << "        ? return_activation.active_return_block\n";
    stream << "        : final_return_adoption_plan.placeholder_return_statement;\n";
    stream << "    const auto deferred_return_block = return_activation.activates_adopted_return\n";
    stream << "        ? final_return_adoption_plan.placeholder_return_statement\n";
    stream << "        : return_activation.active_return_block;\n";
    stream << "    const bool emits_placeholder_return = !return_activation.activates_adopted_return;\n";
    stream << "    const auto activation_mode = return_activation.activation_mode;\n";
    stream << "    const auto adoption_mode = final_return_adoption_plan.adoption_mode;\n";
    stream << "    const bool keeps_placeholder_return_active =\n";
    stream << "        emits_placeholder_return || activation_mode == copperfin_build_runtime_bridge_planned_activation_pending_mode();\n";
    stream << "    const bool adopts_placeholder_replacement =\n";
    stream << "        adoption_mode == copperfin_build_runtime_bridge_replace_placeholder_return_mode();\n";
    stream << "    return CopperfinRuntimeBridgeStubReturnPlan{\n";
    stream << "        std::move(return_activation_plan),\n";
    stream << "        std::move(return_activation),\n";
    stream << "        emitted_return_statement,\n";
    stream << "        deferred_return_block,\n";
    stream << "        emits_placeholder_return,\n";
    stream << "        activation_mode,\n";
    stream << "        adoption_mode,\n";
    stream << "        keeps_placeholder_return_active,\n";
    stream << "        adopts_placeholder_replacement,\n";
    stream << "        native_return_plan.fallback_int_value,\n";
    stream << "        native_return_plan.fallback_value_representation};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeStubReturnAdmission copperfin_runtime_bridge_admit_stub_return(\n";
    stream << "    const CopperfinRuntimeBridgeReturnActivationAdmission& return_activation_admission,\n";
    stream << "    const CopperfinRuntimeBridgeStubReturnPlan& stub_return_plan) {\n";
    stream << "    const bool should_route_stub_return = !return_activation_admission.should_activate_return;\n";
    stream << "    const bool should_emit_placeholder_return = stub_return_plan.emits_placeholder_return;\n";
    stream << "    return CopperfinRuntimeBridgeStubReturnAdmission{\n";
    stream << "        should_route_stub_return,\n";
    stream << "        should_emit_placeholder_return,\n";
    stream << "        return_activation_admission.diagnostics_value,\n";
    stream << "        should_emit_placeholder_return\n";
    stream << "            ? stub_return_plan.emitted_return_statement\n";
    stream << "            : stub_return_plan.deferred_return_block};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeStubReturn copperfin_runtime_bridge_execute_stub_return(\n";
    stream << "    const CopperfinRuntimeBridgeStubReturnPlan& plan) {\n";
    stream << "    const auto& return_activation = plan.return_activation;\n";
    stream << "    const auto& final_return_adoption_plan = plan.return_activation_plan.final_return_adoption_plan;\n";
    stream << "    const auto& native_return_plan = final_return_adoption_plan.return_emission_plan.return_materialization_plan\n";
    stream << "        .outcome_selection_plan.native_return_plan;\n";
    stream << "    const auto emitted_return_statement = return_activation.activates_adopted_return\n";
    stream << "        ? return_activation.active_return_block\n";
    stream << "        : final_return_adoption_plan.placeholder_return_statement;\n";
    stream << "    const auto deferred_return_block = return_activation.activates_adopted_return\n";
    stream << "        ? final_return_adoption_plan.placeholder_return_statement\n";
    stream << "        : return_activation.active_return_block;\n";
    stream << "    const bool emits_placeholder_return = !return_activation.activates_adopted_return;\n";
    stream << "    const auto activation_mode = return_activation.activation_mode;\n";
    stream << "    const auto adoption_mode = final_return_adoption_plan.adoption_mode;\n";
    stream << "    const bool keeps_placeholder_return_active =\n";
    stream << "        emits_placeholder_return || activation_mode == copperfin_build_runtime_bridge_planned_activation_pending_mode();\n";
    stream << "    const bool adopts_placeholder_replacement =\n";
    stream << "        adoption_mode == copperfin_build_runtime_bridge_replace_placeholder_return_mode();\n";
    stream << "    return CopperfinRuntimeBridgeStubReturn{\n";
    stream << "        return_activation.matched_success_status,\n";
    stream << "        return_activation.selected_condition,\n";
    stream << "        return_activation.diagnostics_value,\n";
    stream << "        emitted_return_statement,\n";
    stream << "        deferred_return_block,\n";
    stream << "        emits_placeholder_return,\n";
    stream << "        activation_mode,\n";
    stream << "        adoption_mode,\n";
    stream << "        keeps_placeholder_return_active,\n";
    stream << "        adopts_placeholder_replacement,\n";
    stream << "        native_return_plan.fallback_int_value,\n";
    stream << "        native_return_plan.fallback_value_representation,\n";
    stream << "        return_activation.native_return_surface};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgePlaceholderReturnValuePlan copperfin_build_runtime_bridge_placeholder_return_value_plan(\n";
    stream << "    CopperfinRuntimeBridgeStubReturnPlan stub_return_plan,\n";
    stream << "    CopperfinRuntimeBridgeStubReturn stub_return) {\n";
    stream << "    return CopperfinRuntimeBridgePlaceholderReturnValuePlan{\n";
    stream << "        std::move(stub_return_plan),\n";
    stream << "        std::move(stub_return),\n";
    stream << "        stub_return.emits_placeholder_return,\n";
    stream << "        stub_return.emitted_return_statement,\n";
    stream << "        stub_return.deferred_return_block,\n";
    stream << "        stub_return.activation_mode,\n";
    stream << "        stub_return.adoption_mode,\n";
    stream << "        stub_return.keeps_placeholder_return_active,\n";
    stream << "        stub_return.adopts_placeholder_replacement,\n";
    stream << "        stub_return.placeholder_fallback_int_value,\n";
    stream << "        stub_return.placeholder_fallback_value_representation};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgePlaceholderReturnValueAdmission copperfin_runtime_bridge_admit_placeholder_return_value(\n";
    stream << "    const CopperfinRuntimeBridgeStubReturnAdmission& stub_return_admission,\n";
    stream << "    const CopperfinRuntimeBridgePlaceholderReturnValuePlan& placeholder_return_value_plan) {\n";
    stream << "    const bool should_emit_placeholder_return = placeholder_return_value_plan.emits_placeholder_return;\n";
    stream << "    const bool should_keep_deferred_return = !should_emit_placeholder_return;\n";
    stream << "    return CopperfinRuntimeBridgePlaceholderReturnValueAdmission{\n";
    stream << "        should_emit_placeholder_return,\n";
    stream << "        should_keep_deferred_return,\n";
    stream << "        stub_return_admission.diagnostics_value,\n";
    stream << "        should_emit_placeholder_return\n";
    stream << "            ? placeholder_return_value_plan.emitted_return_statement\n";
    stream << "            : placeholder_return_value_plan.deferred_return_block};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgePlaceholderReturnValue copperfin_runtime_bridge_execute_placeholder_return_value(\n";
    stream << "    const CopperfinRuntimeBridgePlaceholderReturnValuePlan& plan) {\n";
    stream << "    const auto& stub_return = plan.stub_return;\n";
    stream << "    return CopperfinRuntimeBridgePlaceholderReturnValue{\n";
    stream << "        stub_return.matched_success_status,\n";
    stream << "        stub_return.selected_condition,\n";
    stream << "        stub_return.diagnostics_value,\n";
    stream << "        plan.emits_placeholder_return,\n";
    stream << "        plan.emitted_return_statement,\n";
    stream << "        plan.deferred_return_block,\n";
    stream << "        plan.activation_mode,\n";
    stream << "        plan.adoption_mode,\n";
    stream << "        plan.keeps_placeholder_return_active,\n";
    stream << "        plan.adopts_placeholder_replacement,\n";
    stream << "        plan.fallback_int_value,\n";
    stream << "        plan.fallback_value_representation,\n";
    stream << "        stub_return.native_return_surface};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgePlaceholderReturnIntAdmission copperfin_runtime_bridge_admit_placeholder_return_int(\n";
    stream << "    const CopperfinRuntimeBridgePlaceholderReturnValueAdmission& placeholder_return_value_admission,\n";
    stream << "    const CopperfinRuntimeBridgePlaceholderReturnValuePlan& placeholder_return_value_plan) {\n";
    stream << "    return CopperfinRuntimeBridgePlaceholderReturnIntAdmission{\n";
    stream << "        true,\n";
    stream << "        placeholder_return_value_admission.should_emit_placeholder_return,\n";
    stream << "        placeholder_return_value_admission.diagnostics_value,\n";
    stream << "        placeholder_return_value_plan.fallback_int_value};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeStubEmissionAdmission copperfin_runtime_bridge_admit_stub_emission(\n";
    stream << "    const CopperfinRuntimeBridgePlaceholderReturnIntAdmission& placeholder_return_int_admission,\n";
    stream << "    int placeholder_return_int) {\n";
    stream << "    return CopperfinRuntimeBridgeStubEmissionAdmission{\n";
    stream << "        placeholder_return_int_admission.should_emit_placeholder_return,\n";
    stream << "        placeholder_return_int_admission.diagnostics_value,\n";
    stream << "        placeholder_return_int};\n";
    stream << "}\n\n";
    stream << "static int copperfin_runtime_bridge_execute_placeholder_return_int(\n";
    stream << "    const CopperfinRuntimeBridgePlaceholderReturnIntAdmission& placeholder_return_int_admission) {\n";
    stream << "    if (placeholder_return_int_admission.should_return_int) {\n";
    stream << "        return placeholder_return_int_admission.selected_int_value;\n";
    stream << "    }\n";
    stream << "    return placeholder_return_int_admission.selected_int_value;\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeStubEmission copperfin_runtime_bridge_execute_stub_emission(\n";
    stream << "    const CopperfinRuntimeBridgeStubEmissionAdmission& stub_emission_admission) {\n";
    stream << "    return CopperfinRuntimeBridgeStubEmission{\n";
    stream << "        stub_emission_admission.should_emit_stub_return,\n";
    stream << "        stub_emission_admission.diagnostics_value,\n";
    stream << "        stub_emission_admission.selected_int_value};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeStubEmissionReturnSurface copperfin_runtime_bridge_build_stub_emission_return_surface(\n";
    stream << "    const CopperfinRuntimeBridgeStubEmission& stub_emission,\n";
    stream << "    const std::string& native_return_surface) {\n";
    stream << "    return CopperfinRuntimeBridgeStubEmissionReturnSurface{\n";
    stream << "        native_return_surface,\n";
    stream << "        stub_emission.diagnostics_value,\n";
    stream << "        stub_emission.emitted_int_value};\n";
    stream << "}\n\n";
    stream << "static int copperfin_runtime_bridge_apply_stub_emission_output(\n";
    stream << "    const CopperfinRuntimeBridgeStubEmissionReturnSurface& stub_emission_return_surface,\n";
    stream << "    CopperfinRuntimeBridgeIntReturnAdapter return_adapter) {\n";
    stream << "    return return_adapter(stub_emission_return_surface.emitted_int_value);\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeStubEmissionWrapper copperfin_runtime_bridge_build_stub_emission_wrapper(\n";
    stream << "    const std::string& native_return_surface,\n";
    stream << "    CopperfinRuntimeBridgeIntReturnAdapter return_adapter) {\n";
    stream << "    return CopperfinRuntimeBridgeStubEmissionWrapper{\n";
    stream << "        native_return_surface,\n";
    stream << "        return_adapter};\n";
    stream << "}\n\n";
}

} // namespace runtime_pipeline_detail

} // namespace copperfin::runtime
