// Copyright © 2026 Richard M. Hamilton.
// SPDX-License-Identifier: GPL-3.0-only
// Additional permission: Copperfin Application, Runtime, and Toolchain Exception 1.0; see LICENSE.

#include "runtime_pipeline_support.h"

namespace copperfin::runtime {

namespace runtime_pipeline_detail {

void append_native_wrapper_request_serialization_source(std::ostringstream& stream) {
    stream << "static CopperfinRuntimeBridgeDescriptor copperfin_build_runtime_bridge_descriptor(\n";
    stream << "    const char* export_name,\n";
    stream << "    const char* routine_kind,\n";
    stream << "    const char* source_path,\n";
    stream << "    unsigned int source_line,\n";
    stream << "    const char* parameter_declaration_kind,\n";
    stream << "    const char* parameter_names,\n";
    stream << "    unsigned int parameter_count,\n";
    stream << "    void* symbol_address,\n";
    stream << "    CopperfinRuntimeBridgeStubEmissionWrapper stub_emission_wrapper) {\n";
    stream << "    return CopperfinRuntimeBridgeDescriptor{\n";
    stream << "        export_name,\n";
    stream << "        routine_kind,\n";
    stream << "        source_path,\n";
    stream << "        source_line,\n";
    stream << "        parameter_declaration_kind,\n";
    stream << "        parameter_names,\n";
    stream << "        parameter_count,\n";
    stream << "        copperfin_runtime_manifest_path(symbol_address),\n";
    stream << "        copperfin_runtime_host_path(symbol_address),\n";
    stream << "        std::move(stub_emission_wrapper)};\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_runtime_bridge_manifest_flag() {\n";
    stream << "    return \"--manifest\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_runtime_bridge_library_export_flag() {\n";
    stream << "    return \"--library-export\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_runtime_bridge_routine_kind_flag() {\n";
    stream << "    return \"--routine-kind\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_runtime_bridge_source_path_flag() {\n";
    stream << "    return \"--source-path\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_runtime_bridge_source_line_flag() {\n";
    stream << "    return \"--source-line\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_runtime_bridge_parameter_declaration_flag() {\n";
    stream << "    return \"--parameter-declaration\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_runtime_bridge_parameter_names_flag() {\n";
    stream << "    return \"--parameter-names\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_runtime_bridge_parameter_count_flag() {\n";
    stream << "    return \"--parameter-count\";\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeInvocation copperfin_build_runtime_bridge_invocation(\n";
    stream << "    const CopperfinRuntimeBridgeDescriptor& descriptor) {\n";
    stream << "    return CopperfinRuntimeBridgeInvocation{\n";
    stream << "        descriptor,\n";
    stream << "        {\n";
    stream << "            copperfin_runtime_bridge_path_to_utf8_string(descriptor.runtime_host_path),\n";
    stream << "            copperfin_runtime_bridge_manifest_flag(),\n";
    stream << "            copperfin_runtime_bridge_path_to_utf8_string(descriptor.manifest_path),\n";
    stream << "            copperfin_runtime_bridge_library_export_flag(),\n";
    stream << "            descriptor.export_name,\n";
    stream << "            copperfin_runtime_bridge_routine_kind_flag(),\n";
    stream << "            descriptor.routine_kind,\n";
    stream << "            copperfin_runtime_bridge_source_path_flag(),\n";
    stream << "            descriptor.source_path,\n";
    stream << "            copperfin_runtime_bridge_source_line_flag(),\n";
    stream << "            std::to_string(descriptor.source_line),\n";
    stream << "            copperfin_runtime_bridge_parameter_declaration_flag(),\n";
    stream << "            descriptor.parameter_declaration_kind,\n";
    stream << "            copperfin_runtime_bridge_parameter_names_flag(),\n";
    stream << "            descriptor.parameter_names,\n";
    stream << "            copperfin_runtime_bridge_parameter_count_flag(),\n";
    stream << "            std::to_string(descriptor.parameter_count)}};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeCall copperfin_build_runtime_bridge_call(\n";
    stream << "    const CopperfinRuntimeBridgeInvocation& invocation,\n";
    stream << "    std::vector<CopperfinRuntimeBridgeParameter> parameters) {\n";
    stream << "    return CopperfinRuntimeBridgeCall{invocation, std::move(parameters)};\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_escape_runtime_bridge_json_string(const std::string& value) {\n";
    stream << "    std::string escaped;\n";
    stream << "    escaped.reserve(value.size());\n";
    stream << "    for (const char ch : value) {\n";
    stream << "        switch (ch) {\n";
    stream << "        case '\\\\':\n";
    stream << "            escaped += \"\\\\\\\\\";\n";
    stream << "            break;\n";
    stream << "        case '\"':\n";
    stream << "            escaped += \"\\\\\\\"\";\n";
    stream << "            break;\n";
    stream << "        case '\\n':\n";
    stream << "            escaped += \"\\\\n\";\n";
    stream << "            break;\n";
    stream << "        case '\\r':\n";
    stream << "            escaped += \"\\\\r\";\n";
    stream << "            break;\n";
    stream << "        case '\\t':\n";
    stream << "            escaped += \"\\\\t\";\n";
    stream << "            break;\n";
    stream << "        default:\n";
    stream << "            escaped.push_back(ch);\n";
    stream << "            break;\n";
    stream << "        }\n";
    stream << "    }\n";
    stream << "    return escaped;\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_payload_shape_field_name() {\n";
    stream << "    return \"payload_shape\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_export_name_field_name() {\n";
    stream << "    return \"export_name\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_routine_kind_field_name() {\n";
    stream << "    return \"routine_kind\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_source_path_field_name() {\n";
    stream << "    return \"source_path\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_source_line_field_name() {\n";
    stream << "    return \"source_line\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_parameter_declaration_field_name() {\n";
    stream << "    return \"parameter_declaration\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_parameter_names_field_name() {\n";
    stream << "    return \"parameter_names\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_parameter_count_field_name() {\n";
    stream << "    return \"parameter_count\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_schema_version_field_name() {\n";
    stream << "    return \"schema_version\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_parameters_field_name() {\n";
    stream << "    return \"parameters\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_request_media_type_field_name() {\n";
    stream << "    return \"request_media_type\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_request_fields_field_name() {\n";
    stream << "    return \"request_fields\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_expected_response_media_type_field_name() {\n";
    stream << "    return \"expected_response_media_type\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_response_fields_field_name() {\n";
    stream << "    return \"response_fields\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_parameter_name_field_name() {\n";
    stream << "    return \"name\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_parameter_value_field_name() {\n";
    stream << "    return \"value\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_parameter_surface_field_name() {\n";
    stream << "    return \"surface\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_request_document(\n";
    stream << "    const CopperfinRuntimeBridgeCall& call,\n";
    stream << "    const CopperfinRuntimeBridgePayloadPlan& payload_plan,\n";
    stream << "    const std::string& request_media_type) {\n";
    stream << "    std::ostringstream request_stream;\n";
    stream << "    request_stream << \"{\\n\";\n";
    stream << "    request_stream << \"  \\\"\"\n";
    stream << "                   << copperfin_build_runtime_bridge_payload_shape_field_name()\n";
    stream << "                   << \"\\\": \\\"\"\n";
    stream << "                   << copperfin_escape_runtime_bridge_json_string(payload_plan.request_payload_shape)\n";
    stream << "                   << \"\\\",\\n\";\n";
    stream << "    request_stream << \"  \\\"\"\n";
    stream << "                   << copperfin_build_runtime_bridge_export_name_field_name()\n";
    stream << "                   << \"\\\": \\\"\"\n";
    stream << "                   << copperfin_escape_runtime_bridge_json_string(call.invocation.descriptor.export_name)\n";
    stream << "                   << \"\\\",\\n\";\n";
    stream << "    request_stream << \"  \\\"\"\n";
    stream << "                   << copperfin_build_runtime_bridge_routine_kind_field_name()\n";
    stream << "                   << \"\\\": \\\"\"\n";
    stream << "                   << copperfin_escape_runtime_bridge_json_string(call.invocation.descriptor.routine_kind)\n";
    stream << "                   << \"\\\",\\n\";\n";
    stream << "    request_stream << \"  \\\"\"\n";
    stream << "                   << copperfin_build_runtime_bridge_source_path_field_name()\n";
    stream << "                   << \"\\\": \\\"\"\n";
    stream << "                   << copperfin_escape_runtime_bridge_json_string(call.invocation.descriptor.source_path)\n";
    stream << "                   << \"\\\",\\n\";\n";
    stream << "    request_stream << \"  \\\"\"\n";
    stream << "                   << copperfin_build_runtime_bridge_source_line_field_name()\n";
    stream << "                   << \"\\\": \" << call.invocation.descriptor.source_line << \",\\n\";\n";
    stream << "    request_stream << \"  \\\"\"\n";
    stream << "                   << copperfin_build_runtime_bridge_parameter_declaration_field_name()\n";
    stream << "                   << \"\\\": \\\"\"\n";
    stream << "                   << copperfin_escape_runtime_bridge_json_string(call.invocation.descriptor.parameter_declaration_kind)\n";
    stream << "                   << \"\\\",\\n\";\n";
    stream << "    request_stream << \"  \\\"\"\n";
    stream << "                   << copperfin_build_runtime_bridge_parameter_names_field_name()\n";
    stream << "                   << \"\\\": \\\"\"\n";
    stream << "                   << copperfin_escape_runtime_bridge_json_string(call.invocation.descriptor.parameter_names)\n";
    stream << "                   << \"\\\",\\n\";\n";
    stream << "    request_stream << \"  \\\"\"\n";
    stream << "                   << copperfin_build_runtime_bridge_parameter_count_field_name()\n";
    stream << "                   << \"\\\": \" << call.invocation.descriptor.parameter_count << \",\\n\";\n";
    stream << "    request_stream << \"  \\\"\"\n";
    stream << "                   << copperfin_build_runtime_bridge_schema_version_field_name()\n";
    stream << "                   << \"\\\": \\\"\"\n";
    stream << "                   << copperfin_escape_runtime_bridge_json_string(payload_plan.dispatch_plan.serialization_plan.schema_version)\n";
    stream << "                   << \"\\\",\\n\";\n";
    stream << "    request_stream << \"  \\\"\"\n";
    stream << "                   << copperfin_build_runtime_bridge_request_media_type_field_name()\n";
    stream << "                   << \"\\\": \\\"\"\n";
    stream << "                   << copperfin_escape_runtime_bridge_json_string(request_media_type)\n";
    stream << "                   << \"\\\",\\n\";\n";
    stream << "    request_stream << \"  \\\"\"\n";
    stream << "                   << copperfin_build_runtime_bridge_expected_response_media_type_field_name()\n";
    stream << "                   << \"\\\": \\\"\"\n";
    stream << "                   << copperfin_escape_runtime_bridge_json_string(payload_plan.dispatch_plan.serialization_plan.response_media_type)\n";
    stream << "                   << \"\\\",\\n\";\n";
    stream << "    request_stream << \"  \\\"\"\n";
    stream << "                   << copperfin_build_runtime_bridge_request_fields_field_name()\n";
    stream << "                   << \"\\\": [\";\n";
    stream << "    for (std::size_t index = 0; index < payload_plan.request_fields.size(); ++index) {\n";
    stream << "        if (index > 0U) {\n";
    stream << "            request_stream << \", \";\n";
    stream << "        }\n";
    stream << "        request_stream << \"\\\"\"\n";
    stream << "                       << copperfin_escape_runtime_bridge_json_string(payload_plan.request_fields[index])\n";
    stream << "                       << \"\\\"\";\n";
    stream << "    }\n";
    stream << "    request_stream << \"],\\n\";\n";
    stream << "    request_stream << \"  \\\"\"\n";
    stream << "                   << copperfin_build_runtime_bridge_response_fields_field_name()\n";
    stream << "                   << \"\\\": [\";\n";
    stream << "    for (std::size_t index = 0; index < payload_plan.response_fields.size(); ++index) {\n";
    stream << "        if (index > 0U) {\n";
    stream << "            request_stream << \", \";\n";
    stream << "        }\n";
    stream << "        request_stream << \"\\\"\"\n";
    stream << "                       << copperfin_escape_runtime_bridge_json_string(payload_plan.response_fields[index])\n";
    stream << "                       << \"\\\"\";\n";
    stream << "    }\n";
    stream << "    request_stream << \"],\\n\";\n";
    stream << "    request_stream << \"  \\\"\"\n";
    stream << "                   << copperfin_build_runtime_bridge_parameters_field_name()\n";
    stream << "                   << \"\\\": [\\n\";\n";
    stream << "    for (std::size_t index = 0; index < call.parameters.size(); ++index) {\n";
    stream << "        const auto& parameter = call.parameters[index];\n";
    stream << "        request_stream << \"    {\\\"\"\n";
    stream << "                       << copperfin_build_runtime_bridge_parameter_name_field_name()\n";
    stream << "                       << \"\\\": \\\"\"\n";
    stream << "                       << copperfin_escape_runtime_bridge_json_string(parameter.parameter_name)\n";
    stream << "                       << \"\\\", \\\"\"\n";
    stream << "                       << copperfin_build_runtime_bridge_parameter_value_field_name()\n";
    stream << "                       << \"\\\": \\\"\"\n";
    stream << "                       << copperfin_escape_runtime_bridge_json_string(parameter.value_representation)\n";
    stream << "                       << \"\\\", \\\"\"\n";
    stream << "                       << copperfin_build_runtime_bridge_parameter_surface_field_name()\n";
    stream << "                       << \"\\\": \\\"\"\n";
    stream << "                       << copperfin_escape_runtime_bridge_json_string(parameter.call_surface)\n";
    stream << "                       << \"\\\"}\";\n";
    stream << "        if (index + 1U < call.parameters.size()) {\n";
    stream << "            request_stream << \",\";\n";
    stream << "        }\n";
    stream << "        request_stream << \"\\n\";\n";
    stream << "    }\n";
    stream << "    request_stream << \"  ]\\n\";\n";
    stream << "    request_stream << \"}\";\n";
    stream << "    return request_stream.str();\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeResult copperfin_build_runtime_bridge_result(\n";
    stream << "    CopperfinRuntimeBridgeCall call,\n";
    stream << "    CopperfinRuntimeBridgeReturn return_binding) {\n";
    stream << "    return CopperfinRuntimeBridgeResult{std::move(call), std::move(return_binding)};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeReturn copperfin_build_runtime_bridge_placeholder_return_binding(\n";
    stream << "    std::string return_surface) {\n";
    stream << "    return CopperfinRuntimeBridgeReturn{std::to_string(-1), std::move(return_surface)};\n";
    stream << "}\n\n";
}

} // namespace runtime_pipeline_detail

} // namespace copperfin::runtime
