// Copyright © 2026 Richard M. Hamilton.
// SPDX-License-Identifier: GPL-3.0-only
// Additional permission: Copperfin Application, Runtime, and Toolchain Exception 1.0; see LICENSE.

#include "runtime_pipeline_support.h"

#include <locale>

namespace copperfin::runtime {

namespace runtime_pipeline_detail {

void append_native_wrapper_bridge_model_source(std::ostringstream& stream) {
    stream << "static std::string copperfin_runtime_bridge_path_to_utf8_string(const std::filesystem::path& path) {\n";
    stream << "    const auto utf8 = path.u8string();\n";
    stream << "    return std::string(reinterpret_cast<const char*>(utf8.data()), utf8.size());\n";
    stream << "}\n\n";
    stream << "static std::filesystem::path copperfin_wrapper_module_path(void* symbol_address) {\n";
    stream << "#if defined(_WIN32)\n";
    stream << "    HMODULE module = nullptr;\n";
    stream << "    if (!GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,\n";
    stream << "                            reinterpret_cast<LPCSTR>(symbol_address),\n";
    stream << "                            &module) || module == nullptr) {\n";
    stream << "        return {};\n";
    stream << "    }\n";
    stream << "    std::wstring buffer(512U, L'\\0');\n";
    stream << "    for (;;) {\n";
    stream << "        const DWORD length = GetModuleFileNameW(module, buffer.data(), static_cast<DWORD>(buffer.size()));\n";
    stream << "        if (length == 0U) {\n";
    stream << "            return {};\n";
    stream << "        }\n";
    stream << "        if (length + 1U < buffer.size()) {\n";
    stream << "            buffer.resize(length);\n";
    stream << "            return std::filesystem::path(buffer).lexically_normal();\n";
    stream << "        }\n";
    stream << "        buffer.resize(buffer.size() * 2U);\n";
    stream << "    }\n";
    stream << "#else\n";
    stream << "    Dl_info info{};\n";
    stream << "    if (dladdr(symbol_address, &info) == 0 || info.dli_fname == nullptr) {\n";
    stream << "        return {};\n";
    stream << "    }\n";
    stream << "    return std::filesystem::path(info.dli_fname).lexically_normal();\n";
    stream << "#endif\n";
    stream << "}\n\n";
    stream << "static std::filesystem::path copperfin_wrapper_module_directory(void* symbol_address) {\n";
    stream << "    const auto module_path = copperfin_wrapper_module_path(symbol_address);\n";
    stream << "    return module_path.empty() ? std::filesystem::path{} : module_path.parent_path();\n";
    stream << "}\n\n";
    stream << "static std::filesystem::path copperfin_runtime_manifest_path(void* symbol_address) {\n";
    stream << "    return copperfin_wrapper_module_directory(symbol_address) / \"app.cfmanifest\";\n";
    stream << "}\n\n";
    stream << "static std::filesystem::path copperfin_runtime_host_path(void* symbol_address) {\n";
    stream << "#if defined(_WIN32)\n";
    stream << "    return copperfin_wrapper_module_directory(symbol_address) / \"copperfin_runtime_host.exe\";\n";
    stream << "#else\n";
    stream << "    return copperfin_wrapper_module_directory(symbol_address) / \"copperfin_runtime_host\";\n";
    stream << "#endif\n";
    stream << "}\n\n";
    stream << "using CopperfinRuntimeBridgeIntReturnAdapter = int (*)(int);\n\n";
    stream << "struct CopperfinRuntimeBridgeStubEmissionWrapper {\n";
    stream << "    std::string native_return_surface;\n";
    stream << "    CopperfinRuntimeBridgeIntReturnAdapter return_adapter = nullptr;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeDescriptor {\n";
    stream << "    const char* export_name;\n";
    stream << "    const char* routine_kind;\n";
    stream << "    const char* source_path;\n";
    stream << "    unsigned int source_line;\n";
    stream << "    const char* parameter_declaration_kind;\n";
    stream << "    const char* parameter_names;\n";
    stream << "    unsigned int parameter_count;\n";
    stream << "    std::filesystem::path manifest_path;\n";
    stream << "    std::filesystem::path runtime_host_path;\n";
    stream << "    CopperfinRuntimeBridgeStubEmissionWrapper stub_emission_wrapper;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeInvocation {\n";
    stream << "    CopperfinRuntimeBridgeDescriptor descriptor;\n";
    stream << "    std::vector<std::string> arguments;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeParameter {\n";
    stream << "    std::string parameter_name;\n";
    stream << "    std::string value_representation;\n";
    stream << "    std::string call_surface;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeCall {\n";
    stream << "    CopperfinRuntimeBridgeInvocation invocation;\n";
    stream << "    std::vector<CopperfinRuntimeBridgeParameter> parameters;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeReturn {\n";
    stream << "    std::string value_representation;\n";
    stream << "    std::string return_surface;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeResult {\n";
    stream << "    CopperfinRuntimeBridgeCall call;\n";
    stream << "    CopperfinRuntimeBridgeReturn return_binding;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeEnvironmentVariable {\n";
    stream << "    std::string name;\n";
    stream << "    std::string value;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeLaunchPlan {\n";
    stream << "    CopperfinRuntimeBridgeResult result;\n";
    stream << "    std::filesystem::path working_directory;\n";
    stream << "    std::vector<CopperfinRuntimeBridgeEnvironmentVariable> environment;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeObservationPlan {\n";
    stream << "    CopperfinRuntimeBridgeLaunchPlan launch_plan;\n";
    stream << "    std::filesystem::path stdout_log_path;\n";
    stream << "    std::filesystem::path stderr_log_path;\n";
    stream << "    int expected_exit_code = 0;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeExecutionPlan {\n";
    stream << "    CopperfinRuntimeBridgeObservationPlan observation_plan;\n";
    stream << "    std::filesystem::path executable_path;\n";
    stream << "    std::vector<std::string> arguments;\n";
    stream << "    bool capture_stdout = true;\n";
    stream << "    bool capture_stderr = true;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeTransportPlan {\n";
    stream << "    CopperfinRuntimeBridgeExecutionPlan execution_plan;\n";
    stream << "    std::filesystem::path request_path;\n";
    stream << "    std::filesystem::path response_path;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeSerializationPlan {\n";
    stream << "    CopperfinRuntimeBridgeTransportPlan transport_plan;\n";
    stream << "    std::string request_media_type;\n";
    stream << "    std::string response_media_type;\n";
    stream << "    std::string schema_version;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeDispatchPlan {\n";
    stream << "    CopperfinRuntimeBridgeSerializationPlan serialization_plan;\n";
    stream << "    std::vector<std::string> arguments;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeDispatchExecution {\n";
    stream << "    std::filesystem::path executable_path;\n";
    stream << "    std::filesystem::path manifest_path;\n";
    stream << "    std::vector<std::string> arguments;\n";
    stream << "    std::filesystem::path working_directory;\n";
    stream << "    std::vector<CopperfinRuntimeBridgeEnvironmentVariable> environment;\n";
    stream << "    std::filesystem::path stdout_log_path;\n";
    stream << "    std::filesystem::path stderr_log_path;\n";
    stream << "    bool capture_stdout = true;\n";
    stream << "    bool capture_stderr = true;\n";
    stream << "    int expected_exit_code = 0;\n";
    stream << "    bool verify_runtime_host = true;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeProcessLaunch {\n";
    stream << "    std::filesystem::path executable_path;\n";
    stream << "    std::vector<std::string> arguments;\n";
    stream << "    std::filesystem::path working_directory;\n";
    stream << "    std::vector<CopperfinRuntimeBridgeEnvironmentVariable> environment;\n";
    stream << "    std::filesystem::path stdout_log_path;\n";
    stream << "    std::filesystem::path stderr_log_path;\n";
    stream << "    bool capture_stdout = true;\n";
    stream << "    bool capture_stderr = true;\n";
    stream << "    bool launch_attempted = false;\n";
    stream << "    bool launch_succeeded = false;\n";
    stream << "    int exit_code = 0;\n";
    stream << "    int expected_exit_code = 0;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeHostFailureEvaluation {\n";
    stream << "    bool launch_failed = true;\n";
    stream << "    bool should_use_fallback_return = true;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    std::string fallback_return_value;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeMissingResponseEvaluation {\n";
    stream << "    bool response_missing = true;\n";
    stream << "    bool should_use_fallback_return = true;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    std::string fallback_return_value;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeResponseValidationEvaluation {\n";
    stream << "    bool validation_failed = true;\n";
    stream << "    bool response_document_available = false;\n";
    stream << "    bool should_use_fallback_return = true;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    std::string fallback_return_value;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgePayloadPlan {\n";
    stream << "    CopperfinRuntimeBridgeDispatchPlan dispatch_plan;\n";
    stream << "    std::string request_payload_shape;\n";
    stream << "    std::string response_payload_shape;\n";
    stream << "    std::vector<std::string> request_fields;\n";
    stream << "    std::vector<std::string> response_fields;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeInterpretationPlan {\n";
    stream << "    CopperfinRuntimeBridgePayloadPlan payload_plan;\n";
    stream << "    std::string status_field;\n";
    stream << "    std::string value_field;\n";
    stream << "    std::string diagnostics_field;\n";
    stream << "    std::string wrapper_return_surface;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeFailurePolicyPlan {\n";
    stream << "    CopperfinRuntimeBridgeInterpretationPlan interpretation_plan;\n";
    stream << "    bool fail_on_nonzero_exit = true;\n";
    stream << "    bool fail_on_missing_response = true;\n";
    stream << "    std::string diagnostics_fallback;\n";
    stream << "    std::string fallback_return_value;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeResponseValidationPlan {\n";
    stream << "    CopperfinRuntimeBridgeFailurePolicyPlan failure_policy_plan;\n";
    stream << "    std::string expected_response_media_type;\n";
    stream << "    std::string expected_schema_version;\n";
    stream << "    std::vector<std::string> required_response_fields;\n";
    stream << "    std::string success_status_value;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeRequestArtifact {\n";
    stream << "    CopperfinRuntimeBridgeResponseValidationPlan response_validation_plan;\n";
    stream << "    std::string request_document;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeRequestWritePlan {\n";
    stream << "    CopperfinRuntimeBridgeRequestArtifact request_artifact;\n";
    stream << "    std::filesystem::path target_path;\n";
    stream << "    std::string write_mode;\n";
    stream << "    bool ensure_parent_directory = true;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeResponseReadPlan {\n";
    stream << "    CopperfinRuntimeBridgeRequestWritePlan request_write_plan;\n";
    stream << "    bool request_write_succeeded = false;\n";
    stream << "    std::filesystem::path source_path;\n";
    stream << "    std::string read_mode;\n";
    stream << "    bool require_existing_response = true;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeResponseArtifact {\n";
    stream << "    CopperfinRuntimeBridgeResponseReadPlan response_read_plan;\n";
    stream << "    std::string response_document;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeResponseParsePlan {\n";
    stream << "    CopperfinRuntimeBridgeResponseArtifact response_artifact;\n";
    stream << "    std::string parser_kind;\n";
    stream << "    std::string status_field;\n";
    stream << "    std::string value_field;\n";
    stream << "    std::string diagnostics_field;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeResponseParseAdmission {\n";
    stream << "    bool should_parse_response = false;\n";
    stream << "    bool should_use_fallback_return = true;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    std::string fallback_return_value;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeParsedResponse {\n";
    stream << "    std::string status_value;\n";
    stream << "    std::string return_value_representation;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeInterpretedResultPlan {\n";
    stream << "    CopperfinRuntimeBridgeResponseParsePlan response_parse_plan;\n";
    stream << "    CopperfinRuntimeBridgeParsedResponse parsed_response;\n";
    stream << "    std::string success_status_value;\n";
    stream << "    std::string wrapper_return_surface;\n";
    stream << "    std::string fallback_return_value;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeInterpretedResultAdmission {\n";
    stream << "    bool should_interpret_result = false;\n";
    stream << "    bool should_use_fallback_return = true;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    std::string fallback_return_value;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeInterpretedResult {\n";
    stream << "    bool matched_success_status = false;\n";
    stream << "    std::string selected_return_value_representation;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    std::string wrapper_return_surface;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeNativeReturnPlan {\n";
    stream << "    CopperfinRuntimeBridgeInterpretedResultPlan interpreted_result_plan;\n";
    stream << "    CopperfinRuntimeBridgeInterpretedResult interpreted_result;\n";
    stream << "    std::string success_value_representation;\n";
    stream << "    int success_int_value = -1;\n";
    stream << "    std::string fallback_value_representation;\n";
    stream << "    int fallback_int_value = -1;\n";
    stream << "    std::string native_return_surface;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeNativeReturnAdmission {\n";
    stream << "    bool should_materialize_native_return = false;\n";
    stream << "    bool should_use_fallback_return = true;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    std::string fallback_return_value;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeNativeReturn {\n";
    stream << "    bool matched_success_status = false;\n";
    stream << "    std::string selected_value_representation;\n";
    stream << "    int selected_int_value = -1;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    std::string native_return_surface;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeOutcomeSelectionPlan {\n";
    stream << "    CopperfinRuntimeBridgeNativeReturnPlan native_return_plan;\n";
    stream << "    CopperfinRuntimeBridgeNativeReturn native_return;\n";
    stream << "    std::string success_condition;\n";
    stream << "    std::string fallback_condition;\n";
    stream << "    std::string diagnostics_field;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeOutcomeSelectionAdmission {\n";
    stream << "    bool should_select_outcome = false;\n";
    stream << "    bool should_use_fallback_return = true;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    std::string fallback_return_value;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeOutcomeSelection {\n";
    stream << "    bool matched_success_status = false;\n";
    stream << "    std::string selected_condition;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    std::string selected_value_representation;\n";
    stream << "    int selected_int_value = -1;\n";
    stream << "    std::string native_return_surface;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeReturnMaterializationPlan {\n";
    stream << "    CopperfinRuntimeBridgeOutcomeSelectionPlan outcome_selection_plan;\n";
    stream << "    CopperfinRuntimeBridgeOutcomeSelection outcome_selection;\n";
    stream << "    std::string success_return_statement;\n";
    stream << "    std::string fallback_return_statement;\n";
    stream << "    std::string native_return_surface;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeReturnMaterializationAdmission {\n";
    stream << "    bool should_materialize_return = false;\n";
    stream << "    bool should_use_fallback_return = true;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    std::string fallback_return_value;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeReturnMaterialization {\n";
    stream << "    bool matched_success_status = false;\n";
    stream << "    std::string success_condition;\n";
    stream << "    std::string selected_condition;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    std::string success_return_statement;\n";
    stream << "    std::string fallback_return_statement;\n";
    stream << "    std::string native_return_surface;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeReturnEmissionPlan {\n";
    stream << "    CopperfinRuntimeBridgeReturnMaterializationPlan return_materialization_plan;\n";
    stream << "    CopperfinRuntimeBridgeReturnMaterialization return_materialization;\n";
    stream << "    std::string success_branch_statement;\n";
    stream << "    std::string fallback_branch_statement;\n";
    stream << "    std::string emitted_return_block;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeReturnEmissionAdmission {\n";
    stream << "    bool should_emit_return = false;\n";
    stream << "    bool should_use_fallback_return = true;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    std::string emitted_return_block;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeReturnEmission {\n";
    stream << "    bool matched_success_status = false;\n";
    stream << "    std::string selected_condition;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    std::string success_branch_statement;\n";
    stream << "    std::string fallback_branch_statement;\n";
    stream << "    std::string emitted_return_block;\n";
    stream << "    std::string native_return_surface;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeFinalReturnAdoptionPlan {\n";
    stream << "    CopperfinRuntimeBridgeReturnEmissionPlan return_emission_plan;\n";
    stream << "    CopperfinRuntimeBridgeReturnEmission return_emission;\n";
    stream << "    std::string placeholder_return_statement;\n";
    stream << "    std::string adopted_return_block;\n";
    stream << "    std::string adoption_mode;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeFinalReturnAdoptionAdmission {\n";
    stream << "    bool should_adopt_return = false;\n";
    stream << "    bool should_use_placeholder_return = true;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    std::string selected_return_block;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeFinalReturnAdoption {\n";
    stream << "    bool matched_success_status = false;\n";
    stream << "    std::string selected_condition;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    std::string placeholder_return_statement;\n";
    stream << "    std::string adopted_return_block;\n";
    stream << "    std::string adoption_mode;\n";
    stream << "    std::string native_return_surface;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeReturnActivationPlan {\n";
    stream << "    CopperfinRuntimeBridgeFinalReturnAdoptionPlan final_return_adoption_plan;\n";
    stream << "    CopperfinRuntimeBridgeFinalReturnAdoption final_return_adoption;\n";
    stream << "    bool activates_adopted_return = false;\n";
    stream << "    std::string activation_mode;\n";
    stream << "    std::string active_return_block;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeReturnActivationAdmission {\n";
    stream << "    bool should_activate_return = false;\n";
    stream << "    bool should_emit_placeholder_return = true;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    std::string selected_return_block;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeReturnActivation {\n";
    stream << "    bool matched_success_status = false;\n";
    stream << "    std::string selected_condition;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    bool activates_adopted_return = false;\n";
    stream << "    std::string activation_mode;\n";
    stream << "    std::string active_return_block;\n";
    stream << "    std::string native_return_surface;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeStubReturnPlan {\n";
    stream << "    CopperfinRuntimeBridgeReturnActivationPlan return_activation_plan;\n";
    stream << "    CopperfinRuntimeBridgeReturnActivation return_activation;\n";
    stream << "    std::string emitted_return_statement;\n";
    stream << "    std::string deferred_return_block;\n";
    stream << "    bool emits_placeholder_return = true;\n";
    stream << "    std::string activation_mode;\n";
    stream << "    std::string adoption_mode;\n";
    stream << "    bool keeps_placeholder_return_active = true;\n";
    stream << "    bool adopts_placeholder_replacement = true;\n";
    stream << "    int placeholder_fallback_int_value = -1;\n";
    stream << "    std::string placeholder_fallback_value_representation;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeStubReturnAdmission {\n";
    stream << "    bool should_route_stub_return = false;\n";
    stream << "    bool should_emit_placeholder_return = true;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    std::string selected_return_statement;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeStubReturn {\n";
    stream << "    bool matched_success_status = false;\n";
    stream << "    std::string selected_condition;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    std::string emitted_return_statement;\n";
    stream << "    std::string deferred_return_block;\n";
    stream << "    bool emits_placeholder_return = true;\n";
    stream << "    std::string activation_mode;\n";
    stream << "    std::string adoption_mode;\n";
    stream << "    bool keeps_placeholder_return_active = true;\n";
    stream << "    bool adopts_placeholder_replacement = true;\n";
    stream << "    int placeholder_fallback_int_value = -1;\n";
    stream << "    std::string placeholder_fallback_value_representation;\n";
    stream << "    std::string native_return_surface;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgePlaceholderReturnValuePlan {\n";
    stream << "    CopperfinRuntimeBridgeStubReturnPlan stub_return_plan;\n";
    stream << "    CopperfinRuntimeBridgeStubReturn stub_return;\n";
    stream << "    bool emits_placeholder_return = true;\n";
    stream << "    std::string emitted_return_statement;\n";
    stream << "    std::string deferred_return_block;\n";
    stream << "    std::string activation_mode;\n";
    stream << "    std::string adoption_mode;\n";
    stream << "    bool keeps_placeholder_return_active = true;\n";
    stream << "    bool adopts_placeholder_replacement = true;\n";
    stream << "    int fallback_int_value = -1;\n";
    stream << "    std::string fallback_value_representation;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgePlaceholderReturnValueAdmission {\n";
    stream << "    bool should_emit_placeholder_return = true;\n";
    stream << "    bool should_keep_deferred_return = true;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    std::string selected_return_statement;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgePlaceholderReturnValue {\n";
    stream << "    bool matched_success_status = false;\n";
    stream << "    std::string selected_condition;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    bool emits_placeholder_return = true;\n";
    stream << "    std::string emitted_return_statement;\n";
    stream << "    std::string deferred_return_block;\n";
    stream << "    std::string activation_mode;\n";
    stream << "    std::string adoption_mode;\n";
    stream << "    bool keeps_placeholder_return_active = true;\n";
    stream << "    bool adopts_placeholder_replacement = true;\n";
    stream << "    int fallback_int_value = -1;\n";
    stream << "    std::string fallback_value_representation;\n";
    stream << "    std::string native_return_surface;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgePlaceholderReturnIntAdmission {\n";
    stream << "    bool should_return_int = true;\n";
    stream << "    bool should_emit_placeholder_return = true;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    int selected_int_value = -1;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeStubEmissionAdmission {\n";
    stream << "    bool should_emit_stub_return = true;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    int selected_int_value = -1;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeStubEmission {\n";
    stream << "    bool should_emit_stub_return = true;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    int emitted_int_value = -1;\n";
    stream << "};\n\n";
    stream << "struct CopperfinRuntimeBridgeStubEmissionReturnSurface {\n";
    stream << "    std::string native_return_surface;\n";
    stream << "    std::string diagnostics_value;\n";
    stream << "    int emitted_int_value = -1;\n";
    stream << "};\n\n";
    append_native_wrapper_request_serialization_source(stream);
}

} // namespace runtime_pipeline_detail

} // namespace copperfin::runtime
