// Copyright © 2026 Richard M. Hamilton.
// SPDX-License-Identifier: GPL-3.0-only
// Additional permission: Copperfin Application, Runtime, and Toolchain Exception 1.0; see LICENSE.

#include "runtime_pipeline_support.h"

#include <locale>

namespace copperfin::runtime {

namespace runtime_pipeline_detail {

void append_native_wrapper_process_launch_source(std::ostringstream& stream) {
    stream << "static std::string copperfin_runtime_bridge_library_export_env_var() {\n";
    stream << "    return \"COPPERFIN_LIBRARY_EXPORT\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_runtime_bridge_routine_kind_env_var() {\n";
    stream << "    return \"COPPERFIN_ROUTINE_KIND\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_runtime_bridge_source_path_env_var() {\n";
    stream << "    return \"COPPERFIN_SOURCE_PATH\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_runtime_bridge_parameter_count_env_var() {\n";
    stream << "    return \"COPPERFIN_PARAMETER_COUNT\";\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeLaunchPlan copperfin_build_runtime_bridge_launch_plan(\n";
    stream << "    CopperfinRuntimeBridgeResult result) {\n";
    stream << "    return CopperfinRuntimeBridgeLaunchPlan{\n";
    stream << "        result,\n";
    stream << "        result.call.invocation.descriptor.runtime_host_path.parent_path(),\n";
    stream << "        {\n";
    stream << "            {copperfin_runtime_bridge_library_export_env_var(), result.call.invocation.descriptor.export_name},\n";
    stream << "            {copperfin_runtime_bridge_routine_kind_env_var(), result.call.invocation.descriptor.routine_kind},\n";
    stream << "            {copperfin_runtime_bridge_source_path_env_var(), result.call.invocation.descriptor.source_path},\n";
    stream << "            {copperfin_runtime_bridge_parameter_count_env_var(), std::to_string(result.call.invocation.descriptor.parameter_count)}}};\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_runtime_bridge_stdout_log_suffix() {\n";
    stream << "    return \".stdout.log\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_runtime_bridge_stderr_log_suffix() {\n";
    stream << "    return \".stderr.log\";\n";
    stream << "}\n\n";
    stream << "static int copperfin_runtime_bridge_expected_exit_code() {\n";
    stream << "    return 0;\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeObservationPlan copperfin_build_runtime_bridge_observation_plan(\n";
    stream << "    CopperfinRuntimeBridgeLaunchPlan launch_plan) {\n";
    stream << "    const auto export_name = launch_plan.result.call.invocation.descriptor.export_name;\n";
    stream << "    const auto base_directory = launch_plan.working_directory;\n";
    stream << "    return CopperfinRuntimeBridgeObservationPlan{\n";
    stream << "        std::move(launch_plan),\n";
    stream << "        base_directory / (std::string(export_name) + copperfin_runtime_bridge_stdout_log_suffix()),\n";
    stream << "        base_directory / (std::string(export_name) + copperfin_runtime_bridge_stderr_log_suffix()),\n";
    stream << "        copperfin_runtime_bridge_expected_exit_code()};\n";
    stream << "}\n\n";
    stream << "static bool copperfin_runtime_bridge_capture_stdout_policy() {\n";
    stream << "    return true;\n";
    stream << "}\n\n";
    stream << "static bool copperfin_runtime_bridge_capture_stderr_policy() {\n";
    stream << "    return true;\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeExecutionPlan copperfin_build_runtime_bridge_execution_plan(\n";
    stream << "    CopperfinRuntimeBridgeObservationPlan observation_plan) {\n";
    stream << "    return CopperfinRuntimeBridgeExecutionPlan{\n";
    stream << "        observation_plan,\n";
    stream << "        observation_plan.launch_plan.result.call.invocation.descriptor.runtime_host_path,\n";
    stream << "        observation_plan.launch_plan.result.call.invocation.arguments,\n";
    stream << "        copperfin_runtime_bridge_capture_stdout_policy(),\n";
    stream << "        copperfin_runtime_bridge_capture_stderr_policy()};\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_runtime_bridge_request_artifact_suffix() {\n";
    stream << "    return \".request.json\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_runtime_bridge_response_artifact_suffix() {\n";
    stream << "    return \".response.json\";\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeTransportPlan copperfin_build_runtime_bridge_transport_plan(\n";
    stream << "    CopperfinRuntimeBridgeExecutionPlan execution_plan) {\n";
    stream << "    const auto export_name =\n";
    stream << "        execution_plan.observation_plan.launch_plan.result.call.invocation.descriptor.export_name;\n";
    stream << "    const auto base_directory =\n";
    stream << "        execution_plan.observation_plan.launch_plan.working_directory;\n";
    stream << "    static std::atomic<unsigned long long> invocation_sequence{0};\n";
    stream << "    const auto sequence = ++invocation_sequence;\n";
    stream << "#if defined(_WIN32)\n";
    stream << "    const auto process_identity = static_cast<unsigned long long>(GetCurrentProcessId());\n";
    stream << "#else\n";
    stream << "    const auto process_identity = static_cast<unsigned long long>(getpid());\n";
    stream << "#endif\n";
    stream << "    const std::string invocation_identity = std::to_string(process_identity) + \"-\" + std::to_string(sequence);\n";
    stream << "    const std::string artifact_stem = std::string(export_name) + \".\" + invocation_identity;\n";
    stream << "    execution_plan.observation_plan.stdout_log_path =\n";
    stream << "        base_directory / (artifact_stem + copperfin_runtime_bridge_stdout_log_suffix());\n";
    stream << "    execution_plan.observation_plan.stderr_log_path =\n";
    stream << "        base_directory / (artifact_stem + copperfin_runtime_bridge_stderr_log_suffix());\n";
    stream << "    return CopperfinRuntimeBridgeTransportPlan{\n";
    stream << "        std::move(execution_plan),\n";
    stream << "        base_directory / (artifact_stem + copperfin_runtime_bridge_request_artifact_suffix()),\n";
    stream << "        base_directory / (artifact_stem + copperfin_runtime_bridge_response_artifact_suffix())};\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_request_media_type_value() {\n";
    stream << "    return \"application/vnd.copperfin.runtime-bridge-request+json\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_response_media_type_value() {\n";
    stream << "    return \"application/vnd.copperfin.runtime-bridge-response+json\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_schema_version_value() {\n";
    stream << "    return \"v1\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_request_path_argument_name() {\n";
    stream << "    return \"--request-path\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_response_path_argument_name() {\n";
    stream << "    return \"--response-path\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_request_media_type_argument_name() {\n";
    stream << "    return \"--request-media-type\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_response_media_type_argument_name() {\n";
    stream << "    return \"--response-media-type\";\n";
    stream << "}\n\n";
    stream << "static std::string copperfin_build_runtime_bridge_schema_version_argument_name() {\n";
    stream << "    return \"--schema-version\";\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeSerializationPlan copperfin_build_runtime_bridge_serialization_plan(\n";
    stream << "    CopperfinRuntimeBridgeTransportPlan transport_plan) {\n";
    stream << "    return CopperfinRuntimeBridgeSerializationPlan{\n";
    stream << "        std::move(transport_plan),\n";
    stream << "        copperfin_build_runtime_bridge_request_media_type_value(),\n";
    stream << "        copperfin_build_runtime_bridge_response_media_type_value(),\n";
    stream << "        copperfin_build_runtime_bridge_schema_version_value()};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeDispatchPlan copperfin_build_runtime_bridge_dispatch_plan(\n";
    stream << "    CopperfinRuntimeBridgeSerializationPlan serialization_plan) {\n";
    stream << "    auto arguments = serialization_plan.transport_plan.execution_plan.arguments;\n";
    stream << "    arguments.push_back(copperfin_build_runtime_bridge_request_path_argument_name());\n";
    stream << "    arguments.push_back(copperfin_runtime_bridge_path_to_utf8_string(serialization_plan.transport_plan.request_path));\n";
    stream << "    arguments.push_back(copperfin_build_runtime_bridge_response_path_argument_name());\n";
    stream << "    arguments.push_back(copperfin_runtime_bridge_path_to_utf8_string(serialization_plan.transport_plan.response_path));\n";
    stream << "    arguments.push_back(copperfin_build_runtime_bridge_request_media_type_argument_name());\n";
    stream << "    arguments.push_back(serialization_plan.request_media_type);\n";
    stream << "    arguments.push_back(copperfin_build_runtime_bridge_response_media_type_argument_name());\n";
    stream << "    arguments.push_back(serialization_plan.response_media_type);\n";
    stream << "    arguments.push_back(copperfin_build_runtime_bridge_schema_version_argument_name());\n";
    stream << "    arguments.push_back(serialization_plan.schema_version);\n";
    stream << "    return CopperfinRuntimeBridgeDispatchPlan{std::move(serialization_plan), std::move(arguments)};\n";
    stream << "}\n\n";
    stream << "static CopperfinRuntimeBridgeDispatchExecution copperfin_runtime_bridge_execute_dispatch(\n";
    stream << "    const CopperfinRuntimeBridgeDispatchPlan& plan) {\n";
    stream << "    const auto& execution_plan = plan.serialization_plan.transport_plan.execution_plan;\n";
    stream << "    const auto& observation_plan = execution_plan.observation_plan;\n";
    stream << "    const auto& launch_plan = observation_plan.launch_plan;\n";
    stream << "    return CopperfinRuntimeBridgeDispatchExecution{\n";
    stream << "        execution_plan.executable_path,\n";
    stream << "        launch_plan.result.call.invocation.descriptor.manifest_path,\n";
    stream << "        plan.arguments,\n";
    stream << "        launch_plan.working_directory,\n";
    stream << "        launch_plan.environment,\n";
    stream << "        observation_plan.stdout_log_path,\n";
    stream << "        observation_plan.stderr_log_path,\n";
    stream << "        execution_plan.capture_stdout,\n";
    stream << "        execution_plan.capture_stderr,\n";
    stream << "        observation_plan.expected_exit_code,\n";
    stream << "        true};\n";
    stream << "}\n\n";
    stream << "#if defined(_WIN32)\n";
    stream << "static std::wstring copperfin_runtime_bridge_utf8_to_wide(const std::string& value) {\n";
    stream << "    if (value.empty()) {\n";
    stream << "        return {};\n";
    stream << "    }\n";
    stream << "    const int count = MultiByteToWideChar(CP_UTF8, MB_ERR_INVALID_CHARS, value.data(), static_cast<int>(value.size()), nullptr, 0);\n";
    stream << "    if (count <= 0) {\n";
    stream << "        return {};\n";
    stream << "    }\n";
    stream << "    std::wstring result(static_cast<std::size_t>(count), L'\\0');\n";
    stream << "    if (MultiByteToWideChar(CP_UTF8, MB_ERR_INVALID_CHARS, value.data(), static_cast<int>(value.size()), result.data(), count) != count) {\n";
    stream << "        return {};\n";
    stream << "    }\n";
    stream << "    return result;\n";
    stream << "}\n\n";
    stream << "static std::wstring copperfin_runtime_bridge_quote_windows_argument(const std::wstring& argument) {\n";
    stream << "    const bool needs_quotes = argument.empty() || argument.find_first_of(L\" \\t\\r\\n\\\"\") != std::wstring::npos;\n";
    stream << "    if (!needs_quotes) {\n";
    stream << "        return argument;\n";
    stream << "    }\n";
    stream << "    std::wstring quoted(1U, L'\"');\n";
    stream << "    std::size_t backslashes = 0U;\n";
    stream << "    for (const wchar_t ch : argument) {\n";
    stream << "        if (ch == L'\\\\') {\n";
    stream << "            ++backslashes;\n";
    stream << "            continue;\n";
    stream << "        }\n";
    stream << "        if (ch == L'\"') {\n";
    stream << "            quoted.append(backslashes * 2U + 1U, L'\\\\');\n";
    stream << "        } else {\n";
    stream << "            quoted.append(backslashes, L'\\\\');\n";
    stream << "        }\n";
    stream << "        quoted.push_back(ch);\n";
    stream << "        backslashes = 0U;\n";
    stream << "    }\n";
    stream << "    quoted.append(backslashes * 2U, L'\\\\');\n";
    stream << "    quoted.push_back(L'\"');\n";
    stream << "    return quoted;\n";
    stream << "}\n\n";
    stream << "static std::vector<std::wstring> copperfin_runtime_bridge_windows_environment(\n";
    stream << "    const std::vector<CopperfinRuntimeBridgeEnvironmentVariable>& overrides) {\n";
    stream << "    std::vector<std::wstring> entries;\n";
    stream << "    LPWCH raw_environment = GetEnvironmentStringsW();\n";
    stream << "    if (raw_environment != nullptr) {\n";
    stream << "        for (LPWCH current = raw_environment; *current != L'\\0'; current += std::wcslen(current) + 1U) {\n";
    stream << "            entries.emplace_back(current);\n";
    stream << "        }\n";
    stream << "        FreeEnvironmentStringsW(raw_environment);\n";
    stream << "    }\n";
    stream << "    for (const auto& override_value : overrides) {\n";
    stream << "        const auto name = copperfin_runtime_bridge_utf8_to_wide(override_value.name);\n";
    stream << "        const auto value = copperfin_runtime_bridge_utf8_to_wide(override_value.value);\n";
    stream << "        if (name.empty()) {\n";
    stream << "            continue;\n";
    stream << "        }\n";
    stream << "        const std::wstring prefix = name + L\"=\";\n";
    stream << "        const std::wstring replacement = prefix + value;\n";
    stream << "        bool replaced = false;\n";
    stream << "        for (auto& entry : entries) {\n";
    stream << "            if (entry.size() >= prefix.size() && _wcsnicmp(entry.c_str(), prefix.c_str(), prefix.size()) == 0) {\n";
    stream << "                entry = replacement;\n";
    stream << "                replaced = true;\n";
    stream << "            }\n";
    stream << "        }\n";
    stream << "        if (!replaced) {\n";
    stream << "            entries.push_back(replacement);\n";
    stream << "        }\n";
    stream << "    }\n";
    stream << "    std::sort(entries.begin(), entries.end(), [](const std::wstring& left, const std::wstring& right) {\n";
    stream << "        const std::size_t left_separator = left.find(L'=');\n";
    stream << "        const std::size_t right_separator = right.find(L'=');\n";
    stream << "        return _wcsicmp(left.substr(0U, left_separator).c_str(), right.substr(0U, right_separator).c_str()) < 0;\n";
    stream << "    });\n";
    stream << "    return entries;\n";
    stream << "}\n\n";
    stream << "#else\n";
    stream << "static std::string copperfin_runtime_bridge_posix_environment_key(const std::string& entry) {\n";
    stream << "    const std::size_t separator = entry.find('=');\n";
    stream << "    return separator == std::string::npos ? entry : entry.substr(0U, separator);\n";
    stream << "}\n\n";
    stream << "static std::vector<std::string> copperfin_runtime_bridge_posix_environment(\n";
    stream << "    const std::vector<CopperfinRuntimeBridgeEnvironmentVariable>& overrides) {\n";
    stream << "    // Direct environ mutation must use the same external process-wide serialization contract.\n";
    stream << "    static std::mutex environment_mutex;\n";
    stream << "    const std::lock_guard<std::mutex> environment_lock(environment_mutex);\n";
    stream << "    std::vector<std::string> entries;\n";
    stream << "    for (char** current = environ; current != nullptr && *current != nullptr; ++current) {\n";
    stream << "        const std::string entry(*current);\n";
    stream << "        const std::string key = copperfin_runtime_bridge_posix_environment_key(entry);\n";
    stream << "        bool replaced = false;\n";
    stream << "        for (auto& existing : entries) {\n";
    stream << "            if (copperfin_runtime_bridge_posix_environment_key(existing) == key) {\n";
    stream << "                existing = entry;\n";
    stream << "                replaced = true;\n";
    stream << "            }\n";
    stream << "        }\n";
    stream << "        if (!replaced) {\n";
    stream << "            entries.push_back(entry);\n";
    stream << "        }\n";
    stream << "    }\n";
    stream << "    for (const auto& override_value : overrides) {\n";
    stream << "        const std::string prefix = override_value.name + \"=\";\n";
    stream << "        const std::string replacement = prefix + override_value.value;\n";
    stream << "        bool replaced = false;\n";
    stream << "        for (auto& entry : entries) {\n";
    stream << "            if (entry.compare(0U, prefix.size(), prefix) == 0) {\n";
    stream << "                entry = replacement;\n";
    stream << "                replaced = true;\n";
    stream << "            }\n";
    stream << "        }\n";
    stream << "        if (!replaced) {\n";
    stream << "            entries.push_back(replacement);\n";
    stream << "        }\n";
    stream << "    }\n";
    stream << "    return entries;\n";
    stream << "}\n\n";
    stream << "#endif\n\n";
    stream << "static CopperfinRuntimeBridgeProcessLaunch copperfin_runtime_bridge_launch_process(\n";
    stream << "    const CopperfinRuntimeBridgeDispatchExecution& dispatch_execution);\n\n";
    stream << "#if defined(COPPERFIN_RUNTIME_BRIDGE_TEST_HOOKS)\n";
    stream << "COPPERFIN_EXPORT int copperfin_runtime_bridge_test_launch_environment(\n";
    stream << "    const char* executable_path,\n";
    stream << "    const char* output_path,\n";
    stream << "    const char* working_directory,\n";
    stream << "    const char* override_name,\n";
    stream << "    const char* override_value,\n";
    stream << "    const char* argument) {\n";
    stream << "    if (executable_path == nullptr || output_path == nullptr || working_directory == nullptr ||\n";
    stream << "        override_name == nullptr || override_value == nullptr || argument == nullptr) {\n";
    stream << "        return -1;\n";
    stream << "    }\n";
    stream << "    if (std::string(argument) == \"--copperfin-verify-runtime-host\") {\n";
#if defined(_WIN32)
    stream << "        HANDLE verified_host = INVALID_HANDLE_VALUE;\n";
    stream << "        const bool verified = copperfin_runtime_bridge_read_verified_host(\n";
    stream << "            std::filesystem::path(executable_path), std::filesystem::path(output_path), verified_host);\n";
    stream << "        if (verified_host != INVALID_HANDLE_VALUE) {\n";
    stream << "            CloseHandle(verified_host);\n";
    stream << "        }\n";
#else
    stream << "        int verified_host = -1;\n";
    stream << "        const bool verified = copperfin_runtime_bridge_read_verified_host(\n";
    stream << "            std::filesystem::path(executable_path), std::filesystem::path(output_path), verified_host);\n";
    stream << "        if (verified_host >= 0) {\n";
    stream << "            close(verified_host);\n";
    stream << "        }\n";
#endif
    stream << "        return verified ? 0 : -1;\n";
    stream << "    }\n";
    stream << "    std::vector<std::string> arguments;\n";
    stream << "    if (*argument != '\\0') {\n";
    stream << "        arguments.emplace_back(argument);\n";
    stream << "    }\n";
    stream << "    std::vector<CopperfinRuntimeBridgeEnvironmentVariable> overrides;\n";
    stream << "    if (*override_name != '\\0') {\n";
    stream << "        overrides.push_back({override_name, override_value});\n";
    stream << "    }\n";
    stream << "    const CopperfinRuntimeBridgeDispatchExecution dispatch_execution{\n";
    stream << "        std::filesystem::path(executable_path),\n";
    stream << "        {},\n";
    stream << "        std::move(arguments),\n";
    stream << "        std::filesystem::path(working_directory),\n";
    stream << "        std::move(overrides),\n";
    stream << "        std::filesystem::path(output_path),\n";
    stream << "        {},\n";
    stream << "        true,\n";
    stream << "        false,\n";
    stream << "        0,\n";
    stream << "        false};\n";
    stream << "    const auto launch = copperfin_runtime_bridge_launch_process(dispatch_execution);\n";
    stream << "    return launch.launch_succeeded ? launch.exit_code : -1;\n";
    stream << "}\n";
    stream << "#endif\n";
    stream << "static CopperfinRuntimeBridgeProcessLaunch copperfin_runtime_bridge_launch_process(\n";
    stream << "    const CopperfinRuntimeBridgeDispatchExecution& dispatch_execution) {\n";
    stream << "    const bool launch_attempted = !dispatch_execution.executable_path.empty();\n";
    stream << "    int exit_code = -1;\n";
    stream << "    bool process_created = false;\n";
    stream << "#if defined(_WIN32)\n";
    stream << "    HANDLE verified_runtime_host = INVALID_HANDLE_VALUE;\n";
    stream << "    const bool runtime_host_verified = !dispatch_execution.verify_runtime_host ||\n";
    stream << "        copperfin_runtime_bridge_read_verified_host(\n";
    stream << "            dispatch_execution.executable_path,\n";
    stream << "            dispatch_execution.manifest_path,\n";
    stream << "            verified_runtime_host);\n";
    stream << "    const auto executable = copperfin_runtime_bridge_utf8_to_wide(copperfin_runtime_bridge_path_to_utf8_string(dispatch_execution.executable_path));\n";
    stream << "    std::wstring command_line = copperfin_runtime_bridge_quote_windows_argument(executable);\n";
    stream << "    for (const auto& argument : dispatch_execution.arguments) {\n";
    stream << "        command_line.push_back(L' ');\n";
    stream << "        command_line += copperfin_runtime_bridge_quote_windows_argument(copperfin_runtime_bridge_utf8_to_wide(argument));\n";
    stream << "    }\n";
    stream << "    std::vector<wchar_t> mutable_command_line(command_line.begin(), command_line.end());\n";
    stream << "    mutable_command_line.push_back(L'\\0');\n";
    stream << "    const auto environment_entries = copperfin_runtime_bridge_windows_environment(dispatch_execution.environment);\n";
    stream << "    std::vector<wchar_t> environment_block;\n";
    stream << "    for (const auto& entry : environment_entries) {\n";
    stream << "        environment_block.insert(environment_block.end(), entry.begin(), entry.end());\n";
    stream << "        environment_block.push_back(L'\\0');\n";
    stream << "    }\n";
    stream << "    environment_block.push_back(L'\\0');\n";
    stream << "    if (environment_entries.empty()) {\n";
    stream << "        environment_block.push_back(L'\\0');\n";
    stream << "    }\n";
    stream << "    SECURITY_ATTRIBUTES security_attributes{};\n";
    stream << "    security_attributes.nLength = sizeof(security_attributes);\n";
    stream << "    security_attributes.bInheritHandle = FALSE;\n";
    stream << "    const auto open_log = [&](const std::filesystem::path& path, bool capture) {\n";
    stream << "        if (!capture || path.empty()) {\n";
    stream << "            return static_cast<HANDLE>(nullptr);\n";
    stream << "        }\n";
    stream << "        return CreateFileW(path.c_str(), GENERIC_WRITE, FILE_SHARE_READ | FILE_SHARE_WRITE, &security_attributes, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);\n";
    stream << "    };\n";
    stream << "    HANDLE stdout_handle = open_log(dispatch_execution.stdout_log_path, dispatch_execution.capture_stdout);\n";
    stream << "    HANDLE stderr_handle = open_log(dispatch_execution.stderr_log_path, dispatch_execution.capture_stderr);\n";
    stream << "    const bool log_handles_valid =\n";
    stream << "        (!dispatch_execution.capture_stdout || dispatch_execution.stdout_log_path.empty() || stdout_handle != INVALID_HANDLE_VALUE) &&\n";
    stream << "        (!dispatch_execution.capture_stderr || dispatch_execution.stderr_log_path.empty() || stderr_handle != INVALID_HANDLE_VALUE);\n";
    stream << "    if (runtime_host_verified && log_handles_valid && !executable.empty()) {\n";
    stream << "        const auto is_real_handle = [](HANDLE handle) {\n";
    stream << "            return handle != nullptr && handle != INVALID_HANDLE_VALUE;\n";
    stream << "        };\n";
    stream << "        const HANDLE standard_input_handle = GetStdHandle(STD_INPUT_HANDLE);\n";
    stream << "        const HANDLE standard_output_handle = stdout_handle == nullptr ? GetStdHandle(STD_OUTPUT_HANDLE) : stdout_handle;\n";
    stream << "        const HANDLE standard_error_handle = stderr_handle == nullptr ? GetStdHandle(STD_ERROR_HANDLE) : stderr_handle;\n";
    stream << "        std::vector<HANDLE> duplicated_standard_handles;\n";
    stream << "        const auto duplicate_for_child = [&](HANDLE source) {\n";
    stream << "            if (!is_real_handle(source)) {\n";
    stream << "                return static_cast<HANDLE>(nullptr);\n";
    stream << "            }\n";
    stream << "            HANDLE duplicate = nullptr;\n";
    stream << "            if (!DuplicateHandle(GetCurrentProcess(), source, GetCurrentProcess(), &duplicate, 0, TRUE, DUPLICATE_SAME_ACCESS) ||\n";
    stream << "                SetHandleInformation(duplicate, HANDLE_FLAG_INHERIT, HANDLE_FLAG_INHERIT) == FALSE) {\n";
    stream << "                if (duplicate != nullptr) {\n";
    stream << "                    CloseHandle(duplicate);\n";
    stream << "                }\n";
    stream << "                return static_cast<HANDLE>(nullptr);\n";
    stream << "            }\n";
    stream << "            duplicated_standard_handles.push_back(duplicate);\n";
    stream << "            return duplicate;\n";
    stream << "        };\n";
    stream << "        const HANDLE child_input_handle = duplicate_for_child(standard_input_handle);\n";
    stream << "        const HANDLE child_output_handle = duplicate_for_child(standard_output_handle);\n";
    stream << "        const HANDLE child_error_handle = duplicate_for_child(standard_error_handle);\n";
    stream << "        const bool standard_handles_ready =\n";
    stream << "            (!is_real_handle(standard_input_handle) || child_input_handle != nullptr) &&\n";
    stream << "            (!is_real_handle(standard_output_handle) || child_output_handle != nullptr) &&\n";
    stream << "            (!is_real_handle(standard_error_handle) || child_error_handle != nullptr);\n";
    stream << "        std::vector<HANDLE> inherited_handles;\n";
    stream << "        if (child_input_handle != nullptr) {\n";
    stream << "            inherited_handles.push_back(child_input_handle);\n";
    stream << "        }\n";
    stream << "        if (child_output_handle != nullptr) {\n";
    stream << "            inherited_handles.push_back(child_output_handle);\n";
    stream << "        }\n";
    stream << "        if (child_error_handle != nullptr) {\n";
    stream << "            inherited_handles.push_back(child_error_handle);\n";
    stream << "        }\n";
    stream << "        SIZE_T attribute_list_size = 0U;\n";
    stream << "        std::vector<unsigned char> attribute_storage;\n";
    stream << "        PPROC_THREAD_ATTRIBUTE_LIST attribute_list = nullptr;\n";
    stream << "        bool attribute_list_initialized = false;\n";
    stream << "        bool restricted_handle_list_ready = inherited_handles.empty();\n";
    stream << "        if (!inherited_handles.empty()) {\n";
    stream << "            InitializeProcThreadAttributeList(nullptr, 1U, 0U, &attribute_list_size);\n";
    stream << "            attribute_storage.resize(attribute_list_size);\n";
    stream << "            attribute_list = reinterpret_cast<PPROC_THREAD_ATTRIBUTE_LIST>(attribute_storage.data());\n";
    stream << "            attribute_list_initialized = attribute_list_size > 0U &&\n";
    stream << "                InitializeProcThreadAttributeList(attribute_list, 1U, 0U, &attribute_list_size) != FALSE;\n";
    stream << "            restricted_handle_list_ready = attribute_list_initialized &&\n";
    stream << "                UpdateProcThreadAttribute(attribute_list, 0U, PROC_THREAD_ATTRIBUTE_HANDLE_LIST,\n";
    stream << "                    inherited_handles.data(), inherited_handles.size() * sizeof(HANDLE), nullptr, nullptr) != FALSE;\n";
    stream << "        }\n";
    stream << "        STARTUPINFOEXW startup_info{};\n";
    stream << "        startup_info.StartupInfo.cb = restricted_handle_list_ready && !inherited_handles.empty()\n";
    stream << "            ? sizeof(startup_info)\n";
    stream << "            : sizeof(startup_info.StartupInfo);\n";
    stream << "        startup_info.StartupInfo.dwFlags = STARTF_USESTDHANDLES;\n";
    stream << "        startup_info.StartupInfo.hStdInput = child_input_handle;\n";
    stream << "        startup_info.StartupInfo.hStdOutput = child_output_handle;\n";
    stream << "        startup_info.StartupInfo.hStdError = child_error_handle;\n";
    stream << "        if (restricted_handle_list_ready && !inherited_handles.empty()) {\n";
    stream << "            startup_info.lpAttributeList = attribute_list;\n";
    stream << "        }\n";
    stream << "        PROCESS_INFORMATION process_info{};\n";
    stream << "        const auto working_directory = dispatch_execution.working_directory.empty()\n";
    stream << "            ? std::wstring{}\n";
    stream << "            : dispatch_execution.working_directory.wstring();\n";
    stream << "        const DWORD creation_flags = CREATE_UNICODE_ENVIRONMENT |\n";
    stream << "            (restricted_handle_list_ready && !inherited_handles.empty() ? EXTENDED_STARTUPINFO_PRESENT : 0U);\n";
    stream << "        process_created = standard_handles_ready && restricted_handle_list_ready && CreateProcessW(\n";
    stream << "            nullptr,\n";
    stream << "            mutable_command_line.data(),\n";
    stream << "            nullptr,\n";
    stream << "            nullptr,\n";
    stream << "            !inherited_handles.empty(),\n";
    stream << "            creation_flags,\n";
    stream << "            environment_block.data(),\n";
    stream << "            working_directory.empty() ? nullptr : working_directory.c_str(),\n";
    stream << "            &startup_info.StartupInfo,\n";
    stream << "            &process_info) != FALSE;\n";
    stream << "        if (attribute_list_initialized) {\n";
    stream << "            DeleteProcThreadAttributeList(attribute_list);\n";
    stream << "        }\n";
    stream << "        if (process_created) {\n";
    stream << "            WaitForSingleObject(process_info.hProcess, INFINITE);\n";
    stream << "            DWORD process_exit_code = static_cast<DWORD>(-1);\n";
    stream << "            GetExitCodeProcess(process_info.hProcess, &process_exit_code);\n";
    stream << "            exit_code = static_cast<int>(process_exit_code);\n";
    stream << "            CloseHandle(process_info.hThread);\n";
    stream << "            CloseHandle(process_info.hProcess);\n";
    stream << "        }\n";
    stream << "        for (const HANDLE handle : duplicated_standard_handles) {\n";
    stream << "            CloseHandle(handle);\n";
    stream << "        }\n";
    stream << "    }\n";
    stream << "    if (stdout_handle != nullptr && stdout_handle != INVALID_HANDLE_VALUE) {\n";
    stream << "        CloseHandle(stdout_handle);\n";
    stream << "    }\n";
    stream << "    if (stderr_handle != nullptr && stderr_handle != INVALID_HANDLE_VALUE) {\n";
    stream << "        CloseHandle(stderr_handle);\n";
    stream << "    }\n";
    stream << "    if (verified_runtime_host != INVALID_HANDLE_VALUE) {\n";
    stream << "        CloseHandle(verified_runtime_host);\n";
    stream << "    }\n";
    stream << "#else\n";
    stream << "    int verified_runtime_host = -1;\n";
    stream << "    const bool runtime_host_verified = !dispatch_execution.verify_runtime_host ||\n";
    stream << "        copperfin_runtime_bridge_read_verified_host(\n";
    stream << "            dispatch_execution.executable_path,\n";
    stream << "            dispatch_execution.manifest_path,\n";
    stream << "            verified_runtime_host);\n";
    stream << "    std::vector<std::string> argument_values;\n";
    stream << "    argument_values.reserve(dispatch_execution.arguments.size() + 1U);\n";
    stream << "    argument_values.push_back(copperfin_runtime_bridge_path_to_utf8_string(dispatch_execution.executable_path));\n";
    stream << "    argument_values.insert(argument_values.end(), dispatch_execution.arguments.begin(), dispatch_execution.arguments.end());\n";
    stream << "    std::vector<char*> argument_values_pointers;\n";
    stream << "    argument_values_pointers.reserve(argument_values.size() + 1U);\n";
    stream << "    for (auto& argument : argument_values) {\n";
    stream << "        argument_values_pointers.push_back(argument.data());\n";
    stream << "    }\n";
    stream << "    argument_values_pointers.push_back(nullptr);\n";
    stream << "    const auto environment_values = copperfin_runtime_bridge_posix_environment(dispatch_execution.environment);\n";
    stream << "    std::vector<char*> environment_value_pointers;\n";
    stream << "    environment_value_pointers.reserve(environment_values.size() + 1U);\n";
    stream << "    for (const auto& environment_value : environment_values) {\n";
    stream << "        environment_value_pointers.push_back(const_cast<char*>(environment_value.c_str()));\n";
    stream << "    }\n";
    stream << "    environment_value_pointers.push_back(nullptr);\n";
    stream << "    const pid_t child_process = runtime_host_verified ? fork() : static_cast<pid_t>(-1);\n";
    stream << "    if (child_process == 0) {\n";
    stream << "        if (!dispatch_execution.working_directory.empty() && chdir(dispatch_execution.working_directory.c_str()) != 0) {\n";
    stream << "            _exit(126);\n";
    stream << "        }\n";
    stream << "        const auto redirect_output = [&](const std::filesystem::path& path, bool capture, int descriptor) {\n";
    stream << "            if (!capture || path.empty()) {\n";
    stream << "                return true;\n";
    stream << "            }\n";
    stream << "            const int file_descriptor = open(path.c_str(), O_WRONLY | O_CREAT | O_TRUNC, 0666);\n";
    stream << "            if (file_descriptor < 0 || dup2(file_descriptor, descriptor) < 0) {\n";
    stream << "                if (file_descriptor >= 0) {\n";
    stream << "                    close(file_descriptor);\n";
    stream << "                }\n";
    stream << "                return false;\n";
    stream << "            }\n";
    stream << "            close(file_descriptor);\n";
    stream << "            return true;\n";
    stream << "        };\n";
    stream << "        if (!redirect_output(dispatch_execution.stdout_log_path, dispatch_execution.capture_stdout, STDOUT_FILENO) ||\n";
    stream << "            !redirect_output(dispatch_execution.stderr_log_path, dispatch_execution.capture_stderr, STDERR_FILENO)) {\n";
    stream << "            _exit(126);\n";
    stream << "        }\n";
    stream << "#if defined(__linux__)\n";
    stream << "        if (dispatch_execution.verify_runtime_host) {\n";
    stream << "            fexecve(verified_runtime_host, argument_values_pointers.data(), environment_value_pointers.data());\n";
    stream << "        } else {\n";
    stream << "            execve(argument_values_pointers[0], argument_values_pointers.data(), environment_value_pointers.data());\n";
    stream << "        }\n";
    stream << "#else\n";
    stream << "        execve(argument_values_pointers[0], argument_values_pointers.data(), environment_value_pointers.data());\n";
    stream << "#endif\n";
    stream << "        _exit(127);\n";
    stream << "    }\n";
    stream << "    if (verified_runtime_host >= 0) {\n";
    stream << "        close(verified_runtime_host);\n";
    stream << "    }\n";
    stream << "    if (child_process > 0) {\n";
    stream << "        int child_status = 0;\n";
    stream << "        pid_t waited_process = 0;\n";
    stream << "        do {\n";
    stream << "            waited_process = waitpid(child_process, &child_status, 0);\n";
    stream << "        } while (waited_process < 0 && errno == EINTR);\n";
    stream << "        if (waited_process == child_process && WIFEXITED(child_status)) {\n";
    stream << "            exit_code = WEXITSTATUS(child_status);\n";
    stream << "            process_created = true;\n";
    stream << "        } else if (waited_process == child_process && WIFSIGNALED(child_status)) {\n";
    stream << "            exit_code = 128 + WTERMSIG(child_status);\n";
    stream << "            process_created = true;\n";
    stream << "        }\n";
    stream << "    }\n";
    stream << "#endif\n";
    stream << "    const bool launch_succeeded = launch_attempted && process_created && exit_code == dispatch_execution.expected_exit_code;\n";
    stream << "    return CopperfinRuntimeBridgeProcessLaunch{\n";
    stream << "        dispatch_execution.executable_path,\n";
    stream << "        dispatch_execution.arguments,\n";
    stream << "        dispatch_execution.working_directory,\n";
    stream << "        dispatch_execution.environment,\n";
    stream << "        dispatch_execution.stdout_log_path,\n";
    stream << "        dispatch_execution.stderr_log_path,\n";
    stream << "        dispatch_execution.capture_stdout,\n";
    stream << "        dispatch_execution.capture_stderr,\n";
    stream << "        launch_attempted,\n";
    stream << "        launch_succeeded,\n";
    stream << "        exit_code,\n";
    stream << "        dispatch_execution.expected_exit_code};\n";
    stream << "}\n\n";
}

}  // namespace runtime_pipeline_detail

}  // namespace copperfin::runtime
