# Copyright © 2026 Richard M. Hamilton.
# SPDX-License-Identifier: GPL-3.0-only
# Additional permission: Copperfin Application, Runtime, and Toolchain Exception 1.0; see LICENSE.

if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SOURCE_DIR is required")
endif()
file(READ "${SOURCE_DIR}/include/copperfin/platform/printer.h" boundary_header)
file(READ "${SOURCE_DIR}/src/platform/printer.cpp" platform_source)
file(READ "${SOURCE_DIR}/src/runtime/prg_engine_variables.inl" runtime_source)
file(READ "${SOURCE_DIR}/CMakeLists.txt" root_build)
file(READ "${SOURCE_DIR}/.github/workflows/generated-launcher-validation.yml" workflow)

function(require_text contents expected description)
    string(FIND "${contents}" "${expected}" offset)
    if(offset EQUAL -1)
        message(FATAL_ERROR "Missing ${description}: ${expected}")
    endif()
endfunction()
function(forbid_text contents forbidden description)
    string(FIND "${contents}" "${forbidden}" offset)
    if(NOT offset EQUAL -1)
        message(FATAL_ERROR "Forbidden ${description}: ${forbidden}")
    endif()
endfunction()

foreach(token IN ITEMS "_WIN32" "windows.h" "winspool.h" "EnumPrinters" "popen" "lpstat")
    forbid_text("${boundary_header}" "${token}" "native token in portable printer API")
endforeach()
require_text("${boundary_header}" "std::vector<std::string> enumerate_printer_names();" "portable printer declaration")
foreach(token IN ITEMS "::EnumPrintersW(" "PRINTER_ENUM_LOCAL | PRINTER_ENUM_CONNECTIONS" "run_bounded_process(request)" "request.arguments = {argument};")
    require_text("${platform_source}" "${token}" "shell-free platform implementation")
endforeach()
foreach(token IN ITEMS "popen(" "_popen(" "pclose(" "_pclose(" "std::system(" " 2>/dev/null" " 2>NUL")
    forbid_text("${platform_source}" "${token}" "command-shell printer discovery")
    forbid_text("${runtime_source}" "${token}" "command-shell runtime printer discovery")
endforeach()
require_text("${runtime_source}" "copperfin::platform::enumerate_printer_names();" "runtime portable printer use")
require_text("${root_build}" "src/platform/printer.cpp" "printer build source")
require_text("${root_build}" "target_link_libraries(cf_platform_profile PRIVATE winspool)" "private spooler linkage")
require_text("${workflow}" "test_printer_shell_boundary_contract" "hosted boundary scheduling")
