# Copyright © 2026 Richard M. Hamilton.
# SPDX-License-Identifier: GPL-3.0-only
# Additional permission: Copperfin Application, Runtime, and Toolchain Exception 1.0; see LICENSE.
# Traceability: RQ-CF-REL-003; DQ-windows-vsix-lifecycle-scope;
# DV-windows-vsix-lifecycle-contract; HZ-system-failure-01;
# HZ-data-corruption-01; HZ-doc-command-01.

if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SOURCE_DIR is required")
endif()

function(require_text relative_path expected_text description)
    file(STRINGS "${SOURCE_DIR}/${relative_path}" lines)
    set(found FALSE)
    foreach(line IN LISTS lines)
        string(FIND "${line}" "${expected_text}" match_index)
        if(NOT match_index EQUAL -1)
            set(found TRUE)
            break()
        endif()
    endforeach()
    if(NOT found)
        message(FATAL_ERROR "${relative_path} is missing ${description}")
    endif()
endfunction()

set(script "scripts/test-windows-vsix-lifecycle.ps1")
set(workflow ".github/workflows/build-vsix.yml")
set(driver "tests/vsix/Copperfin.VisualStudio.LifecycleDriver/LifecycleDriverPackage.cs")
set(driver_project "tests/vsix/Copperfin.VisualStudio.LifecycleDriver/Copperfin.VisualStudio.LifecycleDriver.csproj")
foreach(path IN ITEMS
        ${script}
        ${workflow}
        ${driver}
        scripts/assemble-rc-candidate.py
        tests/run_windows_vsix_lifecycle_contract_check.cmake)
    foreach(id IN ITEMS RQ-CF-REL-003 DQ-windows-vsix-lifecycle-scope
            DV-windows-vsix-lifecycle-contract HZ-system-failure-01
            HZ-data-corruption-01 HZ-doc-command-01)
        require_text("${path}" "${id}" "reverse traceability to ${id}")
    endforeach()
endforeach()

require_text("${script}" "[ValidateRange(30, 600)]" "bounded process timeout")
require_text("${script}" "ProcessTimeoutSeconds = 360" "bounded IDE and helper allowance")
require_text("${script}" "InstallerTimeoutSeconds = 600" "separate bounded hosted installer allowance")
require_text("${script}" "DriverVsixPath" "separate test-only lifecycle-driver input")
require_text("${script}" "Copperfin.VisualStudio.LifecycleDriver" "exact lifecycle-driver identity")
require_text("${script}" "TimeoutSeconds * 1000" "bounded child-process wait")
require_text("${script}" "Kill($true)" "timed-out process-tree termination")
require_text("${script}" "-requires Microsoft.VisualStudio.Component.CoreEditor" "Visual Studio component selection")
require_text("${script}" "\"/instanceIds:$instanceId\"" "exact Visual Studio instance targeting")
require_text("${script}" "'/quiet', \"/instanceIds:$instanceId\"" "noninteractive instance-scoped VSIX operation")
require_text("${script}" "installationVersion -match" "version-independent Visual Studio profile selection")
require_text("${script}" "Copperfin VSIX is already installed" "clean-runner precondition")
require_text("${script}" "'/updateconfiguration'" "post-install package-registration refresh")
require_text("${script}" "ActivityLog-registration.xml" "retained package-registration prime log")
require_text("${script}" "Importing pkgdef file" "installed pkgdef import proof")
require_text("${script}" "OrdinalIgnoreCase" "Windows path identity comparison")
require_text("${script}" "registrationProcess.WaitForInputIdle(30000)" "bounded registration-prime input readiness")
require_text("${script}" "registrationProcess.WaitForExit(15000)" "bounded registration-prime shutdown")
require_text("${script}" "registration-prime process did not exit after the bounded close request" "graceful-close fallback diagnostic")
require_text("${script}" "registration-prime process tree did not terminate" "fail-closed registration-prime cleanup")
require_text("${script}" "Copperfin Command" "representative installed command")
require_text("${script}" "MainWindowHandle" "bounded IDE readiness observation")
require_text("${script}" "UIAutomationClient" "Windows UI Automation evidence boundary")
require_text("${script}" "ProcessIdProperty, $ExpectedProcessId" "launched-process UI identity binding")
require_text("${script}" "Copperfin.ShowCommandWindow" "registered canonical command identity")
require_text("${script}" "COPPERFIN_VSIX_LIFECYCLE_DRIVER_RESULT" "evidence-process-only driver result boundary")
require_text("${script}" "COPPERFIN_VSIX_LIFECYCLE_DRIVER_PRG" "runner-owned PRG driver boundary")
require_text("${script}" "COPPERFIN_VSIX_LIFECYCLE_DRIVER_SOLUTION" "runner-owned solution driver boundary")
require_text("${script}" "lifecycle-driver.sln" "runner-owned empty solution fixture")
require_text("${script}" "await test-only in-process driver dispatch" "bounded in-process dispatch boundary")
require_text("${script}" "command_post_hresult" "machine-readable command-post result")
require_text("${script}" "driver_uninstall" "test-only driver cleanup operation")
require_text("${driver}" "ProvideAutoLoad(UIContextGuids80.SolutionExists, PackageAutoLoadFlags.BackgroundLoad)" "loaded-solution in-process driver activation")
require_text("${driver}" "solution_identity_verified" "exact solution identity proof")
require_text("${driver}" "PostExecCommand" "public Visual Studio command-service dispatch")
require_text("${driver}" "Microsoft.VisualStudio.OLE.Interop" "command execution option namespace")
require_text("${driver}" "4b56ff76-d352-4027-bb18-ef4c759d260b" "exact Copperfin command group")
require_text("${driver}" "ShowCommandWindowId = 0x0300" "exact Copperfin command ID")
require_text("${driver}" "ItemOperations.OpenFile" "in-process runner-owned PRG request")
require_text("${driver_project}" "<DeployVSTemplates>false</DeployVSTemplates>" "test driver non-template package boundary")
require_text("${driver_project}" "<TemplateOutputDirectory>" "VSSDK template-manifest output boundary")
require_text("${script}" "ui-automation-command.json" "retained command-observation diagnostics")
require_text("${script}" "ui-automation-prg.json" "retained PRG-observation diagnostics")
require_text("${script}" "StartsWith(\"$ExpectedName - \"" "exact active-document window-title boundary")
require_text("${script}" "Exact runner-owned PRG document tab" "exact PRG-open proof")
require_text("${script}" "'/NoSplash', '/Log', $activityLog" "controlled evidence IDE launch")
require_text("${script}" "Registered Copperfin Command surface" "same-process command-surface proof")
require_text("${script}" "Kill($true)" "bounded process-tree termination")
require_text("${script}" "lifecycle-smoke.prg" "runner-owned PRG open fixture")
require_text("${script}" "End package load [CopperfinPackage]" "explicit successful package-load proof")
require_text("${script}" "MatchingErrors.Count -eq 0" "Copperfin package-load error rejection")
require_text("${script}" "$primaryFailure = $_" "primary lifecycle failure preservation")
require_text("${script}" "Cleanup also failed" "cleanup failure aggregation")
require_text("${script}" "Residue inventory also failed" "residue-inventory failure aggregation")
require_text("${script}" "'/uninstall:Copperfin.VisualStudio'" "exact extension uninstall identity")
require_text("${script}" "vsix-installer-operations.json" "retained installer operation diagnostics")
require_text("${script}" "vsix_sha256 = $vsixSha256" "installer diagnostic package-digest binding")
require_text("${script}" "Discovered an installed Copperfin extension during failure cleanup" "post-failure residue discovery")
require_text("${script}" "same_version_reinstall = 'NOT_RUN'" "honest maintenance limitation")
require_text("${script}" "upgrade_from_previous_version = 'NOT_RUN'" "honest upgrade limitation")
require_text("${script}" "disablement = 'NOT_RUN'" "honest disablement limitation")
require_text("${script}" "WorkingDirectory = $resolvedEvidenceDirectory" "checkout-independent IDE working directory")
require_text("${script}" "development_checkout_dependency = 'PASS'" "checkout-independence evidence")
require_text("${script}" "windows-vsix-lifecycle.json" "machine-readable retained evidence")
require_text("${workflow}" "workflow_dispatch:" "manual exact-head validation trigger")
require_text("${workflow}" "runs-on: windows-2022" "stable VSSDK-17 lifecycle host")
require_text("${workflow}" "Exercise Windows VSIX lifecycle" "hosted lifecycle step")
require_text("${workflow}" "/nodeReuse:false" "MSBuild descendant shutdown before installation")
require_text("${workflow}" "windows-vsix-lifecycle.json" "retained lifecycle evidence upload")
require_text("${workflow}" "ActivityLog-registration.xml" "retained registration-prime diagnostics")
require_text("${workflow}" "vsix-installer-operations.json" "retained installer operation diagnostics")
require_text("${workflow}" "Copperfin.VisualStudio.LifecycleDriver.csproj" "test-only lifecycle-driver build")
require_text("${workflow}" "-DriverVsixPath" "test-only lifecycle-driver handoff")
require_text("${workflow}" "vsix-lifecycle-driver.json" "retained in-process dispatch diagnostics")
require_text("${workflow}" "ui-automation-command.json" "retained command UI Automation diagnostics")
require_text("${workflow}" "ui-automation-prg.json" "retained PRG UI Automation diagnostics")
require_text("${workflow}" "Upload Windows VSIX lifecycle diagnostics" "retained failure diagnostics")
require_text("${workflow}" "always()" "failure-path evidence staging")
file(READ "${SOURCE_DIR}/${script}" script_contents)
string(FIND "${script_contents}" "VSIX lifecycle phase: prime per-user package registration" registration_phase_offset)
string(FIND "${script_contents}" "matchingPkgDefImports.Count -ge 1" registration_proof_offset)
string(FIND "${script_contents}" "VSIX lifecycle phase: launch evidence Visual Studio" launch_phase_offset)
string(FIND "${script_contents}" "VSIX lifecycle phase: await test-only in-process driver dispatch" command_submission_offset)
string(FIND "${script_contents}" "Copperfin canonical command UI Automation observation" command_observation_offset)
if(command_observation_offset EQUAL -1)
    string(FIND "${script_contents}" "Copperfin command-surface UI Automation observation" command_observation_offset)
endif()
string(FIND "${script_contents}" "Copperfin startup PRG document UI Automation observation" document_observation_offset)
if(registration_phase_offset EQUAL -1 OR registration_proof_offset EQUAL -1 OR
        launch_phase_offset EQUAL -1 OR command_submission_offset EQUAL -1 OR
        command_observation_offset EQUAL -1 OR
        document_observation_offset EQUAL -1 OR
        NOT registration_phase_offset LESS registration_proof_offset OR
        NOT registration_proof_offset LESS launch_phase_offset OR
        NOT launch_phase_offset LESS command_submission_offset OR
        NOT command_submission_offset LESS command_observation_offset OR
        NOT command_observation_offset LESS document_observation_offset)
    message(FATAL_ERROR "registration priming, evidence startup, command dispatch, and same-process observations must remain ordered")
endif()
file(READ "${SOURCE_DIR}/${workflow}" workflow_contents)
string(FIND "${workflow_contents}" "Exercise Windows VSIX lifecycle" lifecycle_offset)
string(FIND "${workflow_contents}" "Run managed VSIX behavior tests" managed_test_offset)
if(lifecycle_offset EQUAL -1 OR managed_test_offset EQUAL -1 OR
        NOT lifecycle_offset LESS managed_test_offset)
    message(FATAL_ERROR "VSIX lifecycle must run before managed test processes can remain")
endif()
require_text("scripts/assemble-rc-candidate.py" "require_windows_vsix_lifecycle_evidence" "fail-closed RC evidence ingestion")
require_text("docs/contracts/rc-validation-manifest-v3.schema.json" "windows_disablement" "manifest disablement field")

find_program(POWERSHELL_EXECUTABLE NAMES pwsh)
if(POWERSHELL_EXECUTABLE)
    execute_process(COMMAND "${POWERSHELL_EXECUTABLE}" -NoLogo -NoProfile
        -File "${SOURCE_DIR}/${script}" -SelfTest
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "VSIX lifecycle helper self-test failed (${result}):\n${stdout}\n${stderr}")
    endif()
endif()

message(STATUS "Windows VSIX lifecycle contract passed")
