# Copyright © 2026 Richard M. Hamilton.
# SPDX-License-Identifier: GPL-3.0-only
# Additional permission: Copperfin Application, Runtime, and Toolchain Exception 1.0; see LICENSE.

if(NOT DEFINED SOURCE_DIR OR "${SOURCE_DIR}" STREQUAL "")
    message(FATAL_ERROR "SOURCE_DIR is required")
endif()

set(contract_dir "${SOURCE_DIR}/docs/contracts")
set(schema_path "${contract_dir}/polyglot-migration-contract-v1.schema.json")
set(contract_path "${contract_dir}/polyglot-migration-contract-v1.json")
set(request_path "${contract_dir}/polyglot-invocation-request-v1.json")
set(success_path "${contract_dir}/polyglot-success-envelope-v1.json")
set(error_path "${contract_dir}/polyglot-error-envelope-v1.json")
set(invalid_path "${contract_dir}/polyglot-invalid-contract-v1.json")

foreach(required_path IN ITEMS
        "${schema_path}"
        "${contract_path}"
        "${request_path}"
        "${success_path}"
        "${error_path}"
        "${invalid_path}")
    if(NOT EXISTS "${required_path}")
        message(FATAL_ERROR "Polyglot contract fixture is missing: ${required_path}")
    endif()
endforeach()

function(read_json path out_variable)
    file(READ "${path}" contents)
    string(JSON root_type ERROR_VARIABLE parse_error TYPE "${contents}")
    if(parse_error OR NOT root_type STREQUAL "OBJECT")
        message(FATAL_ERROR "Polyglot JSON fixture is not a valid object: ${path}")
    endif()
    set(${out_variable} "${contents}" PARENT_SCOPE)
endfunction()

function(path_type_matches json expected out_variable)
    string(JSON actual ERROR_VARIABLE type_error TYPE "${json}" ${ARGN})
    if(type_error OR NOT actual STREQUAL "${expected}")
        set(${out_variable} FALSE PARENT_SCOPE)
    else()
        set(${out_variable} TRUE PARENT_SCOPE)
    endif()
endfunction()

function(path_value_matches json expression out_variable)
    string(JSON actual ERROR_VARIABLE value_error GET "${json}" ${ARGN})
    if(value_error OR NOT actual MATCHES "${expression}")
        set(${out_variable} FALSE PARENT_SCOPE)
    else()
        set(${out_variable} TRUE PARENT_SCOPE)
    endif()
endfunction()

function(sha256_value_matches json out_variable)
    string(JSON actual ERROR_VARIABLE value_error GET "${json}" ${ARGN})
    string(REGEX MATCH "^sha256:[0-9a-f]+$" matched "${actual}")
    string(LENGTH "${actual}" actual_length)
    if(value_error OR NOT matched OR NOT actual_length EQUAL 71)
        set(${out_variable} FALSE PARENT_SCOPE)
    else()
        set(${out_variable} TRUE PARENT_SCOPE)
    endif()
endfunction()

function(contract_shape_valid json out_variable)
    set(valid TRUE)

    path_value_matches("${json}" "^1\\.[0-9]+$" check contract_version)
    if(NOT check)
        set(valid FALSE)
    endif()
    path_value_matches("${json}" "^[0-9]+\\.[0-9]+\\.[0-9]+$" check protocol_version)
    if(NOT check)
        set(valid FALSE)
    endif()
    path_value_matches("${json}" "^[a-z][a-z0-9._-]*$" check capability_id)
    if(NOT check)
        set(valid FALSE)
    endif()

    foreach(envelope IN ITEMS input output error)
        path_type_matches("${json}" OBJECT check ${envelope})
        if(NOT check)
            set(valid FALSE)
        endif()
        path_type_matches("${json}" STRING check ${envelope} schema_id)
        if(NOT check)
            set(valid FALSE)
        endif()
        path_type_matches("${json}" STRING check ${envelope} content_type)
        if(NOT check)
            set(valid FALSE)
        endif()
    endforeach()

    path_type_matches("${json}" OBJECT check invocation)
    if(NOT check)
        set(valid FALSE)
    endif()
    path_value_matches("${json}" "^(allow|deny|require-audit)$" check invocation decision)
    if(NOT check)
        set(valid FALSE)
    endif()
    path_value_matches("${json}" "^[a-z][a-z0-9._-]*$" check invocation reason_code)
    if(NOT check)
        set(valid FALSE)
    endif()
    path_type_matches("${json}" BOOLEAN check invocation require_audit)
    if(NOT check)
        set(valid FALSE)
    endif()

    path_value_matches("${json}" "^[1-9][0-9]*$" check budget timeout_ms)
    if(NOT check)
        set(valid FALSE)
    endif()
    path_value_matches("${json}" "^[1-9][0-9]*$" check budget latency_budget_ms)
    if(NOT check)
        set(valid FALSE)
    endif()
    path_value_matches("${json}" "^(propagate|ignore)$" check budget cancellation)
    if(NOT check)
        set(valid FALSE)
    endif()

    path_value_matches("${json}" "^(fail-fast|fallback-native|fallback-artifact)$" check fallback mode)
    if(NOT check)
        set(valid FALSE)
    endif()
    path_value_matches("${json}" "^[0-9]+$" check fallback max_attempts)
    if(NOT check)
        set(valid FALSE)
    endif()

    path_value_matches("${json}" "^[a-z][a-z0-9._-]*$" check reproducibility runtime)
    if(NOT check)
        set(valid FALSE)
    endif()
    path_type_matches("${json}" STRING check reproducibility runtime_version)
    if(NOT check)
        set(valid FALSE)
    endif()
    sha256_value_matches("${json}" check reproducibility artifact_sha256)
    if(NOT check)
        set(valid FALSE)
    endif()
    sha256_value_matches("${json}" check reproducibility dependency_lock_sha256)
    if(NOT check)
        set(valid FALSE)
    endif()

    path_value_matches("${json}" "^[a-z][a-z0-9._-]*$" check observability event_namespace)
    if(NOT check)
        set(valid FALSE)
    endif()
    path_type_matches("${json}" ARRAY check observability events)
    if(NOT check)
        set(valid FALSE)
    endif()
    string(JSON event_count ERROR_VARIABLE event_error LENGTH "${json}" observability events)
    if(event_error OR event_count LESS 4)
        set(valid FALSE)
    endif()

    set(${out_variable} ${valid} PARENT_SCOPE)
endfunction()

function(envelope_shape_valid json expected_kind out_variable)
    set(valid TRUE)
    path_value_matches("${json}" "^1\\.0$" check envelope_version)
    if(NOT check)
        set(valid FALSE)
    endif()
    path_value_matches("${json}" "^${expected_kind}$" check kind)
    if(NOT check)
        set(valid FALSE)
    endif()
    path_value_matches("${json}" "^[a-z][a-z0-9._-]*$" check capability_id)
    if(NOT check)
        set(valid FALSE)
    endif()
    path_type_matches("${json}" STRING check correlation_id)
    if(NOT check)
        set(valid FALSE)
    endif()
    path_value_matches("${json}" "^[0-9]+\\.[0-9]+\\.[0-9]+$" check protocol_version)
    if(NOT check)
        set(valid FALSE)
    endif()
    if(expected_kind STREQUAL "success")
        path_type_matches("${json}" OBJECT check payload)
    else()
        path_type_matches("${json}" OBJECT check error)
        if(check)
            path_value_matches("${json}" "^[a-z][a-z0-9._-]*$" check error code)
        endif()
        if(check)
            path_type_matches("${json}" STRING check error message)
        endif()
        if(check)
            path_type_matches("${json}" BOOLEAN check error retryable)
        endif()
    endif()
    if(NOT check)
        set(valid FALSE)
    endif()
    set(${out_variable} ${valid} PARENT_SCOPE)
endfunction()

function(request_shape_valid json out_variable)
    set(valid TRUE)
    path_value_matches("${json}" "^1\\.0$" check envelope_version)
    if(NOT check)
        set(valid FALSE)
    endif()
    path_value_matches("${json}" "^invocation$" check kind)
    if(NOT check)
        set(valid FALSE)
    endif()
    path_value_matches("${json}" "^[a-z][a-z0-9._-]*$" check capability_id)
    if(NOT check)
        set(valid FALSE)
    endif()
    path_type_matches("${json}" STRING check correlation_id)
    if(NOT check)
        set(valid FALSE)
    else()
        string(JSON correlation_id GET "${json}" correlation_id)
        if(correlation_id STREQUAL "")
            set(valid FALSE)
        endif()
    endif()
    path_value_matches("${json}" "^[0-9]+\\.[0-9]+\\.[0-9]+$" check protocol_version)
    if(NOT check)
        set(valid FALSE)
    endif()
    path_type_matches("${json}" OBJECT check arguments)
    if(NOT check)
        set(valid FALSE)
    endif()
    set(${out_variable} ${valid} PARENT_SCOPE)
endfunction()

read_json("${schema_path}" schema_json)
read_json("${contract_path}" contract_json)
read_json("${request_path}" request_json)
read_json("${success_path}" success_json)
read_json("${error_path}" error_json)
read_json("${invalid_path}" invalid_json)

path_type_matches("${schema_json}" STRING check $schema)
if(NOT check)
    message(FATAL_ERROR "Polyglot schema must declare $schema")
endif()
path_type_matches("${schema_json}" OBJECT check $defs)
if(NOT check)
    message(FATAL_ERROR "Polyglot schema must declare reusable definitions")
endif()
string(JSON required_count ERROR_VARIABLE required_error LENGTH "${schema_json}" required)
if(required_error OR required_count LESS 11)
    message(FATAL_ERROR "Polyglot schema is missing required contract fields")
endif()

contract_shape_valid("${contract_json}" contract_valid)
if(NOT contract_valid)
    message(FATAL_ERROR "Polyglot Contract v1 example failed validation")
endif()
request_shape_valid("${request_json}" request_valid)
if(NOT request_valid)
    message(FATAL_ERROR "Polyglot invocation request example failed validation")
endif()
envelope_shape_valid("${success_json}" success success_valid)
if(NOT success_valid)
    message(FATAL_ERROR "Polyglot success envelope example failed validation")
endif()
envelope_shape_valid("${error_json}" error error_valid)
if(NOT error_valid)
    message(FATAL_ERROR "Polyglot error envelope example failed validation")
endif()
contract_shape_valid("${invalid_json}" invalid_valid)
if(invalid_valid)
    message(FATAL_ERROR "Invalid Polyglot Contract fixture unexpectedly passed validation")
endif()

message(STATUS "Polyglot Contract v1 schema and request/response examples passed; invalid fixture rejected")
