// Copyright © 2026 Richard M. Hamilton.
// SPDX-License-Identifier: GPL-3.0-only
// Additional permission: Copperfin Application, Runtime, and Toolchain Exception 1.0; see LICENSE.

#include "test_prg_engine_data_io_support.h"

using namespace cf_test_prg_engine_data_io;

int main() {
    test_scatter_memvar_from_current_record();
    test_scatter_gather_memvar_fields_blank_and_for_semantics();
    test_gather_memvar_preserves_fields_without_matching_variables();
    test_scatter_gather_memvar_single_name_field_filter_semantics();
    test_scatter_to_array_and_gather_from_array_round_trip();
    test_scatter_and_gather_array_preserve_explicit_fields_order();
    test_scatter_gather_array_like_and_except_field_filters();
    test_scatter_gather_memvar_preserves_date_and_datetime_like_values();
    test_scatter_gather_array_preserves_date_and_datetime_like_values();
    test_scatter_gather_name_object_round_trip();
    test_scatter_name_additive_merges_existing_object_properties();
    test_scatter_gather_name_single_name_field_filter_semantics();
    test_scatter_gather_name_like_and_except_field_filters();
    test_scatter_gather_memvar_like_and_except_field_filters();
    test_scatter_gather_name_supports_macro_object_variable_names();
    test_scatter_gather_name_supports_nested_object_targets();
    test_scatter_gather_name_supports_macro_expanded_nested_property_segments();
    test_scatter_gather_name_creates_missing_nested_object_targets();
    test_scatter_name_without_additive_replaces_existing_nested_target_object();
    test_scatter_gather_predeclared_2d_array_row_one_semantics();
    test_scatter_gather_two_column_name_value_array_semantics();
    test_scatter_memo_clause_controls_memo_field_inclusion();
    test_gather_from_array_skips_memo_fields_by_default();
    test_gather_memvar_skips_memo_fields_by_default();
    test_scatter_memvar_blank_on_empty_table_succeeds();
    test_runtime_array_mutator_functions();
    test_save_to_writes_variables_to_file();
    test_restore_from_loads_variables_from_file();
    test_save_restore_runtime_errors_localize();
    test_copy_to_runtime_errors_localize();
    test_append_from_array_runtime_errors_localize();
    test_append_from_runtime_errors_localize();
    test_append_from_type_runtime_errors_localize();
    test_scatter_gather_runtime_errors_localize();
    test_set_filter_dimension_sleep_runtime_errors_localize();
    test_restore_from_additive_merges_variables();
    test_save_to_like_pattern_filters_variables();
    test_save_to_except_pattern_filters_variables();
    test_save_restore_auto_mem_extension_without_explicit_extension();
    test_save_restore_round_trips_escaped_string_and_types();
    test_restore_from_honors_current_frame_local_bindings();
    test_save_restore_round_trips_arrays();
    test_restore_from_rejects_invalid_array_dimensions();
    test_save_restore_round_trips_public_scope();
    test_save_to_shadowed_public_name_does_not_persist_public_scope_marker();
    test_restore_from_without_additive_clears_prior_globals();
    test_restore_from_without_additive_clears_stale_arrays();
    test_restore_from_without_additive_clears_private_shadow_state();
    test_restore_from_rejects_numeric_trailing_garbage();
    test_restore_from_parses_numeric_values_invariantly();
    test_copy_to_emits_event();
    test_copy_to_creates_destination_dbf();
    test_copy_structure_to_creates_empty_schema();
    test_copy_structure_extended_emits_vfp_metadata_rows();
    test_copy_to_from_empty_table_produces_valid_empty_dbf();
    test_append_from_copies_records_into_current_table();
    test_append_from_honors_open_source_cursor_filter();
    test_append_from_skips_extra_source_fields();
    test_append_from_rolls_back_matched_field_write_failure();
    test_append_from_is_reverted_by_undo();
    test_append_from_transaction_rollback_restores_destination();
    test_copy_to_type_sdf_writes_fixed_width_text_rows();
    test_append_from_type_sdf_imports_fixed_width_text_rows();
    test_copy_to_type_csv_and_delimited_text_rows();
    test_append_from_type_csv_imports_delimited_rows();
    test_append_from_type_sdf_and_delimited_preserve_explicit_fields_order();
    test_copy_to_type_tab_and_append_from_type_tab_round_trip();
    test_copy_to_type_xls_and_append_from_type_xls_round_trip();
    test_copy_to_type_dif_and_append_from_type_dif_round_trip();
    test_copy_to_type_sylk_and_append_from_type_sylk_round_trip();
    test_copy_to_type_json_and_append_from_type_json_round_trip();
    test_export_database_type_json_writes_catalog_snapshot();
    test_export_database_type_sql_writes_ddl_and_inserts();
    test_import_database_type_json_round_trips_via_export();
    test_copy_to_array_fills_2d_runtime_array();
    test_copy_to_array_fields_clause_allows_keyword_named_field();
    test_append_from_array_writes_records_from_2d_array();
    test_append_from_array_fields_clause_allows_keyword_named_field();
    test_copy_append_array_preserves_explicit_fields_order();
    test_copy_append_array_like_and_except_field_filters();
    test_copy_append_dbf_like_and_except_field_filters();
    test_append_from_array_macro_source_preserves_date_and_datetime_fields();
    test_gather_memvar_round_trips_field_values();
    test_gather_from_array_is_reverted_by_undo();
    test_m_dot_namespace_shares_bare_memory_variable_binding();
    test_browse_emits_effective_cursor_view_metadata();
    test_browse_like_and_except_field_filters_surface_event_metadata();
    test_browse_nowait_remains_a_clause_boundary();
    test_edit_command_emits_runtime_edit_event();
    test_change_command_emits_runtime_change_event();
    test_input_command_emits_runtime_input_event_with_prompt();
    test_accept_command_emits_runtime_accept_event_with_prompt();
    test_input_accept_commands_surface_macro_prompt_and_target_detail();
    test_input_accept_to_local_targets_stay_local_in_routine_scope();
    test_getfile_command_emits_runtime_getfile_event_with_clause_details();
    test_putfile_command_emits_runtime_putfile_event_with_clause_details();
    test_getdir_command_emits_runtime_getdir_event_with_clause_details();
    test_inputbox_command_emits_runtime_inputbox_event_with_clause_details();
    test_dialog_commands_parenthesized_forms_assign_targets_and_extract_positional_details();
    test_wait_window_command_emits_runtime_wait_event();
    test_wait_clear_command_emits_runtime_wait_clear_event();
    test_keyboard_command_emits_runtime_keyboard_event();
    test_display_structure_emits_runtime_display_event();
    test_display_status_surfaces_session_metadata();
    test_display_memory_surfaces_visible_variable_and_array_metadata();
    test_display_memory_hides_internal_application_surfaces();
    test_display_records_surfaces_effective_cursor_view_metadata();
    test_display_and_list_records_surface_resolved_in_target_detail();
    test_display_and_list_structure_surface_target_detail();
    test_list_status_emits_runtime_list_event();
    test_list_memory_surfaces_visible_variable_and_array_metadata();
    test_display_list_memory_like_except_filter_applies_to_output();
    test_list_structure_surfaces_selected_cursor_schema();
    test_list_records_surfaces_effective_cursor_view_metadata();
    test_aerror_content_for_sql_passthrough_fault();

    if (copperfin::test_support::test_failures() != 0) {
        std::cerr << copperfin::test_support::test_failures() << " test(s) failed.\n";
        return EXIT_FAILURE;
    }
    std::cout << "All tests passed.\n";
    return EXIT_SUCCESS;
}
