#!/usr/bin/env sh
# Copyright © 2026 Richard M. Hamilton. All rights reserved.
# Licensed under the Project Copperfin Source-Available License or
# Commercial License. See LICENSE.md in the repository root.
#
# Generates an Ed25519 keypair for signing Project Copperfin commercial
# license files. Works anywhere `openssl` is available (Git Bash / WSL on
# Windows, or natively on Linux/macOS).
#
# The private key this script produces must NEVER be committed to this
# repository or any other shared location. It is written under
# tools/license-signer/keys/, which is excluded via .gitignore.
#
# Usage:
#   ./generate_signing_key.sh <key-name>
#
# <key-name> should identify the machine/purpose, e.g. "windows-test" or
# "ubuntu-server-t7820". It becomes the license file's "signer_key_id",
# so the verifier can pick the right embedded public key later if you
# ever rotate or run multiple signing keys.

set -eu

if [ "${1:-}" = "" ]; then
    echo "usage: $0 <key-name>  (e.g. windows-test, ubuntu-server-t7820)" >&2
    exit 1
fi

NAME="$1"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT_DIR="$SCRIPT_DIR/keys"
mkdir -p "$OUT_DIR"

PRIV="$OUT_DIR/${NAME}_private.pem"
PUB_PEM="$OUT_DIR/${NAME}_public.pem"
PUB_HEADER="$OUT_DIR/${NAME}_public_key.h"

if [ -e "$PRIV" ]; then
    echo "Refusing to overwrite existing key: $PRIV" >&2
    exit 1
fi

openssl genpkey -algorithm ed25519 -out "$PRIV"
chmod 600 "$PRIV" 2>/dev/null || true
openssl pkey -in "$PRIV" -pubout -out "$PUB_PEM"

# An Ed25519 SubjectPublicKeyInfo DER encoding is a fixed 12-byte header
# followed by the 32 raw public-key bytes, so the last 32 bytes of the DER
# form is exactly the raw key.
RAW_HEX=$(openssl pkey -pubin -in "$PUB_PEM" -outform DER | tail -c 32 | xxd -p | tr -d '\n')
C_BYTES=$(echo "$RAW_HEX" | sed 's/../0x&, /g' | sed 's/, $//')

cat > "$PUB_HEADER" <<EOF
// Generated by tools/license-signer/generate_signing_key.sh for key "$NAME".
// Public key only -- safe to commit. NEVER commit ${NAME}_private.pem.
#pragma once

#include <cstdint>

namespace copperfin::licensing {

inline constexpr char kSignerKeyId_${NAME}[] = "$NAME";
inline constexpr std::uint8_t kEd25519PublicKey_${NAME}[32] = {
    $C_BYTES
};

}  // namespace copperfin::licensing
EOF

echo ""
echo "Generated key pair for signer_key_id=\"$NAME\":"
echo "  Private key (DO NOT COMMIT, DO NOT SHARE): $PRIV"
echo "  Public key PEM (safe to commit):           $PUB_PEM"
echo "  Public key C++ header (safe to commit):    $PUB_HEADER"
echo ""
echo "Copy the contents of $PUB_HEADER into"
echo "include/copperfin/licensing/ed25519_public_key.h to let the product"
echo "verify licenses signed with this key."
